### ISSUE TITLE
`pandora-cloud`什么时候可以秽土转生

### ISSUE THREAD

**Issue by RoyRao2333** [pandora-next/deploy#10]
感谢作者的不离不弃，不知道`pandora-cloud`和`pandora-cloud-serverless`什么时候也可以秽土转生？

**Comment by jurieo** [comment]
pandora-next就是他们的合集

**Comment by RoyRao2333** [comment]
@jurieo 

感谢回复，我主要使用serverless部署，没接触过Docker，不知道目前的`pandora-next`如何使用serverless呢？

**Comment by agegr** [comment]
pandora-next 不支持 serverless 部署。目前必须固定ip才能通过验证

**Comment by RoyRao2333** [comment]
@agegr 感谢，看来只有等作者什么时候可以支持一下了

**Comment by jurieo** [comment]
> @agegr 感谢，看来只有等作者什么时候可以支持一下了

neo说了不会支持的，现在发放jwt就是白名单机制，杜绝一些人。

**Comment by thlearncom** [comment]
> > @agegr 感谢，看来只有等作者什么时候可以支持一下了
> 
> neo说了不会支持的，现在发放jwt就是白名单机制，杜绝一些人。

那fakeopen以后会加入验证还是取消支持了呢？
