### ISSUE TITLE
共享账号用不了了？

### ISSUE THREAD

**Issue by Dannyluo233** [pandora-next/deploy#103]
我第一次尝试访问大概是八点半 试了十几个账号都是在转圈圈 没办法使用 偶尔还会跳出来bate Gateway这样的提示 是哪里出了问题吗？

**Comment by Dannyluo233** [comment]
sry 不是bad Gateway 是timeout cloudflare提示的

**Comment by Roulders** [comment]
可能是GPT官网炸了
