### ISSUE TITLE
web端无法复制代码

### ISSUE THREAD

**Issue by xiake23** [pandora-next/deploy#109]
![image](https://github.com/pandora-next/deploy/assets/88986512/4b6731eb-277c-4ac1-b121-f90db85ea947)

**Comment by wozulong** [comment]
readme有写。

**Comment by xiake23** [comment]
> readme有写。

https://github.com/pandora-next/deploy/blob/master/README.md  是这个readme吗,里面没写这种情况怎么解决啊?是否能截图一下?

**Comment by xiake23** [comment]
@wozulong Failed to copy to clipboard这个问题readme好像没写,是否方便指出一下?

**Comment by wozulong** [comment]
<img width="640" alt="image" src="https://github.com/pandora-next/deploy/assets/8010600/ec73e000-0336-4496-a8b3-3e356ddadb9e">

**Comment by xiake23** [comment]
> 这个问题在不使用NGINX不开启https的情况下不能解决吗 @wozulong

**Comment by xiake23** [comment]
> > 这个问题在不使用NGINX不开启https的情况下不能解决吗 @wozulong

对于本地部署不太友好

**Comment by wozulong** [comment]
127.0.0.1 也可以

**Comment by xiake23** [comment]
> 127.0.0.1 也可以

多谢

**Comment by Tsugikuni-Yoriichi** [comment]
@wozulong 但是在docker中不是只能设置为0.0.0.0才能够访问吗？这种情况下不用nginx怎么办呢？
