### ISSUE TITLE
手机端打不开，页面展示空白

### ISSUE THREAD

**Issue by jianml** [pandora-next/deploy#110]

**Comment by nightjoyip** [comment]
手机系统（IOS?）版本太低？

**Comment by jzksnsjswkw** [comment]
<img width="1280" alt="截屏2023-11-22 17 16 35" src="https://github.com/pandora-next/deploy/assets/69855421/d2d52ec7-b354-4f76-8725-a2b0b65481e1">
iOS14.8白屏

**Comment by zhheo** [comment]
iOS17 没有问题

**Comment by jzksnsjswkw** [comment]
貌似类私有方法在iOS15才支持
[ (Safari 14.1 added support for private data member syntax).](https://developer.apple.com/documentation/safari-release-notes/safari-15-release-notes#:~:text=Added%20support%20for%20private%20class%20methods%20and%20accessors)

**Comment by wozulong** [comment]
这个我无力解决，UI扒自官方的压缩js，不方便改动。
