### ISSUE TITLE
想问问关于动态ip的 license.jwt

### ISSUE THREAD

**Issue by Theoshen** [pandora-next/deploy#111]
docker-compose 部署
如果是动态的公网ip，是不是每天更新ip地址之后就得手动更新compose里面的env
然后docker-compose down 再 docker-compose up -d 呢？

**Comment by justmd5** [comment]
看文档 
> https://fakeopen.org/PandoraNext/update.html

**Comment by Theoshen** [comment]
@justmd5 感谢指路
还有另外一个疑问，既然可以选择映射 licences.jwt，那compose 里面的 env 还有啥用呢？

**Comment by justmd5** [comment]
> @justmd5 感谢指路 还有另外一个疑问，既然可以选择映射 licences.jwt，那compose 里面的 env 还有啥用呢？

可以不用那个env了，不映射data目录用的

**Comment by Theoshen** [comment]
@justmd5 谢谢指点，那我自己搞一个脚本去弄自动化

**Comment by Yanyutin753** [comment]
我更新了一个动态ip的版本，正愁没人试

**Comment by Yanyutin753** [comment]
tokentools的动态ip的版本，自动获取ip,自动授权，然后实现热重载，你来我项目看看，加个群，我那个版本还没试过，我自己是固态ip,

**Comment by Yanyutin753** [comment]
去我项目地址：https://github.com/Yanyutin753/PandoraNext-TokensTool
加我项目群
