### ISSUE TITLE
请问https://ai.fakeopen.com  api对话的是否不能调用了

### ISSUE THREAD

**Issue by isJN** [pandora-next/deploy#120]
今天像测试下api是否可用发现其他的功能好像基本都可以，对话的功能不行了，
返回429
response = requests.post(url, headers=headers, json=json_data,stream=True)

**Comment by huaqiesf** [comment]
我这也是

**Comment by wozulong** [comment]
我即将为PandoraNext添加proxy模式，请期待一下。
