### ISSUE TITLE
【求助】Docker部署不能成功

### ISSUE THREAD

**Issue by notomatoes** [pandora-next/deploy#122]
**描述请求**
Docker日志如下， 不能启动
2023/11/23 06:09:22 ============================================================
2023/11/23 06:09:22 Reading local tokens from /data/tokens.json
2023/11/23 06:09:22 Local tokens file does not exist, skipped
2023/11/23 06:09:22 ============================================================
2023/11/23 06:09:24 Ping remote server failed

**环境信息（请完整填写以下信息）：**
- 操作系统：windows+wsl2

**Comment by jzksnsjswkw** [comment]
指定一下DNS

**Comment by RyanFarfetch** [comment]
> 指定一下DNS

这个Remote Server是一段IP，和DNS配置没关系。

**Comment by Jesse1321** [comment]
2023-11-23 15:46:21 2023/11/23 07:46:21 ============================================================
2023-11-23 15:46:21 2023/11/23 07:46:21 Reading local tokens from /data/tokens.json
2023-11-23 15:46:21 2023/11/23 07:46:21 Local tokens file does not exist, skipped
2023-11-23 15:46:21 2023/11/23 07:46:21 ============================================================
2023-11-23 15:46:22 2023/11/23 07:46:22 Ping remote server failed, detail: Access denied., Ip: 43.x.x.x

**Comment by fremindmm** [comment]
M2 芯片 macos14.1.1 
2023/11/23 08:01:57 ============================================================
2023/11/23 08:01:58 Ping remote server failed, detail: Access denied., Ip: 23.142.224.156
2023/11/23 08:02:02 ============================================================
2023/11/23 08:02:02 Reading local tokens from /data/tokens.json
2023/11/23 08:02:02 Loaded 1 tokens
2023/11/23 08:02:02 Loaded 1 shared tokens
2023/11/23 08:02:02 ============================================================
2023/11/23 08:02:03 Ping remote server failed, detail: Access denied., Ip: 23.142.224.156

docker run 不起来 报如上错误，token 和jwt 已配置

**Comment by lvguanjun** [comment]
https://fakeopen.org/PandoraNext/FAQ.html

建议参考k少的文档
