### ISSUE TITLE
【BUG】

### ISSUE THREAD

**Issue by dounine** [pandora-next/deploy#125]
IP已经授权，但启动还是提示未授权，大佬帮忙看一下。
[root@dev1 PandoraNext-v0.2.3-linux-386-ba29c70]# ./PandoraNext 
2023/11/23 04:44:39 ============================================================
2023/11/23 04:44:39 Reading local tokens from tokens.json
2023/11/23 04:44:39 Loaded 1 tokens
2023/11/23 04:44:39 Loaded 0 shared tokens
2023/11/23 04:44:39 ============================================================
2023/11/23 04:44:40 Ping remote server failed, detail: Access denied., Ip: 183.6.105.141

**Comment by wozulong** [comment]
你服务器时间对吗？

**Comment by dounine** [comment]
刚才没对，差了一个小时，我现在已经同步时间了，也是一样
[root@dev1 PandoraNext-v0.2.3-linux-386-ba29c70]# ./PandoraNext 
2023/11/23 17:36:52 ============================================================
2023/11/23 17:36:52 Reading local tokens from tokens.json
2023/11/23 17:36:52 Loaded 1 tokens
2023/11/23 17:36:52 Loaded 0 shared tokens
2023/11/23 17:36:52 ============================================================
2023/11/23 17:36:53 Ping remote server failed, detail: Access denied.,

**Comment by wozulong** [comment]
在这个目录重新执行curl命令

**Comment by dounine** [comment]
重新拉了授权，还是一样的问题，是不是IP有问题
[root@dev1 PandoraNext-v0.2.3-linux-386-ba29c70]# ls -la
总用量 10372
drwxr-xr-x. 2 root root       78 11月 23 17:40 .
drwxr-xr-x. 3 root root     4096 11月 23 17:40 ..
-rw-r--r--. 1 root root      210 11月 23 04:39 config.json
-rw-r--r--. 1 root root      788 11月 23 17:41 license.jwt
-rwxr-xr-x. 1 root root 10600520 11月 23 04:39 PandoraNext
-rw-r--r--. 1 root root      102 11月 23 04:40 tokens.json
[root@dev1 PandoraNext-v0.2.3-linux-386-ba29c70]# ./PandoraNext 
2023/11/23 17:42:10 ============================================================
2023/11/23 17:42:10 Reading local tokens from tokens.json
2023/11/23 17:42:10 Loaded 1 tokens
2023/11/23 17:42:10 Loaded 0 shared tokens
2023/11/23 17:42:10 ============================================================
2023/11/23 17:42:11 Ping remote server failed, detail: Access denied.

**Comment by wozulong** [comment]
看你授权页面上ip对不对的上

**Comment by dounine** [comment]
授权页面显示的是183，后面不知道是多少：
你好，dounine

你的账号已满：9 年，将获得：9000条 / 24小时 对话数量。

当前许可IP: 183 . * . *** . ***，用量：0 / 9000条，重置：0s秒后

**Comment by dounine** [comment]
已经对了，是时间问题，时区不对导致的，感谢大佬提醒。
