### ISSUE TITLE
【求助】请问pandora next可以不走群主的那个代理 直接直连吗

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [pandora-next/deploy#131]
**描述请求**
请问pandora next可以不走群主的那个代理 直接直连吗

**问题陈述**
我有一台海外的vps可以直连openai，用zhile大佬的代理转发感觉有点儿卡，想着物尽其用，把自己的闲置vps用起来

**已采取的步骤**
看不到代码= =

**预期结果**
希望可以用我的vps直连

**截图/日志**
如果适用，请添加截图或日志以帮助说明您的问题。

**环境信息（请完整填写以下信息）：**
- 操作系统：liunx
- 版本：centos7
- 架构：[x86_64]

**Comment by jurieo** [comment]
想的美，那就不用pandora next，这要那要还要。。

**Comment by yuanshangyujingshierlou** [comment]
> 想的美，那就不用pandora next，这要那要还要。。

戾气有点大哈 哥们

**Comment by jurieo** [comment]
> > 想的美，那就不用pandora next，这要那要还要。。
> 
> 戾气有点大哈 哥们

你看群里有人鸟你吗？白嫖还想啥呢

**Comment by yuanshangyujingshierlou** [comment]
> > > 想的美，那就不用pandora next，这要那要还要。。
> > 
> > 
> > 戾气有点大哈 哥们
> 
> 你看群里有人回复你吗？白嫖还想啥呢。你这问题有人问了很多次了，最开始群主或热心群友还回复一下，现在直接无视。别说不走代理，抹标都不行的

抹标是无视群主的劳动成果，不走代理有啥影响呢？觉得代理卡顿 自己有富于的vps，问问都不能？你管的未免也太宽了？

**Comment by YOMIkio** [comment]
> > > > 想的美，那就不用pandora next，这要那要还要。。
> > > 
> > > 
> > > 戾气有点大哈 哥们
> > 
> > 
> > 你看群里有人回复你吗？白嫖还想啥呢。你这问题有人问了很多次了，最开始群主或热心群友还回复一下，现在直接无视。别说不走代理，抹标都不行的
> 
> 抹标是无视群主的劳动成果，不走代理有啥影响呢？觉得代理卡顿 自己有富于的vps，问问都不能？你管的未免也太宽了？

不走代理那直连官方的不就完事了

**Comment by GIfted-Jarvis** [comment]
修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?

**Comment by yuanshangyujingshierlou** [comment]
> > > > > 想的美，那就不用pandora next，这要那要还要。。
> > > > 
> > > > 
> > > > 戾气有点大哈 哥们
> > > 
> > > 
> > > 你看群里有人回复你吗？白嫖还想啥呢。你这问题有人问了很多次了，最开始群主或热心群友还回复一下，现在直接无视。别说不走代理，抹标都不行的
> > 
> > 
> > 抹标是无视群主的劳动成果，不走代理有啥影响呢？觉得代理卡顿 自己有富于的vps，问问都不能？你管的未免也太宽了？
> 
> 不走代理那直连官方的不就完事了
但是这样就得每次都打开梯子，想着是把程序挂到vps上，然后直接访问vps就行了，这样也可以给朋友使用

**Comment by yuanshangyujingshierlou** [comment]
> 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?

我试下，但是这个是要在本地建个代理吗

**Comment by GIfted-Jarvis** [comment]
> > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> 
> 我试下，但是这个是要在本地建个代理吗

我也不清楚, 刚发现这个项目, 正在研究中.
其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来

**Comment by yuanshangyujingshierlou** [comment]
> > > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> > 
> > 
> > 我试下，但是这个是要在本地建个代理吗
> 
> 我也不清楚, 刚发现这个项目, 正在研究中. 其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来

好的 谢谢了，我试一下

**Comment by jurieo** [comment]
> > > > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> > > 
> > > 
> > > 我试下，但是这个是要在本地建个代理吗
> > 
> > 
> > 我也不清楚, 刚发现这个项目, 正在研究中. 其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来
> 
> 好的 谢谢了，我试一下

直接说结果吧，不可以。这里的代理proxy_url是指定部署服务流量走代理，并通过群佬的代理来完成请求，相当于有2次代理。如果这都可以，那群佬的jwt不就简单的被绕过了。

**Comment by yuanshangyujingshierlou** [comment]
> > > > > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> > > > 
> > > > 
> > > > 我试下，但是这个是要在本地建个代理吗
> > > 
> > > 
> > > 我也不清楚, 刚发现这个项目, 正在研究中. 其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来
> > 
> > 
> > 好的 谢谢了，我试一下
> 
> 直接说结果吧，不可以。这里的代理proxy_url是指定部署服务流量走代理，并通过群佬的代理来完成请求，相当于有2次代理。如果这都可以，那群佬的jwt不就简单的被绕过了。

jwt不是为了限制使用吗，防止有人乱请求浪费大佬的资源

**Comment by YOMIkio** [comment]
> > > > > > 想的美，那就不用pandora next，这要那要还要。。
> > > > > 
> > > > > 
> > > > > 戾气有点大哈 哥们
> > > > 
> > > > 
> > > > 你看群里有人回复你吗？白嫖还想啥呢。你这问题有人问了很多次了，最开始群主或热心群友还回复一下，现在直接无视。别说不走代理，抹标都不行的
> > > 
> > > 
> > > 抹标是无视群主的劳动成果，不走代理有啥影响呢？觉得代理卡顿 自己有富于的vps，问问都不能？你管的未免也太宽了？
> > 
> > 
> > 不走代理那直连官方的不就完事了
> > 但是这样就得每次都打开梯子，想着是把程序挂到vps上，然后直接访问vps就行了，这样也可以给朋友使用

你不是海外vps，还挂什么梯子

**Comment by jurieo** [comment]
> > > > > > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> > > > > 
> > > > > 
> > > > > 我试下，但是这个是要在本地建个代理吗
> > > > 
> > > > 
> > > > 我也不清楚, 刚发现这个项目, 正在研究中. 其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来
> > > 
> > > 
> > > 好的 谢谢了，我试一下
> > 
> > 
> > 直接说结果吧，不可以。这里的代理proxy_url是指定部署服务流量走代理，并通过群佬的代理来完成请求，相当于有2次代理。如果这都可以，那群佬的jwt不就简单的被绕过了。
> 
> jwt不是为了限制使用吗，防止有人乱请求浪费大佬的资源

算了，你没有理解群老开发pandora-next的初衷，低门槛使用和避免滥用。你不走他的代理，如何防止滥用。。如果你仅仅想不走群主的代理，这个项目不适合你，github有大把的项目可以选择，搜搜。

**Comment by yuanshangyujingshierlou** [comment]
> > > > > > > 修改[data/config.json](https://github.com/pandora-next/deploy/blob/master/data/config.json)里的 `proxy_url` 是否可以呢?
> > > > > > 
> > > > > > 
> > > > > > 我试下，但是这个是要在本地建个代理吗
> > > > > 
> > > > > 
> > > > > 我也不清楚, 刚发现这个项目, 正在研究中. 其实你还有个办法, 在远程主机上装桌面, 或者改用 windows, 然后 RDP 直将 Chrome 远程桌面出来
> > > > 
> > > > 
> > > > 好的 谢谢了，我试一下
> > > 
> > > 
> > > 直接说结果吧，不可以。这里的代理proxy_url是指定部署服务流量走代理，并通过群佬的代理来完成请求，相当于有2次代理。如果这都可以，那群佬的jwt不就简单的被绕过了。
> > 
> > 
> > jwt不是为了限制使用吗，防止有人乱请求浪费大佬的资源
> 
> 算了，你没有理解群老开发pandora-next的初衷，低门槛使用和避免滥用。你不走他的代理，如何防止滥用。。如果你仅仅想不走群主的代理，这个项目不适合你，github有大把的项目可以选择，搜搜。

避免滥用是为了让更多人可以使用，如果我不走大佬的代理，就不会占用大佬的服务器资源，不影响啊。谢谢你了，我再看看吧

**Comment by g-mero** [comment]
如果你的网络能够直接访问chatgpt的话，可以自行搭建反代服务，我写了一个简单的程序，通过一些手段绕过了chatGpt的waf，但必须保证你的网络是能够直接访问chatGPT的，github上也有不少开源的反代项目，不过我试了一些不太行，我自己写的docker镜像：gmeroo/chatgpt-proxy: 0.0.2 暴露8888端口,  /conversation 反代

**Comment by CHN-STUDENT** [comment]
计划在国内机器搭建一个朋友一起合租用，目前看了两种 cws 和 pandora，我们有 tz 和 plus 账号，只是想走自己的 tz 了。看起来不支持么？
