### ISSUE TITLE
【求助】

### ISSUE THREAD

**Issue by lnsane** [pandora-next/deploy#133]
![image](https://github.com/pandora-next/deploy/assets/20310872/a899fccc-d178-44a9-b0e8-69379b52da1e)
![image](https://github.com/pandora-next/deploy/assets/20310872/ef584d0e-0f38-4a0f-babc-0b814075f323)

咋回事呀？

**Comment by xxlong2333** [comment]
为什么我docker不能运行！！哭死

**Comment by xxlong2333** [comment]
![image](https://github.com/pandora-next/deploy/assets/109356746/da801917-9f77-494b-ac96-70492ef2ce44)

**Comment by xxlong2333** [comment]
![image](https://github.com/pandora-next/deploy/assets/109356746/f6ce65cc-54b4-4d11-a7b0-7f9f082f7645)

**Comment by wozulong** [comment]
> ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> 
> 咋回事呀？

你抹标，我没说错吧？

**Comment by fu-jw** [comment]
围观首例

**Comment by lnsane** [comment]
> > ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> > 咋回事呀？
> 
> 你抹标，我没说错吧？

不懂呀？啥意思？

**Comment by wozulong** [comment]
> > > ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> > > 咋回事呀？
> > 
> > 
> > 你抹标，我没说错吧？
> 
> 不懂呀？啥意思？

你部署的页面上， Powered by PandoraNext文字和链接去哪了？

**Comment by nanbei-zhuge** [comment]
前排围观

**Comment by lnsane** [comment]
> > > > ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> > > > 咋回事呀？
> > > 
> > > 
> > > 你抹标，我没说错吧？
> > 
> > 
> > 不懂呀？啥意思？
> 
> 你部署的页面上， Powered by PandoraNext文字和链接去哪了？

原来是这个原因是吧？那我弄回去就行了？我不清除不能自定义呀

**Comment by wozulong** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> > > > > 咋回事呀？
> > > > 
> > > > 
> > > > 你抹标，我没说错吧？
> > > 
> > > 
> > > 不懂呀？啥意思？
> > 
> > 
> > 你部署的页面上， Powered by PandoraNext文字和链接去哪了？
> 
> 原来是这个原因是吧？那我弄回去就行了？我不清除不能自定义呀

不是不能自定义，没有必要抹除项目标志。请保留：

1. Powered by PandoraNext文字和链接
2. About PandoraNext文字和链接

其余你可随意更改。

**Comment by lnsane** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/20310872/285368235-a899fccc-d178-44a9-b0e8-69379b52da1e.png) ![image](https://user-images.githubusercontent.com/20310872/285368378-ef584d0e-0f38-4a0f-babc-0b814075f323.png)
> > > > > > 咋回事呀？
> > > > > 
> > > > > 
> > > > > 你抹标，我没说错吧？
> > > > 
> > > > 
> > > > 不懂呀？啥意思？
> > > 
> > > 
> > > 你部署的页面上， Powered by PandoraNext文字和链接去哪了？
> > 
> > 
> > 原来是这个原因是吧？那我弄回去就行了？我不清除不能自定义呀
> 
> 不是不能自定义，没有必要抹除项目标志。请保留：
> 
> 1. Powered by PandoraNext文字和链接
> 2. About PandoraNext文字和链接
> 
> 其余你可随意更改。

OK。我会保留这些信息在页面下面
