### ISSUE TITLE
要怎么部署啊？

### ISSUE THREAD

**Issue by Zhuangmoumou** [pandora-next/deploy#136]

**Comment by lnts2015** [comment]
看 [README.md](https://github.com/pandora-next/deploy#readme)

**Comment by Zhuangmoumou** [comment]
为什么curl -fLO "https://dash.pandoranext.com/data/.../license.jwt"这个命令返回结果是curl: (35) Recv failure: Connection was reset？
以及PandoraNext.exe运行后也返回Ping remote server failed？

**Comment by Zhuangmoumou** [comment]
有大佬能用GitPod部署吗？

**Comment by wozulong** [comment]
> 为什么curl -fLO "[https://dash.pandoranext.com/data/.../license.jwt"这个命令返回结果是curl](https://dash.pandoranext.com/data/.../license.jwt%22%E8%BF%99%E4%B8%AA%E5%91%BD%E4%BB%A4%E8%BF%94%E5%9B%9E%E7%BB%93%E6%9E%9C%E6%98%AFcurl): (35) Recv failure: Connection was reset？ 以及PandoraNext.exe运行后也返回Ping remote server failed？

你这是网络不通啊。

**Comment by Zhuangmoumou** [comment]
> > 为什么curl -fLO "[https://dash.pandoranext.com/data/.../license.jwt"这个命令返回结果是curl](https://dash.pandoranext.com/data/.../license.jwt%22%E8%BF%99%E4%B8%AA%E5%91%BD%E4%BB%A4%E8%BF%94%E5%9B%9E%E7%BB%93%E6%9E%9C%E6%98%AFcurl): (35) Recv failure: Connection was reset？ 以及PandoraNext.exe运行后也返回Ping remote server failed？
> 
> 你这是网络不通啊。

用了梯子也一样结果啊

**Comment by huangdihd** [comment]
> > > 为什么curl -fLO "[https://dash.pandoranext.com/data/.../license.jwt"这个命令返回结果是curl](https://dash.pandoranext.com/data/.../license.jwt%22%E8%BF%99%E4%B8%AA%E5%91%BD%E4%BB%A4%E8%BF%94%E5%9B%9E%E7%BB%93%E6%9E%9C%E6%98%AFcurl): (35) Recv failure: Connection was reset？ 以及PandoraNext.exe运行后也返回Ping remote server failed？
> 
> > 
> 
> > 你这是网络不通啊。
> 
> 
> 
> 用了梯子也一样结果啊
我也遇到了这个问题，试了下用wget下，成功了

**Comment by Zhuangmoumou** [comment]
> > > > 为什么curl -fLO "[https://dash.pandoranext.com/data/.../license.jwt"这个命令返回结果是curl](https://dash.pandoranext.com/data/.../license.jwt%22%E8%BF%99%E4%B8%AA%E5%91%BD%E4%BB%A4%E8%BF%94%E5%9B%9E%E7%BB%93%E6%9E%9C%E6%98%AFcurl): (35) Recv failure: Connection was reset？ 以及PandoraNext.exe运行后也返回Ping remote server failed？
> > 
> > 
> > > 
> > 
> > 
> > > 你这是网络不通啊。
> > 
> > 
> > 用了梯子也一样结果啊
> > 我也遇到了这个问题，试了下用wget下，成功了

那PandoraNext.exe怎么办？
