### ISSUE TITLE
对于/share/的对话分享，忽略site_password【功能】

### ISSUE THREAD

**Issue by itsHenry35** [pandora-next/deploy#137]
**您的功能请求是否与问题有关？请描述。**
现在已经支持对话分享可以不登陆查看，但是如果设置了site_password，外人就无法查看分享。我是想要外人无法创建对话，但可以访问到对话分享。

**描述您想要的解决方案**
增加配置文件的一项，使得对话分享可以不被site_password控制

**描述您考虑过的替代方案**
无

**附加上下文**
无

谢谢！

**Comment by wozulong** [comment]
share会请求不少接口，这意味着无法保护这些接口。
