### ISSUE TITLE
【BUG】proxy模式请求gpt-4 api失败，报"Our systems have detected unusual activity from your system. Please try again later."；切换web模式使用gpt-4正常；切换使用gpt3.5 api正常

### ISSUE THREAD

**Issue by Seayouth** [pandora-next/deploy#142]
**描述错误**
proxy模式下，**请求gpt-4 api失败**，报"Our systems have detected unusual activity from your system. Please try again later."
_补充：本账号确认为Plus账号，并且**切换为web模式，可以正常使用gpt-4**，登录官方网站，也可以正常使用gpt-4_；**请求gpt3.5 api也是正常**

**复现步骤**
按照以下步骤复现错误：
1. 手动模式部署 PandoraNext-v0.2.3-linux-amd64
2. 配置 server_mode为proxy
{
  "bind": "127.0.0.1:8181",
  "timeout": 600,
  "proxy_url": "",
  "public_share": false,
  "site_password": "",
  "setup_password": "",
  "server_tokens": true,
  "server_mode": "proxy",
  "whitelist": null
}
3. 发送gpt4 api请求
curl --location 'https://${HOST}/backend-api/conversation' \
--header 'Content-Type: application/json' \
--header 'Accept: text/event-stream' \
--header 'Authorization: Bearer ${TOKEN}' \
--data '{
    "action": "next",
    "messages": [
        {
            "author": {
                "role": "user"
            },
            "content": {
                "content_type": "text",
                "parts": [
                    "hi"
                ]
            }
        }
    ],
    "parent_message_id": "",
    "model": "gpt-4",
    "timezone_offset_min": -480
}'
4. 观察到错误
![image](https://github.com/pandora-next/deploy/assets/20473508/7b30a15f-9460-424d-a6f4-b7faf003f733)

5. 发送gpt3.5 api请求，响应正常
![image](https://github.com/pandora-next/deploy/assets/20473508/89793bad-1564-478b-abb5-c9cd86a23d24)

**服务器（请完成以下信息）：**
 - 操作系统：Linux
 - 版本：ubuntu22
 - 架构：amd64

感谢

**Comment by AuditAIH** [comment]
目前好像还没有开启4.0的支持 仅支持3.5 然后我的centos8一只是请求到not found 大佬能指点一下哪儿的问题吗？
我的QQ402084119

**Comment by wozulong** [comment]
proxy模式不会打码，需自行处理。

**Comment by Seayouth** [comment]
@AuditAIH 基本按我上面"复现步骤"内容，结合作者README就可以。gpt3.5 api可以正常调用我没有遇到其他问题。如果你有其他问题建议提一个新的issue

**Comment by ziyuewu1105** [comment]
@Seayouth 你好，请问你解决了吗？怎么调用gpt-4模型呢？
