### ISSUE TITLE
【求助】

### ISSUE THREAD

**Issue by wangjinyi425** [pandora-next/deploy#147]
**描述请求**
在使用pandora的proxy模式，/backend-api/conversation body的内容

**问题陈述**
当我想使用uuid进行连续对话时，他只会覆盖原对话，创建uuid一样的新对话

**已采取的步骤**
无

**预期结果**
可以使用api连续对话

**截图/日志**
无

**环境信息：**
- Windows
- 11
- x64
**正在使用的工具/框架**
Python

**相关代码片段**
无
**附加背景**
无
---

小号给了star，大号忘记给了

**Comment by wozulong** [comment]
第一次对话你只需要生成随机的uuid提交。它会返回一个conversation_id，后续的对话你需要使用它返回的conversation_id，并且将它返回的message_id作为parent_id，这样才能让对话一条连着一条。

**Comment by wangjinyi425** [comment]
问题是使用了这个方法后他会重复在一个对话，就相当于更改对话。这样好像没有记忆。
’‘‘python
import requests
import json
class ChatGPT:
    def __init__(self,prompt,token):
        self.token = token
        self.prompt = prompt
        self.headers = {
        'Accept': 'text/event-stream',
        'Content-Type': 'application/json',
        'Authorization': 'Bearer '+self.token
        }
        prompt_gpt = self._send_chatgpt('','',self.prompt)
        self.conversation_id = prompt_gpt[1]
        self.message_id = prompt_gpt[2]
    def get_jsdata(self,cid,mid,text):
        if mid == '':
            json_data = {'action': 'next','messages': [{'author': {'role': 'user',},'content': {'content_type': 'text','parts': [text,],},'metadata': {},},],'model': 'text-davinci-002-render-sha','parent_message_id': '','timezone_offset_min': -480}
        else:
            json_data = {'conversation_id':cid,'action': 'next','messages': [{'author': {'role': 'user',},'content': {'content_type': 'text','parts': [text,],},'metadata': {},},],'model': 'text-davinci-002-render-sha','parent_message_id': mid,'timezone_offset_min': -480}
        return json_data
    def _send_chatgpt(self,cid,mid,text):
        response = requests.post('http://127.0.0.1:8181/backend-api/conversation', json=self.get_jsdata(cid,mid,text), headers=self.headers)
        json_rd = response.content.decode('utf-8').replace('data: ','~').split('~')[-3]
        return json.loads(json_rd)['message']['content']['parts'][0],json.loads(json_rd)['conversation_id'],json.loads(json_rd)['message']['id']
    def send_message(self,text):
        return self._send_chatgpt(self.conversation_id,self.message_id,text)[0]
’‘’
这是代码
