### ISSUE TITLE
/auth/login返回{'detail': 'service overload'}【求助】

### ISSUE THREAD

**Issue by shiyegao** [pandora-next/deploy#148]
**描述请求**
我按照[fakeopen文档](https://fakeopen.org/Pandora/%E7%99%BB%E5%BD%95%E7%9B%B8%E5%85%B3/%E6%8E%A5%E5%8F%A3%E5%88%97%E8%A1%A8.html#_2-auth-login)发现没办法返回accesstoken，不知道问题出在了哪里。（好像前一段时间是可以的）

**已采取的步骤**
我尝试了curl，python，也尝试了/auth/refresh，都是同样的结果

**预期结果**
希望可以获得一个login的接口。

**环境信息（请完整填写以下信息）：**
- 操作系统：macOS

**相关代码片段**
```bash
curl --location 'https://ai.fakeopen.com/auth/login' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=' \
--data-urlencode 'password='
```

**Comment by su-fen** [comment]
接口已经停用了，等群佬后续通知

**Comment by wozulong** [comment]
接口我关掉了，后续应该会通过PandoraNext暴露。
