### ISSUE TITLE
有没有类似之前的API

### ISSUE THREAD

**Issue by huangdihd** [pandora-next/deploy#154]
有没有类似之前`/api/conversation/talk`这种免费聊天接口?

**Comment by QAbot-zh** [comment]
![image](https://github.com/pandora-next/deploy/assets/40236765/605d0747-9997-41af-9db5-b3f6f5de7e30)

**Comment by huangdihd** [comment]
这个好像要花钱？

**Comment by huangdihd** [comment]
proxy模式是要付费的吧

**Comment by huangdihd** [comment]
那就是mode改成proxy然后调用/backend-api/之前的地址就行了？

**Comment by zhushen12580** [comment]
求教程

**Comment by Hibiscus-Lily** [comment]
> 那就是mode改成proxy然后调用/backend-api/之前的地址就行了？
对，其他的按照config，把mode改为proxy，请求地址为`http://127.0.0.1:8181/backend-api/conversation`

**Comment by wozulong** [comment]
这个并不会收费。具体参数请F12查看网页端对话的请求记录。
