### ISSUE TITLE
【求助】backend-api调用

### ISSUE THREAD

**Issue by ziyuewu1105** [pandora-next/deploy#159]
backend-api有哪些api可以调用？有没有相关的文档手册啊？

**Comment by clippers1** [comment]
有么

**Comment by ziyuewu1105** [comment]
> 有么

https://fakeopen.org/Pandora/ChatGPT%E7%9B%B8%E5%85%B3/%E6%8E%A5%E5%8F%A3%E5%88%97%E8%A1%A8.html
这个好像是一些API的手册，很多都要自己参考官网的api，用开发者工具去看

**Comment by 14790897** [comment]
似乎不用，但提示{"detail":{"message":"Unauthorized - Access token is missing"}}

**Comment by ziyuewu1105** [comment]
> 似乎不用，但提示{"detail":{"message":"Unauthorized - Access token is missing"}}

你使用的是access token吗？请求的url是什么？

**Comment by 14790897** [comment]
curl  -X POST -H "Content-Type: application/json"  --location 'http://ip地址:8181/backend-api/conversation' -H "Authorization: Bearer $token" -d '
{
    "action": "next",
    "messages": [
        {
            "id": "aaa243c4-799e-4340-b17a-fb378626cbed",
            "author": {
                "role": "user"
            },
            "content": {
                "content_type": "text",
                "parts": [
                    "骑自行车要戴头盔吗"
                ]
            },
            "metadata": {}
        }
    ],
    "conversation_id": "ed5b639b-8f0d-4493-bfbb-c1aca6166a1e",
    "parent_message_id": "072dddc7-b319-42be-b24d-f49c5ee99c9a",
    "model": "text-davinci-002-render-sha",
    "timezone_offset_min": -480,
    "suggestions": [],
    "history_and_training_disabled": false,
    "arkose_token": null,
    "conversation_mode": {
        "kind": "primary_assistant"
    },
    "force_paragen": false,
    "force_rate_limit": false
}'

**Comment by ziyuewu1105** [comment]
> ```
> curl  -X POST -H "Content-Type: application/json"  --location 'http://ip地址:8181/backend-api/conversation' -H "Authorization: Bearer $token" -d '
> {
>     "action": "next",
>     "messages": [
>         {
>             "id": "aaa243c4-799e-4340-b17a-fb378626cbed",
>             "author": {
>                 "role": "user"
>             },
>             "content": {
>                 "content_type": "text",
>                 "parts": [
>                     "骑自行车要戴头盔吗"
>                 ]
>             },
>             "metadata": {}
>         }
>     ],
>     "conversation_id": "ed5b639b-8f0d-4493-bfbb-c1aca6166a1e",
>     "parent_message_id": "072dddc7-b319-42be-b24d-f49c5ee99c9a",
>     "model": "text-davinci-002-render-sha",
>     "timezone_offset_min": -480,
>     "suggestions": [],
>     "history_and_training_disabled": false,
>     "arkose_token": null,
>     "conversation_mode": {
>         "kind": "primary_assistant"
>     },
>     "force_paragen": false,
>     "force_rate_limit": false
> }'
> ```

不好意思，我是用python发请求的，curl我没使用过。
我按照你的数据发送了一次请求，没有出现你的问题
或者你的access token过期了？

**Comment by 14790897** [comment]
python我会，能否给个代码示例呢？感谢

**Comment by ziyuewu1105** [comment]
> python我会，能否给个代码示例呢？感谢
`import requests
import json

url = "http://<base url>/backend-api/conversation"
payload = {
  'action': "next",
  'arkose_token': "null",
  'conversation_id': "73f458de-4dea-4d37-a019-0c519540d847",
  'conversation_mode': {
    'kind': "primary_assistant"
  },
  'force_paragen': False,
  'force_rate_limit': False,
  'history_and_training_disabled': False,
  'messages': [
    {
      'author': {
        'role': "user"
      },
      'content': {
        'content_type': "text",
        'parts': [
          "介绍一下你自己"
        ]
      },
      'metadata': {}
    }
  ],
  'model': "gpt-3.5",
  'parent_message_id': "2e946b79-d453-4ead-b778-031cac0dcabb",
  'suggestions': [],
  'timezone_offset_min': -480
}
headers = {
  'Content-Type': 'application/json',
  'Authorization': 'Bearer <token>'
}
response = requests.request("POST", url, headers=headers, data=json.dumps(payload))
print(response.text)`

**Comment by 14790897** [comment]
感谢
![谢谢GIF](https://github.com/pandora-next/deploy/assets/121866954/8dd2872c-4e4b-4ad0-b650-174689826ffd)

**Comment by 14790897** [comment]
我使用了这个方法，还是不行😢

**Comment by ziyuewu1105** [comment]
> 我使用了这个方法，还是不行😢

你可以先/token/register注册一个share token,然后使用这个share token试试。你也可以试一下使用/v1/chat/completions这个api

**Comment by ziyuewu1105** [comment]
> 我使用了这个方法，还是不行😢

你是不是server_mode没有开启proxy，我刚才发现使用web模式也会提示Access token is missing

**Comment by 14790897** [comment]
我是docker compose运行的，请问怎么开启代理？

子月五 ***@***.***> 于 2023年11月29日周三 下午3:55写道：

**Comment by 14790897** [comment]
好的， 我看到怎么修改了

**Comment by 14790897** [comment]
但是现在返回：’File not found.‘

**Comment by 14790897** [comment]
谢谢你，刚刚url写错了，现在终于成功了
