### ISSUE TITLE
【求助】{   "code": 400,   "message": "please reload page" }

### ISSUE THREAD

**Issue by xielk** [pandora-next/deploy#162]
**描述请求**
外面套了层CDN

**问题陈述**
{
  "code": 400,
  "message": "please reload page"
}

**预期结果**
是套用CDN要重新授权TOKEN还是?

**环境信息（请完整填写以下信息）：**
- 操作系统：[例如 Windows、macOS、Linux]
- 版本：[例如 10、Catalina、Ubuntu 20.04]
- 架构：[例如 x86_64、arm64]

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by wozulong** [comment]
很有可能是你套cdn导致前端和源的域名不匹配，导致cookie无法写入。

**Comment by vivighr** [comment]
我和你遇见的问题一样，直接删除浏览器中该网站的cookie就可以，换个浏览器也行。
