### ISSUE TITLE
【BUG】

### ISSUE THREAD

**Issue by kuke21** [pandora-next/deploy#165]
大佬，反馈一个问题，1H2G 30M 香港地区 docker部署  使用GTP4模型 刚开始很快一秒吐10来个字  和AI交流多了 内容多了后很明显半天吐不出一个字 没办法吧兑换删除了 新开一个 又回到秒吐10来个字  
我(西南地区)到云服务器 延迟56ms 很稳的延迟  云服务器到代理1ms

**Comment by wozulong** [comment]
GPT-4很多时候官方就很慢，可以多方比较排查问题。比如你可以在你的搭建、演示站、官方进行多方比较。
