### ISSUE TITLE
【求助】使用share token（选择会话需要隔离生成的）登录后其他人的会话显示*号，这个可以设置不显示其他人的会话吗

### ISSUE THREAD

**Issue by lucky1999** [pandora-next/deploy#167]
使用share token（选择会话需要隔离生成的）登录后其他人的会话显示*号，这个可以设置不显示其他人的会话吗
<img width="248" alt="image" src="https://github.com/pandora-next/deploy/assets/29088542/439cbbfe-a5aa-4b79-b6fd-fcc32eb32d2d">

**Comment by wozulong** [comment]
新UI官方拿掉了`Show more`按钮，不占位无法随滚动加载会话，会导致会话拉取不全。
