### ISSUE TITLE
【BUG】

### ISSUE THREAD

**Issue by zhangbinhui** [pandora-next/deploy#168]
**描述错误**
始皇，我在 tokens.json 配置了三个不同账号的 token，这么做是担心账号本身有流控，所以设置了三个账号。前两个用的session token，第三个用的access token, 第三个是我刚刚生成的，并且都设置"shared": true。
我在shared.html登录进入第一个之后，后面的两个就算用无痕模式也会提示 token expired 。
我一开始以为是 token 问题，但尝试用 token 直接登录 chat.zhile.io 是可以的。
而且我用官网登录不同账号，发现共享出去的页面也是正常的，有其他人在正常使用，但我自己却只能用第一个。

**复现步骤**
按照以下步骤复现错误：
1. 前往 'https://pandora.zbhai.top'
2. 进入网站后，点击 'Go share chat'
3. 选择第一个可以用，后面两个不能用。
4. 观察到Token is expired。

**预期行为**
后面两个应该也能正常进入聊天，而不是提示Token is expired。

**截图**
这个是我的token.json
![image](https://github.com/pandora-next/deploy/assets/7031406/7948062b-72a3-4d90-b3b7-21ae36b5b745)

这个是我的nginx.conf 关于shared.html的配置，微调，没有抹标
![image](https://github.com/pandora-next/deploy/assets/7031406/bb4de454-47e9-4c3e-a8c2-b574a56ea69f)

问题就是这样，我自己只能用第一个，后两个不行。但我用官网登录后面两个账号，发现共享出去的页面也是正常的，有其他人在正常使用。

![f4c5aa03d575a810ac55da4ec5e55e4](https://github.com/pandora-next/deploy/assets/7031406/a05fdd59-7d8e-4da0-91bf-cf5628971d8a)

**服务器（请完成以下信息）：**
 - 操作系统：[ubuntu]
 - 版本：[22]
 - 架构：[arm64]

**桌面（请完成以下信息）：**
 - 操作系统：[windows]
 - 浏览器：[例如 chrome]
 - 版本：[119.0.6045.160（正式版本） （64 位）]

**智能手机（请完成以下信息）：**
 - 设备：[小米14]
 - 操作系统：[Hyper OS]
 - 浏览器：[chrome]
 - 版本：[119.0.6045.163]

**附加上下文**
其他需要补充的，可以随时联系我，谢谢。

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by wozulong** [comment]
token expired 是通过access token中的exp字段来进行判断的。session token可以换出access token，但不是那个access t oken就一定能用的。

**Comment by zhangbinhui** [comment]
> token expired 是通过access token中的exp字段来进行判断的。session token可以换出access token，但不是那个access t oken就一定能用的。

**Comment by zhangbinhui** [comment]
> token expired 是通过access token中的exp字段来进行判断的。session token可以换出access token，但不是那个access t oken就一定能用的。

感谢，但是问题access token 并不是用session token 换出来的，我直接用https://chat.openai.com/api/auth/session 获取的，肯定在有效期。拿着这个access token 在https://chat1.zhile.io 也可以登录的，而且也能看到其他人正在用这个token 对应的share chat。而我自己点开这个却会报token expired ，所以我才会提一个bug，怀疑是不是PandoraNext 本身做了限制？某种环境下只能使用一个账号产生的shared chat？
