### ISSUE TITLE
【BUG】docker-compose部署，更新到最新版之后启动提示”License ID is required“

### ISSUE THREAD

**Issue by befantasy** [pandora-next/deploy#172]
**描述错误**
【BUG】docker-compose部署，更新到最新版之后启动提示”License ID is required“

**复现步骤**
按照以下步骤复现错误：
【BUG】docker-compose部署，更新到最新版之后启动提示”License ID is required“

**预期行为**
清晰且简洁地描述您预期会发生什么。

**截图**
如果适用，添加截图以帮助解释您的问题。

**服务器（请完成以下信息）：**
 - 操作系统：[oracle linux]
 - 版本：[8]
 - 架构：[arm64]

**桌面（请完成以下信息）：**
 - 操作系统：[例如 iOS]
 - 浏览器：[例如 chrome, safari]
 - 版本：[例如 22]

**智能手机（请完成以下信息）：**
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如 stock browser, safari]
 - 版本：[例如 22]

**附加上下文**
在此处添加关于问题的任何其他上下文。

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by befantasy** [comment]
发现config.json有了很大变化，license授权方式也变了。release notes里没提。问题已经解决。

**Comment by mummyrain** [comment]
> 发现config.json有了很大变化，license授权方式也变了。release notes里没提。问题已经解决。

我也遇到了相同的问题，请您是怎么解决这个问题的？
![Uploading Snipaste_2023-11-28_01-06-26.png…]()

**Comment by mummyrain** [comment]
> 发现config.json有了很大变化，license授权方式也变了。release notes里没提。问题已经解决。

我也遇到了相同的问题，请问您是怎么解决这个问题的？
<img width="1195" alt="Snipaste_2023-11-28_01-06-26" src="https://github.com/pandora-next/deploy/assets/5226397/c369748f-ed73-4a7b-ab96-398fb93c1d8a">

**Comment by mummyrain** [comment]
问题解决了，config.json文件配置相较于老版本发生了变化。

![微信截图_20231128012640](https://github.com/pandora-next/deploy/assets/5226397/ee342724-7baf-4d33-be8b-4c8e6dc8efaf)
<img width="801" alt="Snipaste_2023-11-28_01-25-09" src="https://github.com/pandora-next/deploy/assets/5226397/dd319e0d-45e5-46e5-bc46-f6aa902c4a36">
![微信截图_20231128012550](https://github.com/pandora-next/deploy/assets/5226397/2d41aaef-2b4e-48b1-8f56-bed6e03e48c0)
