### ISSUE TITLE
docker日志出现access denied，无法使用

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [pandora-next/deploy#177]
页面无法进入出现
![image](https://github.com/pandora-next/deploy/assets/87591236/b130f89b-4156-471a-8030-ac8b7d2450f0)
![image](https://github.com/pandora-next/deploy/assets/87591236/a4e6f07d-2058-4f03-bc9e-59851b35c0c3)

这是docker日志
![image](https://github.com/pandora-next/deploy/assets/87591236/1fc08e57-f90d-42cf-b3c2-275e61285adb)
获取的jwt
![image](https://github.com/pandora-next/deploy/assets/87591236/9def8fa7-e181-4080-afe5-b2bd0849e48f)
docker版本
![image](https://github.com/pandora-next/deploy/assets/87591236/3ec36c6b-00da-4100-a8e1-572b93b70beb)

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by wozulong** [comment]
ip和授权不匹配。
