### ISSUE TITLE
【求助】请求接口报错

### ISSUE THREAD

**Issue by auhgnep** [pandora-next/deploy#189]
大大，请教个问题，现在我部署的一个python服务调用pandora请求总是报错，提示：POST https://ai.fakeopen.com/api/conversation "HTTP/1.1 429 Too Many Requests"
不知道是什么原因，之前我以为是accessToken过期了，换了也一样。

**Comment by thlearncom** [comment]
那个停止服务了，你看现在这个项目的proxy模式，自己部署后请求自己pandoranext的接口

**Comment by wozulong** [comment]
请使用PandoraNext
