### ISSUE TITLE
【求助】proxy模式请求gpt-4模式时，不能正确响应

### ISSUE THREAD

**Issue by thlearncom** [pandora-next/deploy#191]
**问题陈述**
使用proxy模式部署，使用第三方前端在请求gpt-4模式时，不能正确响应，而并将模型改为gpt-3.5时可以正确响应

**已采取的步骤**
已经检查官网gpt-4的次数没有用完，账号正常，access token正常有效，pandoraNext正确配置了最新版本，且是proxy模式。
测试保持其他请求不变，将模型改为gpt-3.5时可以正确响应，而gpt4时，则不行，查看官网只有发送过去的消息，没有回复任何内容，且没有选择任何gpt模型，并提示There was an error generating a response，查看Pandoranext的日志显示200，没有报错，具体如图。
当使用其他反代项目时，如ninja，则3.5和4都可以，但是这个项目比较繁琐而且不熟悉，此代理项目的gpt4需要提供har文件通过验证，考虑我遇到的不能响应的问题是否也和gpt4的特殊验证有关？以及这样是不是可以排除掉前端的问题？我的前端使用的是开源项目Chanzhaoyu/chatgpt-web。

**预期结果**
gpt4的请求应当和3.5一样

**截图/日志**
![image](https://github.com/pandora-next/deploy/assets/104374208/25cb9b4d-ad73-421b-ab8b-6c2a35d786fc)
![image](https://github.com/pandora-next/deploy/assets/104374208/eb9119a5-18ad-4fee-8c1d-81571e8796ad)

**环境信息（请完整填写以下信息）：**
- 操作系统：[Linux]
- 版本：[Ubuntu 20.04]
- 架构：[ x86_64]

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

**Comment by liaoxinyi** [comment]
附议，使用proxy模式下，在获取licenseId的时候，提示本机ip被限制了。猜测应该是反代服务器限制了从代理服务器发起的licenseId请求
使用环境：docker

**Comment by wozulong** [comment]
proxy模式使用backend-api接口一切自行处理。不过现在0.4.0版本已经可用chat2api，可以试试。

**Comment by 14790897** [comment]
我也一样的问题

**Comment by 14790897** [comment]
懂了，要输入arkose token
