### ISSUE TITLE
【求助】本机Docker 安装，proxy模式，接口访问

### ISSUE THREAD

**Issue by aston314** [pandora-next/deploy#192]
我想请求以下接口，但不知道怎么访问：

/api/auth/refresh POST
/api/token/info/fk-xxx GET
/api/auth/session POST
/api/token/register POST
/api/auth/login POST (1:100)

我访问url为：
http://192.168.2.1:8181/backend-api/auth/refresh
http://192.168.2.1:8181/backend-api/token/info/fk-xxx
http://192.168.2.1:8181/backend-api/auth/session
http://192.168.2.1:8181/backend-api/token/register 
http://192.168.2.1:8181/backend-api/auth/auth/login

Docker日志中，访问以上接口均为404，请问如何正确访问。

**Comment by wozulong** [comment]
写的是 /api/ 你为什么请求的是 /backend-api/ ?

**Comment by aston314** [comment]
/api/也请求不了。

http://192.168.2.1:8181/api/token/register

File not found.

**Comment by wozulong** [comment]
1. 查看服务日志，确认服务是proxy模式启动
2. 这个接口是POS方法

**Comment by aston314** [comment]
是proxy模式
stderr: =  OS:		Linux
stderr: =  Arch:	arm64
stderr: =  Version:	v0.3.1
stderr: =  BuildId:	c48d546
stderr: =  Mode:	proxy
stderr: =  Bind:	http://0.0.0.0:8181/

谢谢，我尝试下post方法。

**Comment by Carrot404** [comment]
@aston314 hello, lz成功了吗？我倒是想请教
