### ISSUE TITLE
【BUG】上下文过长会造成卡顿 甚至提示页面等待响应

### ISSUE THREAD

**Issue by jamexiansen** [pandora-next/deploy#193]
**描述错误**
同一个对话上下文很长 会造成加载时间很长 卡顿以及 无响应

**复现步骤**
按照以下步骤复现错误：
1、前提 很长的上下文
2、发送问题
3、卡顿 或者 提示等待响应

**预期行为**
清晰且简洁地描述您预期会发生什么。

**截图**
![上下文过长](https://github.com/pandora-next/deploy/assets/76086917/438a2527-7d51-4c2d-8075-7318a2bd4bdb)
![image](https://github.com/pandora-next/deploy/assets/76086917/a30afd28-9425-4153-93f1-cfe75c4d80d6)

**服务器（请完成以下信息）：**
 - 操作系统：ubuntu
 - 版本：22.04
 - 架构：x86_64

**桌面（请完成以下信息）：**
 - 操作系统：window11
 - 浏览器：edge
 - 版本：119.0.2151.72 (正式版本) (64 位)

**附加上下文**
在此处添加关于问题的任何其他上下文。

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by wozulong** [comment]
这可能不是上下文的问题。可能是你网络波动。请尝试不同网络环境。
