### ISSUE TITLE
【BUG】proxy模式下上传文件时返回的url为https://files.oaiusercontent.com/，使用web模式返回https://files.pandoranext.com/

### ISSUE THREAD

**Issue by ziyuewu1105** [pandora-next/deploy#196]
{
    "status": "success",
    "upload_url": "https://files.oaiusercontent.com/file-AP6ei2R2G6eSzTiXT6z6Wubz?se=2023-11-29T08%3A07%3A56Z&sp=cw&sv=2021-08-06&sr=b&sig=H3XDUuzb7EwJ1Zbzumm/Ys6ke7KwLPTUPhYxg3y0mWw%3D",
    "file_id": "file-AP6ei2R2G6eSzTiXT6z6Wubz"
}
这是使用proxy模式调用http://xxx/backend-api/files接口时的返回，之后调用upload_url里的url上传文件，返回状态码是201，最后调用http://xxx/backend-api/files/xxxxxx/uploaded，返回如下：
{
    'status': 'error',
    'error_code': 'internal_error', 
    'error_message': None
}
我使用的版本是v0.3.2

**期望结果**

proxy模式下应该要返回https//files.pandoranext.com/的url

**Comment by wozulong** [comment]
prox模式任何东西自行处理。
