### ISSUE TITLE
【BUG】现在次数不走jwt授权了嘛

### ISSUE THREAD

**Issue by KrystalandBarry** [pandora-next/deploy#197]
**描述错误**
提问报次数限制，但是jwt授权次数还有很多

**复现步骤**

**预期行为**

**截图**
![image](https://github.com/pandora-next/deploy/assets/33093118/e6e28ebf-a3a8-4bb4-be73-ecae85eed682)
![image](https://github.com/pandora-next/deploy/assets/33093118/13077916-a3b5-4613-a10d-fd6d96e886eb)

**Comment by KrystalandBarry** [comment]
刷新重启对话，可以问一下，然后又不行了
![image](https://github.com/pandora-next/deploy/assets/33093118/2fa38608-3029-4377-8530-3b2b5edb80c1)

**Comment by wozulong** [comment]
这是GPT-4次数限制，跟jwt限制无关。
