### ISSUE TITLE
vps问题

### ISSUE THREAD

**Issue by Tomleolt** [pandora-next/deploy#20]
请问下，香港的vps可以部署吗？有ipv4

**Comment by JAM2199562** [comment]
替陛下答复，吾皇没有禁止你，能不能访问OpenAI要你自己试，所以你不该在这里开这个issues

**Comment by Tomleolt** [comment]
> 替陛下答复，吾皇没有禁止你，能不能访问OpenAI要你自己试，所以你不该在这里开这个issues

好的，好的
