### ISSUE TITLE
【求助】使用proxy模式，提示404：file not found

### ISSUE THREAD

**Issue by foxhank** [pandora-next/deploy#201]
**描述请求**
使用docker部署服务，设置为proxy模式，随后使用另一程序调用此api接口，提示：ChatGPT error 404: File not found.同时docker日志也出现404报错

**问题陈述**

大佬好！我尝试使用docker部署程序，部分配置文件设置如下：
```
  "bind": "0.0.0.0:8181",
......
  "server_mode": "proxy",
  "proxy_api_prefix": "",
······
```
，随后使用另一程序（chatgpt-web）尝试通过access token访问api，参考说明文档中的“设置为proxy后通过/backend-api/”，返回ChatGPT error 404: {"detail":"Not Found"}，同时日志显示
```
`ChatGPTError: ChatGPT error 404: {"detail":"Not Found"}
    at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.2.4/node_modules/chatgpt/build/index.js:55:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 404,
  statusText: 'Not Found',
  [cause]: _Response [Response] {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 404,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Found',
      headersList: [_HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: _HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
```
,Pandora日志提示
`[GIN] 2023/11/29 - 13:40:13 | 404 |  400.741505ms |      172.17.0.1 | POST     "/backend-api/"`
**已采取的步骤**
最开始使用127.0.0.1访问，提示failed to fetch，同时日志提示connect ECONNREFUSED字样，随后尝试根据issue #192将ip地址切成内网地址，
设置为http://172.30.250.23:8181/api/则出现error 404: File not found
设置为http://172.30.250.23:8181/backend-api/则出现error 404: {"detail":"Not Found"}
.Pandora设置为proxy模式，系统信息是：
```
`===================
=  OS:		Linux
=  Arch:	amd64
=  Version:	v0.4.0
=  BuildId:	173fc76
=  Mode:	proxy
=  Bind:	http://0.0.0.0:8181/
=
```
,使用post方法，post请求是
```
POST http://172.30.250.23:8181/backend-api {
  body: {
    action: 'next',
    messages: [ [Object] ],
    model: 'gpt-3.5-turbo',
    parent_message_id: '8af1437c-c814-4207-8425-704e576bd2b7'
  },
  headers: {
    Authorization: 'Bearer xxx',
    Accept: 'text/event-stream',
    'Content-Type': 'application/json'
  }
}
````
**预期结果**
成功返回回答内容。

**截图/日志**
根据issue #192尝试过不同域名，均为404错误。
```
[GIN] 2023/11/29 - 13:19:33 | 404 |      21.735µs |      172.17.0.1 | POST     "/api/token/"
[GIN] 2023/11/29 - 13:38:13 | 404 |  1.238347762s |      172.17.0.1 | POST     "/backend-api/token/"
[GIN] 2023/11/29 - 13:38:42 | 404 |  383.923297ms |      172.17.0.1 | POST     "/backend-api/"
```
我使用的是chatgpt-web，原来使用的是fakeopen的接口，是正常使用的，后提示“429错误，建议切换到Pandora Next”，遂尝试安装，但是却出现404错误。
**环境信息（请完整填写以下信息）：**
- 操作系统：Linux 
- 版本：Debian 11 Linux 5.10.0
- 架构：x86-64

**正在使用的工具/框架**
使用docker-compose方法部署

**附加背景**
最开始尝试请求127.0.0.1:8181，提示failed to fetch:connect econnrefuse 错误，随后使用内网地址访问，无论怎么设置都是404错误。

求大佬解答！

---

**Comment by wozulong** [comment]
对话接口是 /backend-api/conversation 而不是 /backend-api
