### ISSUE TITLE
【BUG】proxy模式设置了proxy_api_prefix后，xxx/backend-api/conversation不能正常工作。

### ISSUE THREAD

**Issue by xiaosaaaa** [pandora-next/deploy#203]
**描述错误**
在最新的0.4.1版本，proxy模式设置了proxy_api_prefix后，xxx/backend-api/conversation不能正常工作，日志显示404。
xxx/v1/chat/completions正常工作。
proxy_api_prefix留空后二者都正常。

补充一下，xxx/backend-api/conversation用的是accesstoken，xxx/v1/chat/completions用的是sharetoken。

**服务器（请完成以下信息）：**
 - 操作系统：Ubuntu 
 - 版本：20.04.1 LTS
 - 架构：x86，amd64

**Comment by wozulong** [comment]
请更新v0.4.2
