### ISSUE TITLE
【求助】tokens.json中需要输入的 session token和refresh token从哪里获取

### ISSUE THREAD

**Issue by by123456by** [pandora-next/deploy#205]
**描述请求**
tokens.json中需要输入的 session token和refresh token从哪里获取
**已采取的步骤**
我搜索issues没找到如何获取这两个值，通过/api/auth/session和cookies获取只有accessToken
**环境信息（请完整填写以下信息）：**
CentOS 7的docker环境

**Comment by ZSW-QQ3628761** [comment]
![Uploading image.png…]()

session token

**Comment by by123456by** [comment]
@ZSW-QQ3628761 这是图片吗，我加载不出来

**Comment by zhangshaowei-code** [comment]
登录https://chat.openai.com/
按F12
点击应用程序
查看储存里面的cookie
搜索__Secure-next-auth.session-token即可得到session-token

**Comment by by123456by** [comment]
> 登录https://chat.openai.com/ 按F12 点击应用程序 查看储存里面的cookie 搜索__Secure-next-auth.session-token即可得到session-token

自部署的不能获取吗
![image](https://github.com/pandora-next/deploy/assets/15666692/a871cc4e-56cb-4a5f-ba9a-3e480db80010)

**Comment by phhh-xh** [comment]
session-token 多久过期啊 我退出了 怎么就过期了

**Comment by wozulong** [comment]
使用proxy模式调用相应接口。可以参考readme
