### ISSUE TITLE
【BUG】如果用的share-token，是不是无法edit  gpts啊

### ISSUE THREAD

**Issue by KrystalandBarry** [pandora-next/deploy#207]
**描述错误**
如果用的share-token，是不是无法edit  gpts

**复现步骤**

**预期行为**

**截图**
![image](https://github.com/pandora-next/deploy/assets/33093118/d3e3ee15-eda5-4fd0-99f4-494b890686a4)
正常用accesstoken和官方登录是有的
![image](https://github.com/pandora-next/deploy/assets/33093118/bcb90e4b-07f5-44d0-aa39-0bdc65c0f05d)

**Comment by ljnchn** [comment]
生成的时候，把“展示账号邮箱"点上

**Comment by KrystalandBarry** [comment]
> 生成的时候，把“展示账号邮箱"点上

可以了谢谢
