### ISSUE TITLE
【求助】Ping remote server failed

### ISSUE THREAD

**Issue by nssiwi** [pandora-next/deploy#215]
**问题陈述**
我用的是windows本地直接exe部署的，今天下午更新0.4.2版本之后就开始出现-Ping remote server failed-

**已采取的步骤**
1、按照群里大神的办法拉取了最新的0.4.4版本exe，删除license.jwt文件，config文件在0.4.4的模板的基础上只填写了license_id、site_password、setup_password，然后在cmd命令中运行PandoraNext.exe程序
2、程序成功生成了license.jwt文件并写入了授权代码
3、根据网络请求日志发现dail client-api.pandoranext.com:443 提示timeout，尝试ping或者telnet均提示不通

**截图/日志**
2023/11/30 19:28:39 ============================================================
2023/11/30 19:28:39 Reading local tokens from tokens.json
2023/11/30 19:28:39 Loaded 1 tokens
2023/11/30 19:28:39 Loaded 0 shared tokens
2023/11/30 19:28:39 ============================================================
2023/11/30 19:29:00 Ping remote server failed

**环境信息（请完整填写以下信息）：**
- 操作系统：Windows
- 版本：10
- 架构：arm64

**Comment by leezhuuu** [comment]
我在docker中也发现了这个问题

另外，我发现fakeopen的api挂了，是我的问题吗，你们现在用的咋样？

**Comment by nssiwi** [comment]
> 我在docker中也发现了这个问题
> 
> 另外，我发现fakeopen的api挂了，是我的问题吗，你们现在用的咋样？

我刚更换了dns，可以了，就是dns的问题

**Comment by lixiangyu0506** [comment]
> > 我在docker中也发现了这个问题
> > 另外，我发现fakeopen的api挂了，是我的问题吗，你们现在用的咋样？
> 
> 我刚更换了dns，可以了，就是dns的问题

请问dns换成多少？
