### ISSUE TITLE
【BUG】docker部署出现 Ping remote server failed问题

### ISSUE THREAD

**Issue by leezhuuu** [pandora-next/deploy#216]
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 Reading local tokens from /data/tokens.json
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 Loaded 1 tokens
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 Loaded 2 shared tokens
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 ============================================================
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 "proxy_api_prefix" < 8 chars or too weak, proxy mode off!
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 ============================================================
2023-11-30 19:50:18 PandoraNext  | 2023/11/30 11:50:18 Ping remote server failed

docker部署出现问题，大家也有这样的情况吗？

**Comment by leezhuuu** [comment]
已解决，是代理的问题

**Comment by Tourweint** [comment]
请问是怎么解决

**Comment by leezhuuu** [comment]
不要用docker，直接部署就好了，docker会出现很多奇奇怪怪的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月28日(周四) 晚上11:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216)




 
请问是怎么解决

**Comment by Tourweint** [comment]
谢谢，按照你说的，解决了，这项目还是部署到服务器好一些，在本地每次开启都比较麻烦



---Original---
From: ***@***.***&gt;
Sent at: 2023年12月28日(Thu) Evening11:57
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216)




 不要用docker，直接部署就好了，docker会出现很多奇奇怪怪的问题 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年12月28日(周四) 晚上11:42 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216) 
 
 
 
 
   
 请问是怎么解决

**Comment by leezhuuu** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月29日(周五) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216)




 谢谢，按照你说的，解决了，这项目还是部署到服务器好一些，在本地每次开启都比较麻烦 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Sent at: 2023年12月28日(Thu) Evening11:57 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216) 
 
 
 
 
  不要用docker，直接部署就好了，docker会出现很多奇奇怪怪的问题  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年12月28日(周四) 晚上11:42  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题: Re: [pandora-next/deploy] 【BUG】docker部署出现 Ping remote server failed问题 (Issue #216)  
   
   
   
   
     
  请问是怎么解决
