### ISSUE TITLE
https://ai.fakeopen.com/v1/chat/completions api使用出现问题

### ISSUE THREAD

**Issue by leezhuuu** [pandora-next/deploy#217]
使用作者的api的时候，今天傍晚报错
{
  "error": true,
  "message": "Load failed"
}

api的地址为https://ai.fakeopen.com/v1/chat/completions 
上午使用时正常的，pandora的网页端一切正常，唯独api出现问题,换账号也不行
大家也这样吗，还是我自己的问题呢?

**Comment by leezhuuu** [comment]
import requests
import json
import subprocess

api_key = "xxxxxxxx"
api_endpoint = "https://ai.fakeopen.com/v1/chat/completions"
# 设置请求头
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {api_key}"
}

# 设置请求体
def get_user_input():
    # user_input = input("请输入一个问题或指令: ")
    user_input = input()
    return user_input

def get_ai_response(user_input):
    data = {
        "model": "gpt-3.5-turbo",
        "messages": [
            {"role": "system", "content": "你是由chatgpt驱动的codeinterpreter，当前系统为macos,每次收到用户的信息时，请判断你的工作模式，再进行相应的任务。你有两个模式，模式一：用户向你发出可执行指令，则使用python程序（优先）或者bash命令完成相应任务，请只回答代码，不要回复其他内容；模式二：用户想和你进行对话，请正常对话，不要输出任何形式的代码，自然地、严谨的语气与用户进行对话。每次收到用户的信息时，请判断你的工作模式，再进行相应的任务。"},
            # {"role": "system", "content": "你是由chatgpt驱动的codeinterpreter"},
            {"role": "user", "content": user_input}
        ]
    }

    # 发送POST请求
    response = requests.post(api_endpoint, headers=headers, data=json.dumps(data))

    # 解析响应
    result = response.json()
    ai_response = result["choices"][0]["message"]["content"]

    return ai_response

def execute_code(code):
    if code.startswith('```python') and code.endswith('```'):
        python_code = code[10:-3]  # 剥离Python代码块的标记
        try:
            exec(python_code)
        except Exception as e:
            print(f"执行Python代码时发生错误: {e}")
    elif code.startswith('```bash') and code.endswith('```'):
        shell_command = code[8:-3]  # 剥离Shell命令的标记
        try:
            # 使用Colab的内置功能执行Shell命令
            output = subprocess.getoutput(shell_command)
            print(output)
        except Exception as e:
            print(f"执行Shell命令时发生错误: {e}")
    else:
        print("未知类型的代码")

def main():
    while True:
        user_input = get_user_input()
        if user_input.lower() == 'exit':
            print("程序结束。")
            break

        ai_response = get_ai_response(user_input)
        # print("AI生成的代码:")
        print(ai_response)

        execute_code(ai_response)

if __name__ == "__main__":
    main()




结果为Request failed with status code 429，意味着在短时间内发送了太多的请求，超过了API的限制，但是目前还不清楚是如何导致的，请问你们遇到这个问题了吗

**Comment by mycurjerry** [comment]
我在请求https://ai.fakeopen.com/v1/chat/completions提示如下信息：需要更新PandoraNext版本？{
    "error": {
        "message": "It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }

**Comment by thmarx** [comment]
+1

**Comment by johe123qwe** [comment]
+1

**Comment by leezhuuu** [comment]
等作者修复吧

**Comment by wozulong** [comment]
#219
