### ISSUE TITLE
作者把 https://ai.fakeopen.com/v1/chat/completions 关了吗？

### ISSUE THREAD

**Issue by lys623** [pandora-next/deploy#219]
![image](https://github.com/pandora-next/deploy/assets/4364314/3ddb8443-31ab-4ff4-af36-02eb1a30d755)
报错了

**Comment by mycurjerry** [comment]
同问

**Comment by leezhuuu** [comment]
下午6点的时候就已经不能用了

**Comment by wozulong** [comment]
PandoraNext可以部署当作chat2api使用，fakeopen的接口也没有保留的必要了。

**Comment by lys623** [comment]
> PandoraNext可以部署当作chat2api使用，fakeopen的接口也没有保留的必要了。

不会部署docker，还是fakeopen简单

**Comment by wozulong** [comment]
> > PandoraNext可以部署当作chat2api使用，fakeopen的接口也没有保留的必要了。
> 
> 不会部署docker，还是fakeopen简单

不是非要用docker部署啊

**Comment by crosspacific** [comment]
还是更喜欢fakeopen的api模式，简单方便。用不到PandoraNext的网页模式。

**Comment by lys623** [comment]
> > > PandoraNext可以部署当作chat2api使用，fakeopen的接口也没有保留的必要了。
> > 
> > 
> > 不会部署docker，还是fakeopen简单
> 
> 不是非要用docker部署啊

怎么弄，求助 @wozulong
