### ISSUE TITLE
皇上吉祥，请问登录chat1.zhile.io后，怎么查看accesstoken？

### ISSUE THREAD

**Issue by pureage1** [pandora-next/deploy#22]
如题，
因为我想直接把accesstoken发给朋友，让朋友用accesstoken再进入，这样他就不用挂梯子了。

**Comment by thlearncom** [comment]
> 如题， 因为我想直接把accesstoken发给朋友，让朋友用accesstoken再进入，这样他就不用挂梯子了。

登录官网后，打开下面的连接可以看到token，https://chat.openai.com/api/auth/session

**Comment by pureage1** [comment]
> > 如题， 因为我想直接把accesstoken发给朋友，让朋友用accesstoken再进入，这样他就不用挂梯子了。
> 
> 登录官网后，打开下面的连接可以看到token，https://chat.openai.com/api/auth/session

不是，我用自己美国服务器 搭建的梯子 登chat.openai.com登不进去，我也不知道原因。 但挂梯子登chat1.zhile.io 是能登进去。我想知道在登入chat1.zhile.io的时候，怎么查看access token 。。。。

**Comment by thlearncom** [comment]
> > > 如题， 因为我想直接把accesstoken发给朋友，让朋友用accesstoken再进入，这样他就不用挂梯子了。
> > 
> > 
> > 登录官网后，打开下面的连接可以看到token，https://chat.openai.com/api/auth/session
> 
> 不是，我用自己美国服务器 搭建的梯子 登chat.openai.com登不进去，我也不知道原因。 但挂梯子登chat1.zhile.io 是能登进去。我想知道在登入chat1.zhile.io的时候，怎么查看access token 。。。。

目测是看不了，你都输入密码了，后台获取一下token就好了，没必要再返回了啊。你试试去这里拿10天有效期的access token吧：https://ai-20230626.fakeopen.com/auth

**Comment by pureage1** [comment]
好的！谢谢了！

**Comment by wozulong** [comment]
看不了一点。只要能查看，就会被当作登录接口刷起来，那帮人就是这样。
