### ISSUE TITLE
【功能】禁用会话隔离的标签点击

### ISSUE THREAD

**Issue by JS-an** [pandora-next/deploy#224]
**您的功能请求是否与问题有关？请描述。**
如题

**描述您想要的解决方案**
隔离会话时，不是该share的标签可以禁止点击，防止触发

**描述您考虑过的替代方案**
无

**附加上下文**
![image](https://github.com/pandora-next/deploy/assets/25688878/b75b661c-95e8-4aa7-b478-b5a58e2bc05e)

**Comment by wspzf** [comment]
要是能隐藏才是更好

**Comment by wozulong** [comment]
目前没办法解决这个问题。新版本可以更改这 *  的文字。后续再看。
