### ISSUE TITLE
【功能】能否以GitHub获得的所有星数作为额度的另一个评价标准呢？

### ISSUE THREAD

**Issue by 14790897** [pandora-next/deploy#226]
**您的功能请求是否与问题有关？请描述。**
注册未满一年，但是经常贡献开源项目

**描述您想要的解决方案**
以GitHub获得的所有星数作为额度的另一个评价标准

**Comment by 14790897** [comment]
> 前段时间国外新闻爆出有些求职者花钱刷star让自己的简历更好看

相对公平就好

**Comment by 14790897** [comment]
那不可能，你不了解咱们的秦始皇

lys623 ***@***.***> 于 2023年12月2日周六 下午6:17写道：

**Comment by wozulong** [comment]
这种能人为改动的指标并不好，暂不考虑。
