### ISSUE TITLE
新增整合FakeAPI的服务到One-API，实现自动刷新，多账号管理

### ISSUE THREAD

**Issue by Yanyutin753** [pandora-next/deploy#23]
管理密码比较麻烦，想着能简单点拿到key，就用One-API来发放令牌，自己写了一个工具网站，来增加渠道，希望能让我们吾皇的项目更好！
项目地址：https://github.com/Yanyutin753/fakeApiTool-One-API

**Comment by Yanyutin753** [comment]
拿到One-APIkey就可以用到很多的地方，比如ChatGPT Next Web 还有企微机器人等等

**Comment by walnutsandwich** [comment]
赞一个
