### ISSUE TITLE
【求助】https://ai.fakeopen.com/v1/chat/completions 被关了，哪里有类似服务，求分享

### ISSUE THREAD

**Issue by lys623** [pandora-next/deploy#232]
如题，不知道什么原因，作者不支持这接口调用了。

**Comment by wozulong** [comment]
部署这个项目，按照文档开启proxy模式。

**Comment by wspzf** [comment]
自建就可以用了

**Comment by showthesunli** [comment]
> > > 部署这个项目，按照文档开启proxy模式。
> > 
> > 
> > @wozulong 请问部署该项目所使用的服务器，是否是必须在openai支持的地区？国内的服务器行吗？
> 
> 随便在哪都可以部署

谢谢回答，还有另外一个问题：请问由同一个chatGPT账户生成的多个shared token，组成的一个pool token，是否可以规避chatGPT的并发数限制？

还是说必须使用不同的chatGPT账号生成的shared token来组成一个pool token 才能规避并发限制？
