### ISSUE TITLE
【求助】现在还能在其他软件里面使用fk-XXXXXX API吗？

### ISSUE THREAD

**Issue by crosspacific** [pandora-next/deploy#236]
**描述请求**
现在还能在其他软件里面使用fk-XXXXXX API吗？
**问题陈述**
作者的 https://ai.fakeopen.com/v1/chat/completions 现在已经关停了，fk-XXXXXX不能在其他软件使用了。

**已采取的步骤**
我搭建了pandora-next，也设置proxy_api_prefix，开启了proxy 模式。pandora-next可以正常使用。请问可以在其他软件，使用我自己的网址，然后使用fk-XXXXXX吗？我试了一下，提示SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON 

**预期结果**
能使用自己的网址反代，使用fk-XXXXXX API。

**截图/日志**

![20231202213758](https://github.com/pandora-next/deploy/assets/48462348/3e138916-a13d-460f-9ca5-3cf379ecbe06)

**环境信息（请完整填写以下信息）：**
- 操作系统：[Linux]
- 版本：[Ubuntu 20.04]
- 架构：[ x86_64]

**正在使用的工具/框架**
无

**相关代码片段**
无

**附加背景**
无

---

**Comment by Jacky-Bruse** [comment]
同问，求支持

**Comment by crosspacific** [comment]
> 我测试是可以用的， proxy_api_prefix 你必须设置一个不少于8位，且同时包含数字和字母的前缀才能开启proxy模式！ 以上地址均需在最前面增加 /<proxy_api_prefix>，也就是你设置的前缀。 根据以上提示，在第三方地址里面写入域名/<proxy_api_prefix>/v1/chat/completions 就可以了

谢谢。我去试一试。

**Comment by crosspacific** [comment]
> 我这是可以用的

谢谢。我已经成功了。 @Jacky-Bruse   @wspzf
