### ISSUE TITLE
【BUG】无法正常生成share token

### ISSUE THREAD

**Issue by BBrother-GFC** [pandora-next/deploy#241]
使用POST请求无法正常生成share token（/v1/chat/completions是可以正常使用的）
![image](https://github.com/pandora-next/deploy/assets/51117375/56a0c981-a129-48b0-82ea-531a1f511f0a)

另外再说一句，自己部署的pandoranext也还是可以使用pk-this-is-a-real-free-pool-token-for-everyone这个免费共享token，不知道是不是一个从pandora下来的功能忘记删了

**Comment by wozulong** [comment]
是否有设置Body？

免费token就是能用的，只是不能在fakeopen上用。

**Comment by BBrother-GFC** [comment]
请问body应该设置成什么？图片中的勾不勾上的返回都一样
![image](https://github.com/pandora-next/deploy/assets/51117375/886e1628-a067-45ee-991c-1db4fdcc629d)

**Comment by crosspacific** [comment]
> 请问body应该设置成什么？图片中的勾不勾上的返回都一样 ![image](https://private-user-images.githubusercontent.com/51117375/287503514-886e1628-a067-45ee-991c-1db4fdcc629d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDgwNjIsIm5iZiI6MTcwMTYwNzc2MiwicGF0aCI6Ii81MTExNzM3NS8yODc1MDM1MTQtODg2ZTE2MjgtYTA2Ny00NWVlLTk5MWMtMWRiNGZkY2M2MjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEyNDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYTQ2MDZmNjk2ZGI4YTQzNzU0MmI3ZWUwYzE3NWViNjZjN2YyMWZkNzNiNGJmZWZiYzU4YmJmOWYyNTdlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJNfAEASNS4JH63zVHyvZ8tK1QDyBjyBrlhjm_BINw8)

你好，我也想询问怎么用自己搭建的pandaora-next生成share token。请问你解决了吗？

**Comment by BBrother-GFC** [comment]
> > 请问body应该设置成什么？图片中的勾不勾上的返回都一样 ![image](https://private-user-images.githubusercontent.com/51117375/287503514-886e1628-a067-45ee-991c-1db4fdcc629d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MDgwNjIsIm5iZiI6MTcwMTYwNzc2MiwicGF0aCI6Ii81MTExNzM3NS8yODc1MDM1MTQtODg2ZTE2MjgtYTA2Ny00NWVlLTk5MWMtMWRiNGZkY2M2MjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDEyNDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYTQ2MDZmNjk2ZGI4YTQzNzU0MmI3ZWUwYzE3NWViNjZjN2YyMWZkNzNiNGJmZWZiYzU4YmJmOWYyNTdlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJNfAEASNS4JH63zVHyvZ8tK1QDyBjyBrlhjm_BINw8)
> 
> 你好，我也想询问怎么用自己搭建的pandaora-next生成share token。请问你解决了吗？

没，我也不知道在f12中的哪里看具体请求信息
还是希望始皇能够完善下share token申请的readme吧😢

**Comment by crosspacific** [comment]
https://fakeopen.org/Pandora/%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF.html
