### ISSUE TITLE
宝塔面板部署容器后启动不起来

### ISSUE THREAD

**Issue by lyp88997** [pandora-next/deploy#25]
宝塔面板部署容器后启动不起来，模版内容一致，也授权IP了
容器日志
2023/11/15 15:28:19 Unable to verify the server's license: token contains an invalid number of segments

version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "8181:8181"
    environment:
      - PANDORA_NEXT_LICENSE=<JWT Token>

**Comment by long-dotcom** [comment]
你的环境变量填写的啥呀，是授权页命令行那个吗

**Comment by lyp88997** [comment]
我不知道怎么填

**Comment by long-dotcom** [comment]
> 我不知道怎么填

你授权后会在你服务器同级目录下生成一个jwt文件，docker配置里的环境变量填文件里的字串

**Comment by wozulong** [comment]
授权页面给的命令会让你下载一个license.jwt的文件，docker部署时用文件里的内容字符串作为PANDORA_NEXT_LICENSE环境变量。

**Comment by peter-zx** [comment]
docker run -d --restart always --name PandoraNext -p 8181:8181 \
           -e PANDORA_NEXT_LICENSE="<JWT Token>" pengzhile/pandora-next
我正确替换了token
然后run

结果就是 镜像在不断的重启。端口也设置好了
 STATUS  
 Restarting

**Comment by lyp88997** [comment]
> docker run -d --restart always --name PandoraNext -p 8181:8181 -e PANDORA_NEXT_LICENSE="" pengzhile/pandora-next 我正确替换了token 然后run
> 
> 结果就是 镜像在不断的重启。端口也设置好了 STATUS Restarting

看看日志
我用第一个命令没有授权上，用第二个授权上就可以了
