### ISSUE TITLE
【求助】

### ISSUE THREAD

**Issue by knight-666** [pandora-next/deploy#253]
**描述请求**
Error #01: Post "https://client-api.pandoranext.com/backend-api/conversation": dial tcp: lookup client-api.pandoranext.com on 9.9.9.9:53: read udp 172.17.0.4:56149->9.9.9.9:53: read: no route to host

这是咋的了

**问题陈述**

**已采取的步骤**

**预期结果**
描述您期望得到的帮助或解决方案

**截图/日志**
![image](https://github.com/pandora-next/deploy/assets/28332512/d6c42a84-ece8-46da-a1a8-44e9bfbee3a3)

**环境信息（请完整填写以下信息）：**
docker

**Comment by wozulong** [comment]
dns解析失败，试试换换dns
