### ISSUE TITLE
【BUG】Firefox中边栏的聊天记录无法自动刷新

### ISSUE THREAD

**Issue by pureair** [pandora-next/deploy#256]
**描述错误**
边栏的聊天记录无法自动刷新，新建会话之后，新会话不会出现在边栏。

**复现步骤**
按照以下步骤复现错误：
1. 使用firefox浏览器
2. 新建一个会话
3. 聊天一次，新会话不会出现在边栏
4. 再新建一个会话聊天一次，新建的两个会话都不会出现在边栏，且刷新后也看不到。

**预期行为**
新建的会话会自动出现在边栏。

**截图**
--

**服务器（请完成以下信息）：**
 - 操作系统：Debian
 - 版本：12
 - 架构：arm64, docker

**桌面（请完成以下信息）：**
 - 操作系统：Windows
 - 浏览器：firefox
 - 版本：120

**附加上下文**
使用了CDN
开启F12，网络页，禁用cache重载，侧边栏看不到新增会话的记录
开启F12，储存页，删掉cache，重载，侧边栏能看到新增会话
Chrome浏览器，同站点、账号，新建会话聊天后，边栏会自动插入新记录，并且自动命名。

**Comment by wozulong** [comment]
不太了解，我演示站测试下来firefox没有问题。

**Comment by pureair** [comment]
最后试出了解决办法。F12 - Application - Service Workers - service-worker.js - unregister 刷新后就好了。（之前清理过站点数据无效。）

**Comment by pureair** [comment]
最后发现还是网络环境的问题。直连下聊天没有问题，边栏刷新会出问题。全局以后就都正常了。😂

**Comment by pureair** [comment]
最后还是排查出来了。问题不在pandora，是我反代用的caddy，header需要手动添加cache-control: no-cache
