### ISSUE TITLE
【功能】能够打开用链接分享的 GPTs

### ISSUE THREAD

**Issue by QYQSDTC** [pandora-next/deploy#258]
**您的功能请求是否与问题有关？请描述。**
除了从 Explore 里面打开官方的 gpts，希望能够打开别人用链接分享的 gpts

**描述您想要的解决方案**
能够输入 gpts 链接打开 gpts

**描述您考虑过的替代方案**
用主账号打开链接，然后就能在 recently used gpts 里面看到

**附加上下文**
在此处添加关于功能请求的任何其他上下文或截图。

---

请将占位符替换为您的具体详情，以创建一个全面的功能请求工单。

**Comment by wozulong** [comment]
你把gpts地址的前缀换成你的部署的前缀即可。
