### ISSUE TITLE
gpt-4-vision 和 dall-e-3 的 API 调用【功能】

### ISSUE THREAD

**Issue by shiyegao** [pandora-next/deploy#259]
**您的功能请求是否与问题有关？请描述。**
现在大佬的 api 支持 GPT3 和 GPT4，请问支持dall-e-3和gpt-4-vision吗？

**描述您想要的解决方案**
希望支持 api 调用dall-e-3和gpt-4-vision

**附加上下文**
![image](https://github.com/pandora-next/deploy/assets/45991529/450f29d0-7004-4e70-b92a-1bd1a9a6a00e)

**Comment by wozulong** [comment]
暂时并不支持gpt4-v，你可以使用/backend-api自行模拟。
