### ISSUE TITLE
【BUG】macOS 下 ：zsh: exec format error: ./PandoraNext

### ISSUE THREAD

**Issue by mr-dragon** [pandora-next/deploy#261]
**描述错误**

macOS 下 ：执行 `./PandoraNext`

```shell
zsh: exec format error: ./PandoraNext
```

**复现步骤**
按照以下步骤复现错误：
1. 下载 PandoraNext-v0.4.5-linux-arm64-12c1f01.tar.gz 或 PandoraNext-v0.4.5-linux-arm-12c1f01.tar.gz
2. 解压，修改config，设置lis
3. 执行 `./PandoraNext`

**桌面（请完成以下信息）：**
 - 操作系统：Apple M1
 - 版本：13.6.1，iTerm2 终端下执行

**Comment by kmnslocr083** [comment]
> **描述错误**
> 
> macOS 下 ：执行 `./PandoraNext`
> 
> ```shell
> zsh: exec format error: ./PandoraNext
> ```
> 
> **复现步骤** 按照以下步骤复现错误：
> 
>     1. 下载 PandoraNext-v0.4.5-linux-arm64-12c1f01.tar.gz 或 PandoraNext-v0.4.5-linux-arm-12c1f01.tar.gz
> 
>     2. 解压，修改config，设置lis
> 
>     3. 执行 `./PandoraNext`
> 
> 
> **桌面（请完成以下信息）：**
> 
>     * 操作系统：Apple M1
> 
>     * 版本：13.6.1，iTerm2 终端下执行

### BUG你妈呢BUG？不知道 macOS 是 darwin？还在那下 linux？谁告诉你支持 macOS 了？
### 还你妈设置lis，lic 就算了你 lis，几把都笑爆了。

**Comment by wozulong** [comment]
> > **描述错误**
> > macOS 下 ：执行 `./PandoraNext`
> > ```shell
> > zsh: exec format error: ./PandoraNext
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **复现步骤** 按照以下步骤复现错误：
> > ```
> > 1. 下载 PandoraNext-v0.4.5-linux-arm64-12c1f01.tar.gz 或 PandoraNext-v0.4.5-linux-arm-12c1f01.tar.gz
> > 
> > 2. 解压，修改config，设置lis
> > 
> > 3. 执行 `./PandoraNext`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **桌面（请完成以下信息）：**
> > ```
> > * 操作系统：Apple M1
> > 
> > * 版本：13.6.1，iTerm2 终端下执行
> > ```
> 
> ### BUG你妈呢BUG？不知道 macOS 是 darwin？还在那下 linux？谁告诉你支持 macOS 了？
> ### 还你妈设置lis，lic 就算了你 lis，几把都笑爆了。

哪位暴躁老哥？？？

**Comment by wozulong** [comment]
> **描述错误**
> 
> macOS 下 ：执行 `./PandoraNext`
> 
> ```shell
> zsh: exec format error: ./PandoraNext
> ```
> 
> **复现步骤** 按照以下步骤复现错误：
> 
> 1. 下载 PandoraNext-v0.4.5-linux-arm64-12c1f01.tar.gz 或 PandoraNext-v0.4.5-linux-arm-12c1f01.tar.gz
> 2. 解压，修改config，设置lis
> 3. 执行 `./PandoraNext`
> 
> **桌面（请完成以下信息）：**
> 
> * 操作系统：Apple M1
> * 版本：13.6.1，iTerm2 终端下执行

并没有放出mac版本，macOS下可以试试docker。
