### ISSUE TITLE
【求助】各位大神好！想问一下如何获取refresh token，感谢各位大神！

### ISSUE THREAD

**Issue by merrygreek** [pandora-next/deploy#263]
**真诚请教**

**Comment by su-fen** [comment]
https://fakeopen.org/Token/Refresh.html

**Comment by star2k** [comment]
> https://fakeopen.org/Token/Refresh.html

没法获取了么，若之前ios上若获取过，如何找回？

**Comment by su-fen** [comment]
> > https://fakeopen.org/Token/Refresh.html
> 
> 没法获取了么，若之前ios上若获取过，如何找回？

如果丢了那就无法找回，你之前获取过的refreshtoken仍然是可用的

**Comment by wozulong** [comment]
refresh已被推荐，使用session即可。
