### ISSUE TITLE
【求助】不暴露docker的端口，就无法使用

### ISSUE THREAD

**Issue by knight-666** [pandora-next/deploy#264]
**描述请求**
在不暴露docker映射的端口时，就无法使用，不知道这个是不是有心跳检测之类的东西

**问题陈述**
docker 部署 使用代理模式 防火墙打开 不暴露docker映射端口
报如下错误
Error #01: Post "https://client-api.pandoranext.com/backend-api/conversation": dial tcp: lookup client-api.pandoranext.com on 8.8.4.4:53: read udp 172.17.0.4:59616->8.8.4.4:53: read: no route to host

**已采取的步骤**
关闭防火墙或者暴露docker容器端口，就可以使用了

**预期结果**
代理模式下，不想使用web，是否能选择不暴露web的端口

**截图/日志**
Error #01: Post "https://client-api.pandoranext.com/backend-api/conversation": dial tcp: lookup client-api.pandoranext.com on 8.8.4.4:53: read udp 172.17.0.4:59616->8.8.4.4:53: read: no route to host

**环境信息（请完整填写以下信息）：**
- 操作系统：Linux  docker 

在顺便问一下，代理模式下，发送一条消息是算4条用量吗？
我看我这里，每发一条消息 用量增加4条

当前许可IP: 66 . *** . ** . ***，用量：28 / 6000条，重置：22h12m12s后

**Comment by QAbot-zh** [comment]
![image](https://github.com/pandora-next/deploy/assets/40236765/2908593f-7c1e-4d02-8360-e0260ff572a1)
