### ISSUE TITLE
【求助】backend-api 代理显示 Unauthorized - Access token is missing

### ISSUE THREAD

**Issue by xbmlz** [pandora-next/deploy#265]
**问题陈述**
使用Docker compose 自部署的pandora-next 在使用 backend-api 接口时，按照原来 https://ai.fakeopen.com/api/conversation 方式调用时一直返回 Unauthorized - Access token is missing

```json
{"message":"Unauthorized - Access token is missing"}
```

**环境信息（请完整填写以下信息）：**
- 操作系统：Linux
- 版本：Ubuntu 20.04
- 架构：amd64

**Comment by xbmlz** [comment]
还有一个小小的建议，可不可以辛苦大佬搞个Discord 的群，互相帮助一下

**Comment by yorunning** [comment]
> 还有一个小小的建议，可不可以辛苦大佬搞个Discord 的群，互相帮助一下

有tg群

**Comment by wozulong** [comment]
调用接口应该按照文档开启proxy模式，调用地址里应该有<proxy_api_prefix>的内容。
