### ISSUE TITLE
PandoraNext 搭建好了，怎么像原来Fakeopen API 原来一样使用？

### ISSUE THREAD

**Issue by long202258** [pandora-next/deploy#269]
PandoraNext 搭建好了，怎么像原来Fakeopen API 原来一样使用？ 小白求指导

**Comment by tyhunter** [comment]
文档写得很清楚了，先设置proxy_api_prefix，再去https://ai.fakeopen.com/token生成fk-xxx开头的api token
然后请求https://yourname/<proxy_api_prefix>/v1/chat/completions

**Comment by wozulong** [comment]
开启proxy模式，就跟之前一样用了。

**Comment by for3ever3** [comment]
> 文档写得很清楚了，先设置proxy_api_prefix，再去[https://ai.fakeopen.com/token生成fk-xxx开头的api](https://ai.fakeopen.com/token%E7%94%9F%E6%88%90fk-xxx%E5%BC%80%E5%A4%B4%E7%9A%84api) token 然后请求https://yourname/<proxy_api_prefix>/v1/chat/completions

如果是本地搭建可以用吗？

**Comment by for3ever3** [comment]
> 开启proxy模式，就跟之前一样用了。



> 文档写得很清楚了，先设置proxy_api_prefix，再去[https://ai.fakeopen.com/token生成fk-xxx开头的api](https://ai.fakeopen.com/token%E7%94%9F%E6%88%90fk-xxx%E5%BC%80%E5%A4%B4%E7%9A%84api) token 然后请求https://yourname/<proxy_api_prefix>/v1/chat/completions

我在本地搭建的时候，访问/<proxy_api_prefix>/v1/chat/completions出现了404
