### ISSUE TITLE
【求助】抱歉，不太懂GitHub沟通礼仪，忘记点星了，求助详情见下：

### ISSUE THREAD

**Issue by ixujue** [pandora-next/deploy#271]
描述请求
不懂这些技术，感觉放自己服务器上估计操作不好。

问题陈述
想要部署到Vercel这类平台，不知道是否可行？如果可行，要怎么操作？

如果这个是不能讨论的或是没有计划解决的，麻烦回复一下，谢谢。

**Comment by su-fen** [comment]
https://fakeopen.org/

**Comment by wozulong** [comment]
建议使用vps，更加稳定。vercel诸多限制，而且ip频繁变动，不稳定。
