### ISSUE TITLE
【求助】GPT回答问题过程中卡住，回答一半就不在输出了...

### ISSUE THREAD

**Issue by DomainPon** [pandora-next/deploy#274]
![Snipaste_2023-12-07_23-43-37](https://github.com/pandora-next/deploy/assets/30632531/72c67e01-cfee-4fe6-adf2-b156faf0ac4d)

**Comment by su-fen** [comment]
nginx是否配置好？另外官网其实也挺卡的

**Comment by wozulong** [comment]
gpt-4卡是常态。也不排除是网络问题，可以在新的演示站试试 chat.oaifree.com
