### ISSUE TITLE
吾皇，微臣一问，后续pandora会取消支持，只让用pandora-next吗

### ISSUE THREAD

**Issue by dao-zero** [pandora-next/deploy#28]

**Comment by yelc66** [comment]
说了不更新了

**Comment by wozulong** [comment]
pandora不更新了，但目前也不会关，保持现状。

**Comment by StudyingLover** [comment]
> pandora不更新了，但目前也不会关，保持现状。

pandora的代码现在还能下载吗

**Comment by zxyza** [comment]
> pandora不更新了，但目前也不会关，保持现状。
老大，现在关了对么，我用pandora提示It is recommended to upgrade to the latest PandoraNext: https://github.com/pandora-next/deploy
