### ISSUE TITLE
【功能】token用户名不支持特殊符号，我的账号是aa+bb@gmail.com，提示存在无效字符

### ISSUE THREAD

**Issue by qingyanbaby** [pandora-next/deploy#285]
**您的功能请求是否与问题有关？请描述。**
token用户名不支持特殊符号，我的账号是aa+bb@gmail.com，提示存在无效字符

**描述您想要的解决方案**
添加支持

**Comment by wozulong** [comment]
可能是邮箱判断方面存在问题，这个问题我看看。
