### ISSUE TITLE
【功能】我写了一个自动更新session和刷新pool的脚本

### ISSUE THREAD

**Issue by AuditAIH** [pandora-next/deploy#291]
**### 感谢吾皇提供了这么好的工具，使用前点亮star和follow作者**

感谢tokensTool的作者提供的指导
站着巨人的肩膀前进
警告 session为1:100刷新，其他的为1:1刷新

请认真读完代码再执行
执行前请确保安装了curl和jq
请确保tokens.json文件内的test-1
必有一个为session_token，将来刷新
如果启用了自定义证书 请在curl时增加-k忽略证书
如需配合其他工具 请求地址为构造的前缀 建议用pool

首先设置一个定时执行的任务，session2个月一次，pooltoken每天一次

`~ $ crontab -e
crontab: no changes made to crontab
~ $ crontab -l
30 6 15 * * /data/data/com.termux/files/home/root/PandoraNext/updatesession.sh >> /data/data/com.termux/files/home/root/PandoraNext/update.log 2>&1

45 6 * * * /data/data/com.termux/files/home/root/PandoraNext/updatesharetoken.sh >> /data/data/com.termux/files/home/root/PandoraNext/update.log 2>&1`

`#!/bin/bash

  # 进入脚本所在的目录
cd /root/PandoraNext/

  # 定义配置文件路径
CONFIG_FILE="config.json"
TOKEN_FILE="tokens.json"

  # 脚本开始执行的提示信息
echo "$(date +"%Y-%m-%d %H:%M:%S") - 脚本开始执行获取session"

  # 检查配置文件是否存在
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Config file not found"
    exit 1
fi

  # 从配置文件中读取必要的配置值
bind=$(jq -r '.bind' "$CONFIG_FILE")
proxy_api_prefix=$(jq -r '.proxy_api_prefix' "$CONFIG_FILE")
tls_enabled=$(jq -r '.tls.enabled' "$CONFIG_FILE")

  # 根据配置选择 HTTP 或 HTTPS 协议
protocol="http"
if [[ "$tls_enabled" == true ]]; then
    protocol="https"
fi

  # 处理特殊的 bind 值，如 localhost 地址
case $bind in
    0.0.0.0|127.0.0.1)
        bind="localhost"
        ;;
    *)
        ;;
esac

  # 构建 API 接口前缀
api_endpoint_prefix="$protocol://$bind/$proxy_api_prefix/api"

  # 定义登录接口的完整 URL
login_url="$api_endpoint_prefix/auth/login"

  # 请在这里填写您的用户名和密码
username="你的用户名"
password="你的密码"

  # 尝试登录和更新 token，最多重试 10 次
attempt=0
max_attempts=10
while [ $attempt -lt $max_attempts ]; do
    # 发送登录请求并获取响应
    response=$(curl -s --location "$login_url" \
    --header 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode "username=$username" \
    --data-urlencode "password=$password")

    # 从响应中提取 session_token
    new_session_token=$(echo "$response" | jq -r '.session_token')

    # 检查 session_token 是否有效
    if [[ "$new_session_token" != null && "$new_session_token" != "" ]]; then
        # 从 TOKEN_FILE 中读取旧的 session_token
        old_session_token=$(jq -r '.session_token.token' "$TOKEN_FILE")
        # 更新 TOKEN_FILE 中的 session_token
        jq --arg token "$new_session_token" '.session_token.token = $token' "$TOKEN_FILE" > temp.json && mv temp.json "$TOKEN_FILE"

        # 显示 session_token 更新成功的信息
        echo "$(date +"%Y-%m-%d %H:%M:%S") - 成功将Session Token: ${old_session_token:0:5}......${old_session_token:(-5)}更新为新的Session Token: ${new_session_token:0:5}......${new_session_token:(-5)}"
        
        # 从配置文件中获取 setup_password
        setup_password=$(jq -r '.setup_password' "$CONFIG_FILE")
        # 构建重新加载的 URL
        reload_url="$api_endpoint_prefix/setup/reload"

        # 使用新的 session_token 发送 POST 请求以重新加载程序
        curl -H "Authorization: Bearer $setup_password" -X POST "$reload_url"
        # 输出一个空行以保持格式整洁
        echo

        break
    else
        # 登录尝试失败的信息
        echo "Attempt $((attempt+1)) of $max_attempts failed, waiting 2000 seconds to retry"
    fi

    # 在再次尝试之前等待 2000 秒
    sleep 2000
    attempt=$((attempt+1))
done

# 在尝试次数达到上限后显示失败信息
if [ $attempt -eq $max_attempts ]; then
    echo "Failed to update token after $max_attempts attempts"
fi
`
### **下面是刷新pooltoken的 请确认sessiontoken已经通过上述步骤更新成功。也可以替换成自己JSON里面的其他值**

`#!/bin/bash

# 进入脚本所在的目录
cd /root/PandoraNext/

# 定义配置文件路径
CONFIG_FILE="config.json"
TOKEN_FILE="tokens.json"

# 检查配置文件是否存在
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Config file not found"
    exit 1
fi

# 读取 bind、proxy_api_prefix 和 tls.enabled 值
bind=$(jq -r '.bind' "$CONFIG_FILE")
proxy_api_prefix=$(jq -r '.proxy_api_prefix' "$CONFIG_FILE")
tls_enabled=$(jq -r '.tls.enabled' "$CONFIG_FILE")

# 检查是否有空值
if [ -z "$bind" ]; then
    echo "Bind is empty"
    exit 1
fi

if [ -z "$proxy_api_prefix" ]; then
    echo "Proxy API Prefix is empty"
    exit 1
fi

# 根据 tls.enabled 的值选择协议
protocol="http"
if [[ "$tls_enabled" == true ]]; then
    protocol="https"
fi

# 处理特殊的 bind 值
case $bind in
    0.0.0.0|127.0.0.1)
        bind="localhost"
        ;;
    *)
        ;;
esac

# 构建并输出 API 接口前缀
api_endpoint_prefix="$protocol://$bind/$proxy_api_prefix/api"
echo "API Endpoint Prefix: $api_endpoint_prefix"

# 检查 token 文件是否存在
if [ ! -f "$TOKEN_FILE" ]; then
    echo "Token file not found"
    exit 1
fi

# 读取 session_token
session_token=$(jq -r '.session_token.token' "$TOKEN_FILE")

# 如果 session_token 不存在，则结束脚本
if [ -z "$session_token" ]; then
    echo "Session Token not found"
    exit 1
fi

echo "Session Token: ${session_token:0:5}......${session_token:(-5)}"

# 函数：使用 Session Token 获取 Access Token
get_access_token_with_session_token() {
    echo "Getting access token using session token..."
    login_response=$(curl --silent --location "$api_endpoint_prefix/auth/session" \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "session_token=$session_token")

    if [ -z "$login_response" ]; then
        echo "Failed to get access token: No response"
        return 1
    fi

    access_token=$(echo $login_response | jq -r '.access_token')

    if [ -z "$access_token" ]; then
        echo "Failed to get access token."
        return 1
    fi

    echo "Access Token: ${access_token:0:5}......${access_token:(-5)}"
}

# 函数：注册或更新 Share Token
register_share_token() {
    echo "Registering or updating Share Token..."
    share_token_response=$(curl --silent --location "$api_endpoint_prefix/token/register" \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'unique_name=fakeopen' \
        --data-urlencode "access_token=$access_token" \
        --data-urlencode 'site_limit=' \
        --data-urlencode 'expires_in=0' \
        --data-urlencode 'show_conversations=true' \
        --data-urlencode 'show_userinfo=true')

    if [ -z "$share_token_response" ]; then
        echo "Failed to register share token: No response"
        return 1
    fi

    share_token=$(echo $share_token_response | jq -r '.token_key')

    if [ -z "$share_token" ]; then
        echo "Failed to extract share token."
        return 1
    fi

    echo "Share Token: $share_token"
}

# 函数：注册或更新 Pool Token
update_pool_token() {
    echo "Registering or updating Pool Token..."
    pool_token_response=$(curl --silent --location "$api_endpoint_prefix/pool/update" \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "share_tokens=$share_token" \
        --data-urlencode 'pool_token=您的pool_token')

    if [ -z "$pool_token_response" ]; then
        echo "Failed to update pool token: No response"
        return 1
    fi

    pool_token=$(echo $pool_token_response | jq -r '.pool_token')

    if [ -z "$pool_token" ]; then
        echo "Failed to extract pool token."
        return 1
    fi

    echo "Successfully updated Pool Token: $pool_token"
}

# 执行函数
get_access_token_with_session_token
if [ $? -eq 0 ]; then
    register_share_token
    if [ $? -eq 0 ]; then
        update_pool_token
    fi
fi

或者您没有pooltoken要注册一个
请把注册或更新pooltoken的函数替换掉
#!/bin/bash

# [之前的代码部分]

# 函数：从文件中读取 Pool Token 或返回空
read_pool_token_from_file() {
    if [ -f "pooltoken" ]; then
        echo "$(cat pooltoken)"
    else
        echo ""
    fi
}

# 函数：将 Pool Token 写入文件
write_pool_token_to_file() {
    echo "$1" > pooltoken
}

# 函数：注册或更新 Pool Token
update_pool_token() {
    echo "Registering or updating Pool Token..."

    # 尝试从文件中读取 Pool Token
    existing_pool_token=$(read_pool_token_from_file)

    pool_token_response=$(curl --silent --location "$api_endpoint_prefix/pool/update" \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "share_tokens=$share_token" \
        --data-urlencode "pool_token=$existing_pool_token")

    if [ -z "$pool_token_response" ]; then
        echo "Failed to update pool token: No response"
        return 1
    fi

    pool_token=$(echo $pool_token_response | jq -r '.pool_token')

    if [ -z "$pool_token" ]; then
        echo "Failed to extract pool token."
        return 1
    fi

    # 将新的 Pool Token 写入文件
    write_pool_token_to_file "$pool_token"

    echo "Successfully updated Pool Token: $pool_token  =  $share_token"
}

# [之后的代码部分]   `

传送门自动更新tokens。
一键部署tokensTool：https://github.com/Yanyutin753/PandoraNext-TokensTool

**Comment by 668168** [comment]
good. 谢谢饭团

**Comment by for3ever3** [comment]
而你我的朋友，你才是真正的英雄
