### ISSUE TITLE
【求助】为什么IP许可里显示的“无”，我的账号好像用不了

### ISSUE THREAD

**Issue by lapluie0** [pandora-next/deploy#294]
<img width="1280" alt="微信图片_20231210121400" src="https://github.com/pandora-next/deploy/assets/39639958/04f78692-8d15-4fe2-aa8d-415360cb3f4c">

**Comment by lapluie0** [comment]
感谢

**Comment by wozulong** [comment]
填写license_id启动服务才会显示ip
