### ISSUE TITLE
【求助】一直提示pandora-next2023/12/10 10:16:55 Failed to fetch license: Too Many Requests(429)是什么问题？

### ISSUE THREAD

**Issue by shentong0722** [pandora-next/deploy#297]
一直提示pandora-next2023/12/10 10:16:55 Failed to fetch license: Too Many Requests(429)是什么问题？

**Comment by BBrother-GFC** [comment]
请你仔细看看license的文档，只能3分钟获取一次

**Comment by shentong0722** [comment]
> 请你仔细看看license的文档，只能3分钟获取一次

可是我是获取之后填进config里之后运行时报错，而且是第一次运行，循环报这个

**Comment by wozulong** [comment]
自动获取如果不行，可以试试页面上介绍的手动获取。
