### ISSUE TITLE
【功能】希望增加自动刷新 Session Token 或 Refresh Token 功能

### ISSUE THREAD

**Issue by BBrother-GFC** [pandora-next/deploy#298]
始皇大大之后是否会加PandoraNext自带的用账号密码自动刷新 Session Token 或 Refresh Token 功能呢？
担心额度的话能否在token.json里面设置上某个账号是否刷新的开关（开shared的情况下）

**Comment by stazeng** [comment]
扶墙登openai找到Session Token才1天，第二天提示到期了？什么情况？
