### ISSUE TITLE
【BUG】使用proxy API访问出现401

### ISSUE THREAD

**Issue by wj2008** [pandora-next/deploy#299]
**描述错误**
使用api访问出现401， 
http://v6.51****.xyz:2025/****8888/v1/chat/completions

**复现步骤**
按照以下步骤复现错误：
1. 按文档部署后使用proxy api请求 Bearer pk-this-is-a-real-free-pool-token-for-everyone
2. 响应不是200而是401错误，看docker 日志提示是 Error #01: Unauthorized - Access token is missing

**预期行为**
正常使用api请求

**截图**
<img width="962" alt="image" src="https://github.com/pandora-next/deploy/assets/55370685/f203b292-e9d4-4d94-8530-8fb4fc522e8d">

**服务器（请完成以下信息）：**
=
=  OS:		Linux
=  Arch:	amd64
=  Version:	v0.5.0
=  BuildId:	17a7c65
=  Mode:	web, proxy
=  Bind:	http://0.0.0.0:8181/
---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by wj2008** [comment]
<img width="670" alt="image" src="https://github.com/pandora-next/deploy/assets/55370685/c7c64a23-0cd7-4762-9051-058a426ed78e">

**Comment by xiaosaaaa** [comment]
因为大pk里面的号有些被封掉了，你轮换到失效的就会这样。

**Comment by su-fen** [comment]
昨晚11点多的时候重新刷了一遍
