### ISSUE TITLE
我们自己有 转生 通道

### ISSUE THREAD

**Issue by kaozb** [pandora-next/deploy#30]
## 2000个对话完全不够用啊

主要是该死的 cloudfare;   官网能用 css js不行，刚好next 解决了这个问题

![image](https://github.com/pandora-next/deploy/assets/85659592/4b2f02f0-0df8-4177-89b5-329ac210102a)

**Comment by QAbot-zh** [comment]
1天2000条还不够啊，这是几个人在用😂

**Comment by Qinks6** [comment]
license.jwt怎么弄？

**Comment by DearDavies** [comment]
这个应该是按照账号的年份给的条数吧？我的是5k条每天
