### ISSUE TITLE
【求助】账号密码登录会自动重定向到开始界面

### ISSUE THREAD

**Issue by zzttyy413841467** [pandora-next/deploy#303]
**描述请求**
清晰、简洁地描述您需要帮助的内容。

**问题陈述**
账号密码登录会自动重定向到开始界面，没有任何反应

**已采取的步骤**
描述您为解决问题已采取的步骤或您所做的研究。

**预期结果**
描述您期望得到的帮助或解决方案。

**截图/日志**
[GIN] 2023/12/11 - 06:28:40 | 302 |  212.289068ms | 2001: | POST     "/auth/login?state=E8cR0MyX5"
[GIN] 2023/12/11 - 06:28:40 | 200 |     1.86829ms | 2001: | GET      "/auth/password?state=MgTYBdZH"
[GIN] 2023/12/11 - 06:28:40 | 200 |    21.28439ms | 2001: | GET      "/v2/XXXXX/api.js"
[GIN] 2023/12/11 - 06:28:41 | 200 |  490.458623ms | 2001: | GET      "/v2/2.3.1/enforcement.db38df7eed55a4641d0eec2d11e1ff6a.html"
[GIN] 2023/12/11 - 06:28:42 | 200 |   22.381845ms | 2001: | GET      "/v2/2.3.1/enforcement.db38df7eed55a4641d0eec2d11e1ff6a.js"
[GIN] 2023/12/11 - 06:28:42 | 200 |     161.232µs | 2001: | GET      "/manifest.json"
[GIN] 2023/12/11 - 06:28:42 | 200 |  333.508087ms | 2001: | GET      "/v2/XXXXX/settings"
[GIN] 2023/12/11 - 06:28:44 | 200 |     248.923µs | 2001: | GET      "/service-worker.js"
[GIN] 2023/12/11 - 06:28:59 | 200 |  1.327243316s | 2001: | POST     "/fc/gt2/public_key/XXXXX"
[GIN] 2023/12/11 - 06:28:59 | 200 |   43.560195ms | 2001: | GET      "/v2/2.3.1/enforcement.db38df7eed55a4641d0eec2d11e1ff6a.html"
[GIN] 2023/12/11 - 06:29:00 | 200 |   26.446368ms | 2001: | GET      "/v2/2.3.1/enforcement.db38df7eed55a4641d0eec2d11e1ff6a.js"
[GIN] 2023/12/11 - 06:29:00 | 200 |  270.488297ms | 2001: | GET      "/v2/XXXXX/settings"
[GIN] 2023/12/11 - 06:29:03 | 302 |  3.162458483s | 2001: | POST     "/auth/password?state=MgTYB"

[GIN] 2023/12/11 - 06:29:03 | 302 |     796.136µs | 2001: | GET      "/"
[GIN] 2023/12/11 - 06:29:03 | 302 |     605.692µs | 2001: | GET      "/auth/login?next=%2F"
[GIN] 2023/12/11 - 06:29:03 | 200 |    2.050742ms | 2001: | GET      "/auth/login?state=39PyZRX"
[GIN] 2023/12/11 - 06:29:04 | 200 |     148.395µs | 2001: | GET      "/manifest.json"
[GIN] 2023/12/11 - 06:29:05 | 200 |     297.783µs | 2001: | GET      "/service-worker.js"

**环境信息（请完整填写以下信息）：**
- 操作系统：Linux
- 版本：CentOS
- 架构：amd64

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by JS-an** [comment]
确实，对于内部项目跳转到本项目，如果能跳过登录页面，直接进入使用，体验会好很多

**Comment by wozulong** [comment]
参照readme上所提到的同步时间操作试试。

**Comment by zhetc** [comment]
我使用docker部署的，也是无限跳转到首页，时区修改为CST也无限跳转，后来测试发现，我习惯性的使用--net=host网络，改回--net=bridge -p 8181:8181，就可以正常登录了。
