### ISSUE TITLE
【求助】使用docker-compose 部署在本地，服务起不来，查看log "Ping remote server failed"

### ISSUE THREAD

**Issue by LeonMac** [pandora-next/deploy#307]
**描述请求**
使用docker-compose 部署在本地，服务起不来，查看docker log "Ping remote server failed, detail: Access denied, Ip: x.x.x.x, Reason: invalid"

**问题陈述**
上周服务都可以起来，不知道为什么这周不行了。

**已采取的步骤**
重新docker pull了最新的镜像，也重新git pull了最新的 deploy repo。

**预期结果**
能够正常起服务。

**截图/日志**
···
2023/12/12 03:07:59 ============================================================
2023/12/12 03:07:59 Reading local tokens from /data/tokens.json
2023/12/12 03:07:59 Loaded 1 tokens
2023/12/12 03:07:59 Loaded 2 shared tokens
2023/12/12 03:07:59 ============================================================
2023/12/12 03:07:59 "proxy_api_prefix" < 8 chars or too weak, proxy mode off!
2023/12/12 03:07:59 ============================================================
2023/12/12 03:08:00 Ping remote server failed, detail: Access denied, Ip: x.x.x.x, Reason: invalid
···

**环境信息（请完整填写以下信息）：**
- 操作系统：[Linux]
- 版本：[Ubuntu 20.04]
- 架构：[例如 x86_64]

**正在使用的工具/框架**
无其它

**相关代码片段**
无

**附加背景**
有时会使用sock5的自建代理，有时不用。但是都无法建立服务。
---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by wozulong** [comment]
是不是更换过license_id？删除license.jwt再试试看看。

**Comment by dalisanxianbao** [comment]
我也出现这样的问题，求解

**Comment by null119** [comment]
同样，pull了最新镜像就跑不起来了

**Comment by wozulong** [comment]
如果你license id没有泄露，不要随意更换。如果更换了license id，你需要使用新的license id，同时需要删除老的license.jwt后再启动。
