### ISSUE TITLE
后端日志突然发现一个错误 ，使用chat2api【BUG】

### ISSUE THREAD

**Issue by RootSir** [pandora-next/deploy#309]
**描述错误**
清晰且简洁地描述错误是什么。

**复现步骤**
按照以下步骤复现错误：
1. 前往 '...'
2. 点击 '....'
3. 向下滚动至 '....'
4. 观察到错误

**预期行为**
清晰且简洁地描述您预期会发生什么。

**截图**
如果适用，添加截图以帮助解释您的问题。

**服务器（请完成以下信息）：**
 - 操作系统：[例如 iOS]
 - 版本：[例如 22]
 - 架构：[例如 x86_64、arm64]

**桌面（请完成以下信息）：**
 - 操作系统：[例如 iOS]
 - 浏览器：[例如 chrome, safari]
 - 版本：[例如 22]

**智能手机（请完成以下信息）：**
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如 stock browser, safari]
 - 版本：[例如 22]

**附加上下文**
在此处添加关于问题的任何其他上下文。

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。
2023/12/12 13:50:34 [Recovery] 2023/12/12 - 13:50:34 panic recovered:
runtime error: index out of range [0] with length 0
runtime/panic.go:114 (0x4325bb)
??:12 (0x11934c4)
??:1 (0x10a6e48)
??:1 (0x11917c4)
??:1 (0x10a1f0a)
??:1 (0x120dc44)
??:1 (0x10afe59)
??:1 (0x10afe47)
??:1 (0x10aeebd)
??:1 (0x10aee74)
??:1 (0x10ad60f)
??:1 (0x10ad29f)
??:1 (0x10acddc)
??:1 (0x8e6e0d)
??:1 (0x8e2353)
runtime/u9m7qy_hj.s:1650 (0x45ec80)

使用版本0.4.6

**Comment by for3ever3** [comment]
要不你更新一下版本吧

**Comment by lcfctkg** [comment]
这个系统版本可真感人
