### ISSUE TITLE
tz问题更新image已解决。缓存问题求问

### ISSUE THREAD

**Issue by lisankai93** [pandora-next/deploy#31]
请大佬帮忙解决，谢谢！

**Comment by 823302271** [comment]
我开了梯子出现其他问题

**Comment by lisankai93** [comment]
更新最新docker好了。

另外有个问题就是没有缓存，每次隔一会重新进入网站都要重新登录。nginx已经开了cache了

**Comment by wozulong** [comment]
> 更新最新docker好了。
> 
> 另外有个问题就是没有缓存，每次隔一会重新进入网站都要重新登录。nginx已经开了cache了

应该是你/tmp目录里的东西被自动清除了。
