### ISSUE TITLE
演示地址输入token后报错【求助】

### ISSUE THREAD

**Issue by AShanWang** [pandora-next/deploy#313]
登录项目的演示地址：https://chat1.zhile.io/auth/login?state=D4khXLi0ei_vcD5sUGKnauQ--sOPyI4FlpaoL4JpcM3Q6x6JnZT5Sq4o8K8kviZ0aHojzzWJ3UfZpnZNqPrZWMEId7G90h3XRadeTtQN3O-DD8yjPN9odxfx
输入token后报错，如下图：
![image](https://github.com/pandora-next/deploy/assets/129077870/32dec821-553c-4939-a51c-1d6f1cc439e9)

---
自己也按照教程尝试在vps上搭建了一个，
但是输入token后和演示地址的结果一样，
报错
please reload page。
重新刷新，即使在无痕模式下也是相同的结果。

p.s.:    github注册时长超过半年不到一年，所有只有100+100的额度，

---
奇怪的是，
使用[Go shared chat](https://chat1.zhile.io/shared.html)里的共享账号，就能正常使用。
不知道问题出在哪里了。

## 备注
- 个人非常确认自个的chatgpt账号是正常的，可以在openai官网正常登录使用，
- token也是获取的最新的。

**Comment by wozulong** [comment]
OpenAI再次拉高风控。目前已解决。

**Comment by AShanWang** [comment]
感谢大佬的回复，
但是我刚才试了一下，
还是相同的结果呐。

这两个演示地址我都试了，但结果都一样。
1. https://chat.zhile.io/auth/login?state=G8EOH3QBoYv0ITf_UlwkdvO1s_HJ8yjec67H0e9WZMH4csLb1CRS3qBbOatk6KHMH-Ls5BORdan_
2. https://chat1.zhile.io/auth/login?state=98GgmTbjHktnbzL2k5eQIg754co-tqRPW1VzBPLdfitJI0pazlNb97Sz1WhY6IpjlTz27qJ1PGLLXX8dF5w9Zo7WpFl2-FPR_QqqPS80X1y-8nT7ErNZzV1ZxolRCMU

- 如图
![image](https://github.com/pandora-next/deploy/assets/129077870/58553aea-a14e-4021-81bb-15d1d53aafae)

---
我的token肯定是没有问题的，
因为相同的token在我的另一个自己搭建的项目中可以登录。
地址如下：
- https://ashancbt.link/

好奇怪啊。

**Comment by AShanWang** [comment]
今天换了个浏览器试了下，
正常了。

brave浏览器        √
edge & chrome   x
