### ISSUE TITLE
【求助】项目彩蛋有人知道吗？

### ISSUE THREAD

**Issue by terrywangt** [pandora-next/deploy#315]
**描述请求**
这个登录后页面https://dash.pandoranext.com/
![image](https://github.com/pandora-next/deploy/assets/24427783/d792e485-bea7-40f0-8148-4f5ed3f8ed93)
小字内容：4. 有两个彩蛋，每个可额外获得500条额度。
**问题陈述**
兄弟们，这里有行小字，说有两个彩蛋，彩蛋是什么，有人知道吗？
我好像命中了一个彩蛋但不知道命中的是什么。
![image](https://github.com/pandora-next/deploy/assets/24427783/596bce04-2ca4-49c7-b945-f8d8eb831ce6)

有没有兄弟知道彩蛋具体是什么？

**Comment by fu-jw** [comment]
follow[作者啊](https://github.com/wozulong)，群里说八百遍了🤦‍♂️

**Comment by terrywangt** [comment]
> follow[作者啊](https://github.com/wozulong)，群里说八百遍了🤦‍♂️

👌。加的什么群，能拉我一下吗

**Comment by fu-jw** [comment]
仔细阅读readme

**Comment by terrywangt** [comment]
> 仔细阅读readme

tg群呀，好吧。谢谢兄弟

**Comment by BBrother-GFC** [comment]
我是那种啥都没干就已经+1000的了（
虽然我也不知道两个彩蛋分别是什么
![image](https://github.com/pandora-next/deploy/assets/51117375/849771f7-a3a0-4b2a-a9ef-76ff469d6e1d)

**Comment by BBrother-GFC** [comment]
我是那种啥都没弄就已经+1000的那类人了（
![image](https://github.com/pandora-next/deploy/assets/51117375/10fc129e-9af8-42d8-b399-1674dd450ced)

**Comment by fu-jw** [comment]
> 我是那种啥都没弄就已经+1000的那类人了（ ![image](https://private-user-images.githubusercontent.com/51117375/290098863-10fc129e-9af8-42d8-b399-1674dd450ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTAyMjIsIm5iZiI6MTcwMjQ0OTkyMiwicGF0aCI6Ii81MTExNzM3NS8yOTAwOTg4NjMtMTBmYzEyOWUtOWFmOC00MmQ4LWIzOTktMTY3NGRkNDUwY2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2NDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyN2YwZGQ3ZGE2NWQ5NWZjMzE0M2E2NTY2ZGY2NWRhNzE3ZWRkZWQyMzdkZjVmNjE5YTBiZjZiOWI3MzllNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-S5QaJsYhgUuCG-2z9-Gg9-KyUM-1BMbvH2L4Jk4cQ)

star+follow两个彩蛋你都触发了，所以加1000

**Comment by liulisanwan** [comment]
没看到tg群在哪里大佬能截个图吗
