### ISSUE TITLE
分享一个批量自动更新tokens.json的bash脚本，支持docker自动重启

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [pandora-next/deploy#32]
## 使用说明
- 记得配置 容器名称，最定的accesstoken，配置json配置文件路径（就你docker加载的/data/tokens.json）
- 账号直接早tokens.json中写好，密码配置好，token放空，脚本会自动更新token
- 命令 ```sh script.sh```  也可以增加 -y 指令，自动重启容器

## 脚本如下：

```bash
#!/bin/bash
# 从环境变量获取 access_token
# ACCESS_TOKEN=$GPT_access_token
# 或者直接指定
ACCESS_TOKEN=""
 
# 容器名称
CONTAINER_NAME="PandoraNext"
# 你的域名
SITE_LIMIT=""
# JSON 配置文件路径
CONFIG_FILE="/root/tokens.json" 



# 检查是否传递了 -y 参数
AUTO_RESTART=false
if [ "$1" = "-y" ]; then
    AUTO_RESTART=true
fi


# 使用 jq 命令读取 JSON 文件中的所有账号名称
ACCOUNT_NAMES=$(jq -r 'keys[]' $CONFIG_FILE)
# 计算总账号数
TOTAL_ACCOUNT_COUNT=$(echo "$ACCOUNT_NAMES" | wc -l)
UPDATED_COUNT=0
# 遍历账号名称
for ACCOUNT_NAME in $ACCOUNT_NAMES
do
    # 使用 curl 命令获取新的 token_key
    RESPONSE=$(curl -s 'https://ai.fakeopen.com/token/register' \
        -H 'authority: ai.fakeopen.com' \
        -H 'accept: */*' \
        -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
        -H 'x-requested-with: XMLHttpRequest' \
        -H 'user-agent: Mozilla/5.0' \
        -H 'origin: https://ai.fakeopen.com' \
        -H 'sec-fetch-site: same-origin' \
        -H 'sec-fetch-mode: cors' \
        -H 'sec-fetch-dest: empty' \
        -H 'referer: https://ai.fakeopen.com/token' \
        -H 'accept-language: zh-CN,zh;q=0.9' \
        -d "unique_name=${ACCOUNT_NAME}&access_token=${ACCESS_TOKEN}&expires_in=0&site_limit=${SITE_LIMIT}")

    # 提取新的 token_key
    NEW_TOKEN=$(echo $RESPONSE | jq -r '.token_key')

    # 打印账号名称和新的 token_key
    echo "Account Name: $ACCOUNT_NAME"
    echo "New Token: $NEW_TOKEN"

    # 更新 JSON 文件
    jq --arg tk "$NEW_TOKEN" --arg un "$ACCOUNT_NAME" '.[$un].token = $tk' $CONFIG_FILE > temp.json && mv temp.json $CONFIG_FILE
     # 更新计数器并打印进度
    ((UPDATED_COUNT++))
    echo "更新进度: ${UPDATED_COUNT}/${TOTAL_ACCOUNT_COUNT}"
done

echo "全部TOKEN更新完成，总计更新: $UPDATED_COUNT 条账号信息"

 
# 全部更新完成后的处理
if $AUTO_RESTART; then
    echo "正在重启 Docker 容器 $CONTAINER_NAME..."
    docker restart $CONTAINER_NAME
    echo "Docker 容器： $CONTAINER_NAME 已自动重启。"
else
    echo "所有账号已更新完成。是否现在重启 Docker 容器 $CONTAINER_NAME？(y/n)"
    read -r RESTART_ANSWER

    if [ "$RESTART_ANSWER" = "y" ] || [ "$RESTART_ANSWER" = "Y" ]; then
        echo "正在重启 Docker 容器： $CONTAINER_NAME..."
        docker restart $CONTAINER_NAME
        echo "Docker 容器 ：$CONTAINER_NAME 已重启。"
    else
        echo "未执行 Docker 容器重启操作。"
    fi
fi
```

**Comment by Yanyutin753** [comment]
为啥我用服务器去访问https://ai.fakeopen.com/token/register会被403，本地就不会，好奇怪啊，搞得我都不敢用这个拿token，都是用python写了一个接口拿，该咋解决，求教大佬

**Comment by epre5** [comment]
来个Python的
`# -*- coding: utf-8 -*-
import requests
import json
import subprocess
import time
# 不需要推送消息可以删掉相关代码
def send_notification(message):
    # 构造URL
    url = '<推送接口>'.format(message)
    # 发送GET请求
    try:
        requests.get(url)
    except Exception as e:
        print("发送通知时发生错误: {}".format(e))

try:
    # 读取accounts.txt文件(每行填邮箱和密码，用空格隔开，tokens.json里的每个字段填邮箱)
    with open('/opt/pandora_token_update/accounts.txt', 'r') as file:
        accounts = file.readlines()

    # 读取tokens.json文件
    with open('/data/data/tokens.json', 'r') as file:
        tokens_data = json.load(file)

    # 遍历每个账户
    for account in accounts:
        username, password = account.strip().split()
        response = requests.post("https://ai-20230912.fakeopen.com/auth/login", data={"username": username, "password": password})
        
        # 检查响应中是否有access_token
        if 'access_token' in response.json():
            access_token = response.json()['access_token']
            
            # 更新tokens.json中的token值
            if username in tokens_data:
                tokens_data[username]['token'] = access_token

        # 每个账户处理后延迟1秒
        time.sleep(1)

    # 将更新后的数据写回tokens.json文件
    with open('/data/data/tokens.json', 'w') as file:
        json.dump(tokens_data, file, indent=4)

    # 重启Docker容器
    subprocess.call(['docker', 'restart', 'PandoraNext'])

    # 发送更新成功的通知
    send_notification("PandoraNext: Access_Token更新成功")

except Exception as e:
    # 发送异常通知
    send_notification("更新失败，异常信息：{}".format(e))
`
然后执行crontab -e去加一条
0 9 */5 * * /usr/bin/python /opt/pandora_token_update/updateAccessToken.py
每隔5天更新一次token

**Comment by renhai-lab** [comment]
请问，如果第三方（谷歌）登录的是不是没办法用这种自动获取方式？

**Comment by jxtomxu** [comment]
> 请问，如果第三方（谷歌）登录的是不是没办法用这种自动获取方式？

同问

**Comment by wozulong** [comment]
好东西。

**Comment by wozulong** [comment]
> 请问，如果第三方（谷歌）登录的是不是没办法用这种自动获取方式？

第三方账号登录后取session-token的cookie，可以用来刷新access token，已知有效期至少3个月。

**Comment by fuchao2687** [comment]
你好，请问账号密码写入tokens.json的格式是什么？
