### ISSUE TITLE
【BUG】手机端访问演示站点好像复制的按钮和copy都无效，电脑端正常

### ISSUE THREAD

**Issue by will15980** [pandora-next/deploy#320]
**描述错误**
手机端访问演示站点https://chat.oaifree.com/好像复制的按钮和copy都无效，电脑端正常

**复现步骤**
按照以下步骤复现错误：
复制或者点copy code，剪贴板都无内容

**截图**

![546546511117](https://github.com/pandora-next/deploy/assets/16914827/b8e501e9-7479-4067-b3cf-2aa00c113a5c)

---

**Comment by wozulong** [comment]
我测试手机端复制正常，剪贴板有内容。
