### ISSUE TITLE
docker 启动后一直报一个错误.

### ISSUE THREAD

**Issue by kelvinlee** [pandora-next/deploy#33]
```
$ docker run -d --restart always --name PandoraNext --net=bridge -p 8181:8181 \
             -e PANDORA_NEXT_LICENSE="<JWT Token>" pengzhile/pandora-next
```
出这个错误
```
Unable to verify the server's license: json: cannot unmarshal array into Go struct field License.aud of type string
```

有大神能帮忙看看么?

**Comment by zhly000** [comment]
同问

**Comment by Geolem** [comment]
这个<JWT Token>要替换为你实际获取的token值吧

**Comment by kelvinlee** [comment]
> 这个要替换为你实际获取的token值吧

已经换了 ....

**Comment by kelvinlee** [comment]
> 同问

先用 https://dash.pandoranext.com/ 获取一个 JWT token , 然后再用自己的 chat token .

**Comment by ChenEeeee** [comment]
这个jwt token要替代那个token吗

**Comment by peter-zx** [comment]
docker run -d --restart always --name PandoraNext -p 8181:8181 \
           -e PANDORA_NEXT_LICENSE="<JWT Token>" pengzhile/pandora-next
我正确替换了token
然后run

结果就是 镜像在不断的重启。端口也设置好了
 STATUS  
 Restarting
