### ISSUE TITLE
官网炸了

### ISSUE THREAD

**Issue by wozulong** [pandora-next/deploy#331]
<img width="967" alt="image" src="https://github.com/pandora-next/deploy/assets/8010600/9032744a-98e9-401d-b4ef-7b4f54a43ec7">

**Comment by wozulong** [comment]
<img width="930" alt="image" src="https://github.com/pandora-next/deploy/assets/8010600/b4a018a5-9401-4e75-829d-e8ca27a48ebf">

解决了。

**Comment by Aok211** [comment]
兄弟，我想自己搭一个长期稳定的镜像站，怎么联系你！

**Comment by Aok211** [comment]
> 兄弟，我想自己搭一个长期稳定的镜像站，怎么联系你！

自己工作室用，希望能长期稳定更新，有偿，V：antisds，希望能联系我。
