### ISSUE TITLE
授权的次数，在没有使用的情况下会莫名其妙的被消耗掉

### ISSUE THREAD

**Issue by s181462537** [pandora-next/deploy#333]
在我没有去使用看情况下，次数会被异常消耗掉，项目已设了全站的密码，不存在被他人使用看情况，不知道是怎么回事

**Comment by wozulong** [comment]
请检查：

1. `setup_password` 弱密码
2. `proxy_api_prefix` 弱前缀
3. 是否使用TokensTool工具

**Comment by wozulong** [comment]
在以上问题得到修复之后，请在dash.pandoranext.com中更换license id，删除license.jwt，config.json中替换新license id后启动。
