### ISSUE TITLE
Nginx证书不存在

### ISSUE THREAD

**Issue by yantaosun** [pandora-next/deploy#338]
**描述请求**
请教，在config.json中设置开启tls设置的证书路径需要挂载到容器内部吗，现在是宿主机的路径，总是提示不存在

**问题陈述**
阐述您面临的问题或您寻求帮助的原因。

**已采取的步骤**
描述您为解决问题已采取的步骤或您所做的研究。

**预期结果**
描述您期望得到的帮助或解决方案。

**截图/日志**
![image](https://github.com/pandora-next/deploy/assets/49381740/35d6bbdf-79b6-4f79-bcfd-7005a285ec35)
![image](https://github.com/pandora-next/deploy/assets/49381740/13827d1a-3b23-4a92-8a7b-4b0d0bdcc5de)

**环境信息（请完整填写以下信息）：**
- 操作系统：[例如 Windows、macOS、Linux]
- 版本：[例如 10、Catalina、Ubuntu 20.04]
- 架构：[例如 x86_64、arm64]

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by wozulong** [comment]
这个一定是要的
