### ISSUE TITLE
【功能】使用环境变量配置PandoraNext

### ISSUE THREAD

**Issue by D3-3109** [pandora-next/deploy#339]
**您的功能请求是否与问题有关？请描述。**
希望可以支持通过使用环境变量的方式来配置，使用Railway和Zeabur这些Serverless平台没有办法设置config.json，无法启动

**描述您想要的解决方案**
希望可以支持通过使用环境变量的方式来配置

**描述您考虑过的替代方案**
在Web界面Setup，然后填写License_id?

**附加上下文**
None

---

请将占位符替换为您的具体详情，以创建一个全面的功能请求工单。

**Comment by wozulong** [comment]
这些平台ip是否是变动的？

**Comment by D3-3109** [comment]
> 这些平台ip是否是变动的？

我现在使用的Zeabur，AWS Hong Kong的IP分配给我的都是52.223.32.133 35.71.144.225[cname.zeabur-dns.com]
