### ISSUE TITLE
【BUG】Failed to fetch license: Too Many Requests(429)

### ISSUE THREAD

**Issue by ghdefe** [pandora-next/deploy#343]
**描述错误**
启动报错：Failed to fetch license: Too Many Requests(429)

**复现步骤**
按照以下步骤复现错误：
1. 设置license id
2. 启动pandora-next
3. 报错

**预期行为**
启动并报告访问地址

**截图**
![image](https://github.com/pandora-next/deploy/assets/33114370/3ffc1c5b-d214-4ad3-96ca-a5e65512cae9)

**桌面（请完成以下信息）：**
 - 操作系统：Windows
 - 版本：10
 - 架构：x86

**附加上下文**
是注册码服务器down了吗？还是我的账号被封禁了

**Comment by D3-3109** [comment]
API设置了每次fetch license请求间隔为2分钟的限制，具体看dash.pandoranext.com
