### ISSUE TITLE
【求助】是否可以直接在share用户页面不显示隔离会话？

### ISSUE THREAD

**Issue by ICLiuLi** [pandora-next/deploy#347]
**描述请求**
希望在share用户的会话页面，可以直接不显示隔离会话

**问题陈述**
多个用户使用同一个key进行自己的会话时，会有大量的*号隔离会话

**预期结果**
是否可以增加一个配置直接不显示隔离会话

**截图/日志**
![image](https://github.com/pandora-next/deploy/assets/28101604/9fc1cb87-eec3-453e-829c-8885b235613c)

**Comment by Unreal-Null** [comment]
确实，比较影响美观

**Comment by Luolin0826** [comment]
确实  比如“isolated_conv_title”置空的时候，可以不显示其他人的会话就好了

**Comment by daomengRen** [comment]
+1

**Comment by ICLiuLi** [comment]
或者我觉得，仅限于share页面的时候，可以配置超过多少天的会话不展示，这样也可以

**Comment by QAbot-zh** [comment]
作者解释过：https://github.com/pandora-next/deploy/issues/167#issuecomment-1827496763

**Comment by wozulong** [comment]
[https://docs.pandoranext.com/en-US/configuration/config/#isolated_conv_title](https://docs.pandoranext.com/en-US/configuration/config/#isolated_conv_title) 目前无法做到。
