### ISSUE TITLE
site_password功能BUG

### ISSUE THREAD

**Issue by oSunnyo** [pandora-next/deploy#35]
设置config.json中的site_password密码后，登陆主页提示输入密码，但提交后显示 please reload page 无法正常进入！

**Comment by gltjk** [comment]
这个 bug 好像在 Chrome、Edge 等 Chromium 系浏览器里出现得比较多，可能的解决方案有三个：
A. 换非 Chromium 系浏览器，如 Firefox、Safari 等。
B. 在控制台的应用程序里手工添加一条 cookie，名称为 `_Secure-next-auth.site-password`，值为你设置的密码，然后多刷新两次页面。
C. 反复尝试输密码+提交+刷新的组合，直到最终成功😂

**Comment by ottocsb** [comment]
这就是php万岁？

**Comment by walnutsandwich** [comment]
这个site_password 参数有什么用

**Comment by walnutsandwich** [comment]
请问这个site_password 参数有什么用？

**Comment by gltjk** [comment]
> 这个 bug 好像在 Chrome、Edge 等 Chromium 系浏览器里出现得比较多，可能的解决方案有三个： A. 换非 Chromium 系浏览器，如 Firefox、Safari 等。 B. 在控制台的应用程序里手工添加一条 cookie，名称为 `_Secure-next-auth.site-password`，值为你设置的密码，然后多刷新两次页面。 C. 反复尝试输密码+提交+刷新的组合，直到最终成功😂

方案四（**最佳实践**）：升级到 [v0.1.2](https://github.com/pandora-next/deploy/releases/tag/v0.1.2) 🤣

**Comment by oSunnyo** [comment]
v0.1.2 已修复此BUG
