### ISSUE TITLE
【BUG】刷新License Id后，旧的License Id在PandoraNext中仍然有效

### ISSUE THREAD

**Issue by BBrother-GFC** [pandora-next/deploy#350]
Bug 概要:
在 https://dash.pandoranext.com/ 刷新License Id后，旧的License Id 仍然在 PandoraNext 中有效且能够正常识别并扣取额度。而不是失效，旧的License Id 仍然会自动重定向到PandoraNext中的新刷新的License Id。
（说人话就是：
新ID:ABCD
旧ID:EFGH
填入旧的ID
在setup界面看ID，可以发现用的是新ID）

重现步骤:

进入 https://dash.pandoranext.com/
刷新License Id。
打开 config.json 文件。
观察旧的License Id是否仍然存在，并且是否自动重定向到PandoraNext中的新License Id。
期望行为:
在刷新License Id后，config.json 文件中的旧License Id应该失效，不再自动重定向到PandoraNext中的新License Id。

实际行为:
旧的License Id仍然存在于 config.json 文件中，并且仍然自动重定向到新刷新的License Id。

**Comment by wozulong** [comment]
我测试了正在运行的服务，点击更换，所有请求都403了。未能复线。

**Comment by BBrother-GFC** [comment]
经尝试，在开启刷新功能的那一天之前的license ID都能重定向到新的
解决办法：刷新两遍就不行了（两个号都试了（废两号，悲
