### ISSUE TITLE
【功能】能把UI改成与老版演示站相似的吗

### ISSUE THREAD

**Issue by HJZ0713** [pandora-next/deploy#352]
如题，新版UI不太好看，希望可以把他改成老版演示站那样的，看着更像真正的ChatGPT
![屏幕截图 2023-12-16 135717](https://github.com/pandora-next/deploy/assets/114553430/3bc8e214-dccf-4e6c-9a4e-5f9d87378294)

**Comment by ijay666** [comment]
可是现在真正的 ChatGPT 就是新版 ui 的样子啊！🤣

**Comment by HJZ0713** [comment]
啊？我看看去
