### ISSUE TITLE
【功能】Pandora的Backend-api转/v1/chat/completions的小项目

### ISSUE THREAD

**Issue by Ink-Osier** [pandora-next/deploy#353]
来蹭蹭始皇热度~

为了方便大家把 PandoraNext 用到更多的地方，写了一个草台班子小项目，来把绘图、代码解释器、联网、GPTS等功能转成`/v1/chat/completions`接口~

支持代码解释器、绘图、联网和大部分的GPTS，希望对大家有帮助~

项目链接：https://github.com/Ink-Osier/PandoraToV1Api

效果示例：
![cb10baa0c84cc21a0e6d7f86099151a](https://github.com/pandora-next/deploy/assets/133617214/e1796cc2-0b57-486e-80e6-20c10d04cae7)

同时也有一个方便大家一键部署获取始皇的证书剩余额度的小项目，之前有小伙伴有类似的，这里做了一个docker的，响应的证书id和ip也做了保护，有需要的小伙伴也可以看看：https://github.com/Ink-Osier/getPandoraLicenseUsage

**Comment by QvQQ** [comment]
诶？不是可以直接请求访问PandoraNext的/v1/*的API接口嘛？为什么还要转发？

**Comment by Ink-Osier** [comment]
因为pandora自带的v1只支持纯文字生成，不支持绘图，代码解释器，联网，还有gpts，hh

**Comment by lisankai93** [comment]
很需要，试试，感谢作者！

**Comment by jeff-mao** [comment]
项目里面介绍了Docker-Compose 部署，如果pandora-next是直接运行的服务器上的应该怎么设置？

**Comment by Ink-Osier** [comment]
Pandora-Next的运行方式并不影响这个项目的使用，只是这个项目建议用docker-compose

**Comment by yuwangi** [comment]
请问这个 支持 官方的api 吗？ 可以直接用吗

**Comment by Ink-Osier** [comment]
> 请问这个 支持 官方的api 吗？ 可以直接用吗

不支持sk调用，是纯网页版ChatGPT转API的项目

**Comment by volatile-static** [comment]
请问chat/completions什么时候能支持视觉模型

**Comment by Ink-Osier** [comment]
> 请问chat/completions什么时候能支持视觉模型

近期有该功能的推进计划，具体完成时间未知

**Comment by Ink-Osier** [comment]
> 请问chat/completions什么时候能支持视觉模型

已支持，请关注最新版项目
