### ISSUE TITLE
【功能】关于Ping remote server failed问题的解决方案

### ISSUE THREAD

**Issue by xzy103** [pandora-next/deploy#355]
# 问题说明
不少小伙伴更新docker镜像后，出现了`Ping remote server failed`报错的问题。
![image](https://github.com/pandora-next/deploy/assets/40889019/5b418682-32f9-436c-942c-1206362429da)

我发现大家好像都有点一头雾水，虽然我一开始也这样。

一通找下来，其实项目作者一开始就说了问题的解决办法，但没被重视（居然还被点了👎，过分）
![image](https://github.com/pandora-next/deploy/assets/40889019/fb062078-c6f7-4d3e-9388-82f16c599406)

# 如何解决
我试了一下，只需要在启动docker的时候，**增加一条卷映射**就可以了，将本机的时间映射到容器内。

增加：`/etc/localtime:/etc/localtime:ro`

其中`ro`表示`only read`，只读。

解决。

（本人服务器位于国内，使用北京时间，如果加了卷映射还是存在该问题，猜测可能是因为主机的时间非北京时间。）

---

**最后，大家提issue前记得Star，尊重作者。**

**Comment by D3-3109** [comment]
感谢，一开始没注意到这个issue，居然是被closed了
