### ISSUE TITLE
【求助】如何添加chatgpt4模型？

### ISSUE THREAD

**Issue by jiaxinonly** [pandora-next/deploy#357]
**描述请求**
请问如何添加chatgpt4模型?

**问题陈述**
目前自行部署了pandora-next，只有一个chatgpt3.5，我想使用chatgpt4，是否只要我的账号升级了chatgpt plus，就可以解锁？

**预期结果**
购买chatgpt plus可以代理chatgpt4

**Comment by dadaewqq** [comment]
right
