### ISSUE TITLE
【求助】Proxy api到底怎么用啊啊啊啊，折腾了几个小时也没成功。。。大佬们救救孩子吧

### ISSUE THREAD

**Issue by shentong0722** [pandora-next/deploy#358]
**描述请求**
看了几百遍官方文档，尝试了无数次也没搞明白咋用啊这个

**问题陈述**
Proxy API不会用

**截图/日志**

用/v1/chat/completions会返回这个：
![image](https://github.com/pandora-next/deploy/assets/63089521/a7bc1af8-46eb-4523-84e5-be17ae00218c)
浏览器直接访问则返回：
<img width="1279" alt="image" src="https://github.com/pandora-next/deploy/assets/63089521/e15e1c8b-215c-4486-ae57-6a3402de6d5e">

用/v1则返回：
![image](https://github.com/pandora-next/deploy/assets/63089521/fbc81e13-80d7-4e07-bf47-ca3c8e331f7f)
浏览器直接访问返回：
<img width="1280" alt="image" src="https://github.com/pandora-next/deploy/assets/63089521/64759de1-f8b2-4fba-96ad-6c7e7cef00b4">

用/backend-api/conversation则返回：
![image](https://github.com/pandora-next/deploy/assets/63089521/192f51a5-a1ab-4509-a37f-809c029a2c29)
浏览器直接访问返回：
<img width="1280" alt="image" src="https://github.com/pandora-next/deploy/assets/63089521/09e6bc61-2c6c-43b9-912e-82b317ac1fa0">

**相关代码片段**
真的是把所有的方法全都试遍了也成功不了，大佬们救救孩子吧

**Comment by crosspacific** [comment]
文档看不懂，去看不良林的视频

**Comment by shentong0722** [comment]
好家伙。。。什么后缀都不用加原来

**Comment by cyj153** [comment]
这个Proxy api还能在ChatGPT-Next-Web中使用吗？有教程吗？
