### ISSUE TITLE
没有超过注册1年的github账户

### ISSUE THREAD

**Issue by jinde98** [pandora-next/deploy#36]
![image](https://github.com/pandora-next/deploy/assets/127750182/39ab1f46-b487-4cda-b7b4-c9d963eee5e6)
没有注册超过1年的账户，我该怎么办 ？

**Comment by zhheo** [comment]
在一年的等待期内用开发者提供的

**Comment by wozulong** [comment]
没有可以使用演示站

**Comment by AShanWang** [comment]
一样，
![image](https://github.com/pandora-next/deploy/assets/129077870/591e550a-c03b-4518-a22c-129a36adcb75)
