### ISSUE TITLE
【功能】https://platform.openai.com/

### ISSUE THREAD

**Issue by JasonTa2023** [pandora-next/deploy#365]
**您的功能请求是否与问题有关？请描述。**
是的，目前PandoraNext能登录chat.openai.com

**描述您想要的解决方案**
希望proxy模式能增加登录https://platform.openai.com/平台。
并返回由https://api.openai.com/dashboard/onboarding/login返回的sess-开头的临时api-key。

**描述您考虑过的替代方案**
手动登录到platform.openai.com获取

**附加上下文**
![2023-12-18_100414](https://github.com/pandora-next/deploy/assets/143620580/24d5312e-c83b-4dbf-aa42-638dd08d715a)

---

请将占位符替换为您的具体详情，以创建一个全面的功能请求工单。

**Comment by mouxangithub** [comment]
始皇说不加这个
