### ISSUE TITLE
【功能】docker搭建时通过账号密码登陆

### ISSUE THREAD

**Issue by Tzbfire** [pandora-next/deploy#366]
如pandora的时候
docker run -d -p 5000:5000 -v /root/GPT:/data -e OPENAI_EMAIL=账号 -e OPENAI_PASSWORD=密码 -e OPENAI_MFA_CODE=false -e PANDORA_SERVER=0.0.0.0:5000 --restart unless-stopped --name pandora pengzhile/pandora:latest

**Comment by mouxangithub** [comment]
没看懂，现在不就支持账号密码登录么，包括tokens.json也可以配账号密码

**Comment by x-Zer0** [comment]
> 没看懂，现在不就支持账号密码登录么，包括tokens.json也可以配账号密码
可以给个示例吗，账号密码具体怎么写，官网对tokens.json没看太明白

**Comment by QAbot-zh** [comment]
> > 没看懂，现在不就支持账号密码登录么，包括tokens.json也可以配账号密码
> > 可以给个示例吗，账号密码具体怎么写，官网对tokens.json没看太明白

![image](https://github.com/pandora-next/deploy/assets/40236765/a3599c3e-cf77-4196-bc1b-51f9b4f2b3d1)

**Comment by wozulong** [comment]
请跟随[文档](https://docs.pandoranext.com/)搭建PandoraNext，不要继续使用老的Pandora

**Comment by Tzbfire** [comment]
> > > 没看懂，现在不就支持账号密码登录么，包括tokens.json也可以配账号密码
> > > 可以给个示例吗，账号密码具体怎么写，官网对tokens.json没看太明白
> 
> ![image](https://private-user-images.githubusercontent.com/40236765/291484859-a3599c3e-cf77-4196-bc1b-51f9b4f2b3d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzQ4NDIsIm5iZiI6MTcwMzAzNDU0MiwicGF0aCI6Ii80MDIzNjc2NS8yOTE0ODQ4NTktYTM1OTljM2UtY2Y3Ny00MTk2LWJjMWItNTFmOWI0ZjJiM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDAxMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NjZmYWYwMWUwMTI4ODI5NjliMzFmODU0MmE5YWY5YzIxNWI0NWFkMWRhZmRiNTIwNzRjMDlkZWM3MjlkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4-mxqcYgkPifKAZQDXEjWpRJGr-fO0lGr1C9FVKwQvQ)

![image](https://github.com/pandora-next/deploy/assets/13600034/5cac5a60-fb9a-422b-bf4d-f0a058a0a7b5)
![image](https://github.com/pandora-next/deploy/assets/13600034/f375b9db-eafd-4220-a251-2a67c27407db)

我该怎么设置，打开网页即用？
