### ISSUE TITLE
proxy模式的actoken是如何获取的【求助】

### ISSUE THREAD

**Issue by isJN** [pandora-next/deploy#368]
我的代码如下：
data = {
            "username": username,
            "password": password
        }
url = "http://myIP:prot/qq123456789/auth/login"
headers = {
            "Content-Type": "application/x-www-form-urlencoded"
        }
response = requests.get(url, data=urlencode(data), headers=headers)
其中设置如下
![11111111111111111111](https://github.com/pandora-next/deploy/assets/58289415/2cf2d2ec-8c43-4b5d-b8c2-2c9f1f44b6a3)

运行信息
登录失败，状态码： 404

**Comment by JasonTa2023** [comment]
response = requests.get(url, data=data, headers=headers)

**Comment by isJN** [comment]
> response = requests.get(url, data=data, headers=headers)

还是一样的报错

**Comment by isJN** [comment]
还是一样的报错

**Comment by lnts2015** [comment]
> http://myIP:prot/qq123456789/auth/login

这样使用： http://myip:prot/qq123456789/api/auth/login   你的少了个api
