### ISSUE TITLE
【BUG】gpt4-mobile刷新页面跳回gpt4模型

### ISSUE THREAD

**Issue by suisei-pettan** [pandora-next/deploy#371]
**描述错误**
使用gpt4-mobile模型新开的会话在页面刷新后会变为gpt4模型且后续对话使用gpt4额度

**复现步骤**
按照以下步骤复现错误：
1. 模型选择 gpt4-mobile模型 ,创建会话.
2. 重新打开或刷新页面.
3. 观察到左上角的模型从ChatGPT Alpha 变为 ChatGPT 4，且后续对话对话会占用gpt4额度.

**预期行为**
页面刷新后仍保持使用 gpt4-mobile模型.

**截图**
刷新前
<img width="1241" alt="image" src="https://github.com/pandora-next/deploy/assets/44109309/b2918fb2-3ddb-481e-88af-e2dbf0929281">
刷新后
<img width="1245" alt="image" src="https://github.com/pandora-next/deploy/assets/44109309/cac8bcd2-ff64-4d70-817d-d36ad306b08d">

**Comment by wozulong** [comment]
现在是强开使用的。上下文没问题，次数限制也不止40次/3小时。但不能刷新，这个问题暂时无法解决。
