### ISSUE TITLE
【功能】登录提示RefreshAccessTokenError

### ISSUE THREAD

**Issue by zhangmc** [pandora-next/deploy#373]
session token和refresh token可自动刷新。
{
    "test_1": {
        "token": "session_token",
        "shared": false,
        "show_user_info": true
    }
}
按照文档配置token.json的session token，一周后登录提示RefreshAccessTokenError错误，重新获取session token加载后正常，
请问下是什么问题？

**Comment by wozulong** [comment]
session token过期了
