### ISSUE TITLE
【功能】access_token 模式下，能支持openai的function_call么？

### ISSUE THREAD

**Issue by yetio** [pandora-next/deploy#380]
**您的功能请求是否与问题有关？请描述。**
当我询问大模型：“当前天气怎么样？”时，在chatgpt中，可以通过联网访问或者天气plugin的形式支持；在openai的api中，有function call功能自己定义此命令。而通过pandora时，无法支持这两种形式。

**描述您想要的解决方案**
支持function call命令

**描述您考虑过的替代方案**
清晰且简洁地描述您考虑过的任何替代解决方案或功能。

**附加上下文**
在此处添加关于功能请求的任何其他上下文或截图。

---

请将占位符替换为您的具体详情，以创建一个全面的功能请求工单。

**Comment by yetio** [comment]
https://platform.openai.com/docs/guides/function-calling

**Comment by wozulong** [comment]
不支持的。
