### ISSUE TITLE
【功能】希望在文档下加入 不良林 大佬博客文章

### ISSUE THREAD

**Issue by CHN-STUDENT** [pandora-next/deploy#386]
**您的功能请求是否与问题有关？请描述。**
希望在文档下加入 不良林 大佬博客文章，不良林大佬解释了一些专业术语，方便我们这些小白。

**描述您想要的解决方案**
目前我这菜鸟有很多概念一知半解，直接读教程比较生硬，直接问一些问题也怕打扰大佬们和被嘲笑，但是不学习、不查阅资料进步不了，所以需要看一些白话文的文章学习，不良林大佬的文章给了我很大启发。

**描述您考虑过的替代方案**
在文章其他说明加入 [不良林大佬的 pandora 使用教程](https://bulianglin.com/archives/pandora.html)

**附加上下文**
在此处添加关于功能请求的任何其他上下文或截图。
感谢你们，又学习很多，这个点子来源  https://github.com/pandora-next/deploy/issues/358#issuecomment-1858826275

**Comment by CHN-STUDENT** [comment]
pull 请求 https://github.com/pandora-next/deploy/pull/387

**Comment by wozulong** [comment]
现在有了新的文档站，可以去看看。

**Comment by CHN-STUDENT** [comment]
@wozulong 我得意思想在文档站放上他的连接，有时候我看名词看不太懂，我觉得他写的文章挺好的，能够当作一篇好教程，不知道合理不。
