### ISSUE TITLE
【求助】用户信息相关问题

### ISSUE THREAD

**Issue by qingfengfenga** [pandora-next/deploy#389]
**描述请求**
想问一下，`Docker-compose`部署的环境，用户注册后，用户信息存储在哪里？怎么备份用户信息？怎么重置密码？

**Comment by nianhua99** [comment]
用户注册是注册的openai账号，跟你部署的没关系

**Comment by qingfengfenga** [comment]
> 用户注册是注册的openai账号，跟你部署的没关系

那这种情况的话，使用第三方账号登陆的OpenAI账号，是不是就只能去官网拿`access token`和`session token`登录了

**Comment by wozulong** [comment]
注册的是官方账号，改密码去官方该。第三方账号登录的，去官方。
