### ISSUE TITLE
【求助】内置账号密码的格式为：邮箱,密码，此种是0额度消耗的。这个消耗是web下还是proxy

### ISSUE THREAD

**Issue by xiaobinglan** [pandora-next/deploy#391]
**描述请求**
内置账号密码的格式为：邮箱,密码，此种是0额度消耗的。这个消耗是web下还是proxy

**问题陈述**
我在使用邮箱和密码使用的时候，依旧会扣除我的额度
![123123123123](https://github.com/pandora-next/deploy/assets/100662830/85e9a6ee-11f4-4fa1-b0c6-ae3102c7aeda)

**已采取的步骤**
尝试多个邮箱账号使用，依旧产生1：1消耗，我是在web上测试的

**预期结果**
希望指点指点，能使用0消耗的话解决日常较大的使用量

**环境信息（请完整填写以下信息）：**
- 操作系统： Windows
- 版本：11
- 架构： x86_64

**正在使用的工具/框架**
Pandoranext

---

**Comment by wwlmm** [comment]
这里说的消耗是 登录 的消耗，因为通常调用登录接口的风险都是很大的，一般登录消耗比例是：1:100。你在web模式下使用的话，消耗就是1:1，莫非你以为使用邮箱和密码登录就不消耗你对话所使用的额度了吗？

**Comment by wozulong** [comment]
tokens.json的所有描述，都与proxy模式无关。
