### ISSUE TITLE
【求助】我的proxy使用v1/chat/completions 3.5模型比例 1:10！！

### ISSUE THREAD

**Issue by xiaobinglan** [pandora-next/deploy#392]
**描述请求**
今天在使用的时候产生的消耗是1：10

**已采取的步骤**
web邮箱密码是1：1，但是proxy下是1：10，使用的是3.5模型，之前是1：4

**预期结果**
仍然无法解决

**环境信息（请完整填写以下信息）：**
- 操作系统：Windows
- 版本：11
- 架构： x86_64

**正在使用的工具/框架**
python

**相关代码片段**
    # 准备请求数据
    # gpt-3.5-turbo
    payload = {
        "model": "gpt-3.5-turbo",  # 指定模型，根据实际情况调整
        "messages": [
            {"role": "user", "content": user_message}  # 接收传入的用户对话内容
        ],
        "max_tokens": 3000,  # 最大生成的令牌数量，根据需要调整
    }

---

**Comment by wozulong** [comment]
那是不会的，你检查一下参数。
