### ISSUE TITLE
【BUG】GTP4不能用了？

### ISSUE THREAD

**Issue by kuke21** [pandora-next/deploy#394]
本以为是版本问题，升级到0.6.0也一样 报There was a problem preparing your chat. Please refresh the page and try again.  用GTP3.5就正常
<img width="986" alt="{3CB13E11-2AFD-4bf8-8B62-CC8F2D61B46B}" src="https://github.com/pandora-next/deploy/assets/55670537/5fa6e41e-a748-42f3-a7b5-9993c976067a">

**Comment by breeze1988** [comment]
遇到一样的问题啊，刷新了accessToken还是不行

**Comment by oushucan** [comment]
同问。There was a problem preparing your chat. Please refresh the page and try again.按提示网页重打开试过，还一样。然后是用docker-compose装的，down过再up还一样

**Comment by kuke21** [comment]
我的可以了

**Comment by xiaowu191** [comment]
有朋友遇到这个问题吗？plus账号，昨天还可以，今天似乎接口不通了；
![Snipaste_2023-12-21_12-02-56](https://github.com/pandora-next/deploy/assets/17995477/68ff3a0b-0377-4062-998f-40bf06ab2b24)

**Comment by wozulong** [comment]
> 有朋友遇到这个问题吗？plus账号，昨天还可以，今天似乎接口不通了； ![Snipaste_2023-12-21_12-02-56](https://private-user-images.githubusercontent.com/17995477/292082953-68ff3a0b-0377-4062-998f-40bf06ab2b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDIxMjcsIm5iZiI6MTcwMzE0MTgyNywicGF0aCI6Ii8xNzk5NTQ3Ny8yOTIwODI5NTMtNjhmZjNhMGItMDM3Ny00MDYyLTk5OGYtNDBiZjA2YWIyYjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA2NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTBkZmI2NGMzYmE3MjQzMjNkNjgxZWNkYzdiNGJmODU4ZDRkNzg3OWMxNWVkZDJiMjc5ODQ0YzgxYjY3YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bEMXnyrbu_lb6t5dYBtBVnKItjkeHkv7BX9p9vvcZ_c)

你可能要更新一下版本。

**Comment by wozulong** [comment]
openai今天早上搞了下事，又回滚了。不过将来的某天可能又上去，到时候更新吧。
