### ISSUE TITLE
【BUG】无法使用Pool Token登录官方演示站点和ChatGPT-Next-Web

### ISSUE THREAD

**Issue by aaro-n** [pandora-next/deploy#404]
**描述错误**
使用Pool Token登录官方演示站点时提示“token is malformed: token contains an invalid number of segments”，自建站点和官方演示站点都试过，出现相同的提示，Session Token，Access Token，Share Token这三项都可以正常登录
。
**复现步骤**
按照以下步骤复现错误：
1. 打开[链接](https://chat.openai.com/api/auth/session)，从官方网站获取Session Token和 Access Token。
2. 打开[链接](https://ai.fakeopen.com/token)，填入 Access Token获取Share Token，Share Token可以正常登录。。
3. 打开[链接](https://ai.fakeopen.com/pool)，填入Share Token，获取Pool Token，Pool Token无法使用，填入Pool Token提示描述里的错误。

**预期行为**
正常 使用Pool Token

**截图**
如果适用，添加截图以帮助解释您的问题。

**服务器（请完成以下信息）：**
 - 操作系统：Docker
 - 版本：0.6.0,0.6.1
 - 架构: x86_64

**桌面（请完成以下信息）：**
 - 操作系统：macos
 - 浏览器：chrome
 - 版本：119.0.6045.15

**智能手机（请完成以下信息）：**
 - 设备：[例如 iPhone6]
 - 操作系统：[例如 iOS8.1]
 - 浏览器：[例如 stock browser, safari]
 - 版本：[例如 22]

**附加上下文**
在此处添加关于问题的任何其他上下文。

---

请将占位符替换为您的具体详情，以创建一个全面的问题报告。

**Comment by aaro-n** [comment]
参考文档：https://bulianglin.com/archives/pandora.html

**Comment by guobaozu** [comment]
感觉pool token应该是出问题了，我今天生成的pool token也全部报这个错误。

**Comment by aaro-n** [comment]
现在ChatGPT-Next-Web又可以正常使用Pool Token了，问题先开着，明天正常，会关闭此问题。

**Comment by wozulong** [comment]
pool token不能使用ChatGPT，只能请求chat2api
