### ISSUE TITLE
【求助】Ping remote server failed, detail: Access denied, Ip: xxx.xxx.xxx.xxx, Reason: ip

### ISSUE THREAD

**Issue by xiaobinglan** [pandora-next/deploy#411]
**描述请求**
突然出现的问题，之前还在正常使用

**问题陈述**
使用proxy接口调用api的形式使用

**已采取的步骤**
更换license_id、关闭梯子都无法使用

**截图/日志**
![微信截图_20231223220156](https://github.com/pandora-next/deploy/assets/100662830/2a52d2ee-79aa-4904-beb4-702456593db3)

**环境信息（请完整填写以下信息）：**
- 操作系统：Windows
- 版本：10
- 架构： x86_64

---

**Comment by wozulong** [comment]
[https://docs.pandoranext.com/zh-CN/deploy/FAQ#%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF](https://docs.pandoranext.com/zh-CN/deploy/FAQ#%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF)
