### ISSUE TITLE
【求助】如何设置用户名&密码访问呢？我总是会报错

### ISSUE THREAD

**Issue by xybio** [pandora-next/deploy#416]
**描述请求**
如何设置用户名&密码访问呢？是把这里

 "token": "access token / session token / refresh token / share token / username & password",

的username & password替换掉吗？
我这里总是会出现如下报错，可能是我没理解了该如何设置，能给我具体提供一个配置的范例吗？

**问题陈述**
报错：
Error
you must set a password to embed accounts directly

---

**Comment by xybio** [comment]
已解决，打扰

**Comment by yefeiyu** [comment]
> 已解决，打扰

怎么解决的说一声啊
