### ISSUE TITLE
【求助】使用clash如何正确访问，要放行哪些域名或ip?

### ISSUE THREAD

**Issue by aston314** [pandora-next/deploy#430]
stderr: 2023/12/29 05:21:14 Ping remote server failed, detail: Access denied, Ip: 54.64.27.74, Reason: ip
stderr: 2023/12/29 05:22:17 Failed to fetch license: Too Many Requests(429)
stderr: 2023/12/29 05:23:20 Failed to fetch license: Too Many Requests(429)

**Comment by mouxangithub** [comment]
Failed to fetch license: Too Many Requests，你的license id呢，配了？

**Comment by wozulong** [comment]
[https://docs.pandoranext.com/zh-CN/deploy/FAQ#错误信息](https://docs.pandoranext.com/zh-CN/deploy/FAQ#%E9%94%99%E8%AF%AF%E4%BF%A1%E6%81%AF)
