### ISSUE TITLE
【BUG】/api/auth/login 对于某些账号报错 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by QvQQ** [pandora-next/deploy#435]
**描述错误**
全新账号是指，刚刚注册、没有进行过任何对话的账号。（我只测试了PandoraNext提供的sign up功能所注册的账号）

1. 当使用全新账号的`email`与`password`以`POST`请求`/api/auth/login`接口时，返回的HTTP状态码为`500`。
2. 在服务器端使用`docker logs container_name`可以发现`[GIN] 2024/01/01 - 11:45:14 | 500 |  191.9810µs |  x.x.x.x | POST     "/proxy_prefix/api/auth/login"`。
3. 当使用相同账号在web端（无论是原ChatGPT网页、还是PandoraNext的web页面）至少进行一轮对话后，再次请求该接口，即可正常获取`access_token`与`session_token`。（maybe）
4. （即使请求出错也扣了额度呜呜呜TvT）
5. `全新账号`似乎是稳定复现的，其他账号（包括已注册使用了几小时）的也有概率出现。

**截图**
<img width="753" alt="image" src="https://github.com/pandora-next/deploy/assets/35735975/aa0a30dc-796a-4bf3-9bfc-03fdd6d76e43">
<img width="1099" alt="image" src="https://github.com/pandora-next/deploy/assets/35735975/fb10d0c2-2527-40af-b704-61fba7cc6102">

**服务器：**
 - 操作系统：Ubuntu
 - 版本：18.04.5 LTS
 - 架构：x86_64

**Comment by wozulong** [comment]
你应该在请求接口时打印报错信息，只打印状态码无法知道具体问题。
