### ISSUE TITLE
用已经注册好的账户登录失败，显示：该密码不是您在注册期间使用的身份验证方法。【求助】

### ISSUE THREAD

**Issue by yangpin97** [pandora-next/deploy#436]
**描述请求**
帮忙查看登录时遇到的问题，谢谢。

**问题陈述**

本地用docker部署完，可以正常打开web界面，但是在登录自己已有的谷歌账户（这个账户能正常使用登录chatgpt官方的）时一直提示如下几类报错。

**已采取的步骤**
1、切换容器代理，全局海外，分流，全局国内。
2、电脑切换代理，全局海外，分流，全局国内。

**预期结果**
希望能正常登录PandoraNext

**截图/日志**
1、容器正常启动截图
![image](https://github.com/pandora-next/deploy/assets/105636974/bcd86e90-5b53-456c-a740-c63341611bc4)

2、web登录报错截图1（这个报错是我忘记openai重新设置的密码报错）
![image](https://github.com/pandora-next/deploy/assets/105636974/a1620554-b7f6-447c-b2e3-e06d8d6bbb37)

3、web登录报错截图2（这个报错是输入我谷歌账户密码报错）
![image](https://github.com/pandora-next/deploy/assets/105636974/4fed891c-99db-41c9-a4f8-320e1cded29d)

4、登录日志截图
![image](https://github.com/pandora-next/deploy/assets/105636974/04af239a-5cc7-4b31-9156-564f0e00fae9)

**环境信息（请完整填写以下信息）：**
- 操作系统：ubuntu
- 版本： Ubuntu 23.04 
- 架构：(GNU/Linux 6.2.0-39-generic x86_64)

**相关代码片段**
docker代码
version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: openai
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "8081:8181"
    volumes:
      - ./data:/data（授权ID已经配置好了）
      - ./sessions:/root/.cache/PandoraNext

**Comment by yangpin97** [comment]
更新报错截图：
![image](https://github.com/pandora-next/deploy/assets/105636974/973d6524-caea-4e31-b101-383ebdb93a43)

**Comment by wozulong** [comment]
3个截图3个错。 第三方登录的账号，不能直接登录。

**Comment by yangpin97** [comment]
@wozulong 好的，那我直接用PandoraNext提供的代理，用一个新的谷歌账户（没有注册过openai）直接注册一个新的可行吗？
