### ISSUE TITLE
按照docker命令部署，不知道为啥老这样

### ISSUE THREAD

**Issue by smerckzak** [pandora-next/deploy#44]
![微信图片_20231117105603](https://github.com/pandora-next/deploy/assets/64113248/8e396f21-c9fb-4a44-bed7-009dd1f83e7c)
![微信图片_20231117110116](https://github.com/pandora-next/deploy/assets/64113248/121d2605-8fd1-465e-b065-971f9cc618ba)

**Comment by smerckzak** [comment]
root@armbian:~# docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                  PORTS                                       NAMES
ea0899d310bf   pengzhile/pandora-next           "/opt/app/entrypoint…"   8 seconds ago   Up Less than a second   0.0.0.0:8181->8181/tcp, :::8181->8181/tcp   PandoraNext



CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS                          PORTS     NAMES
ea0899d310bf   pengzhile/pandora-next           "/opt/app/entrypoint…"   About a minute ago   Restarting (1) 23 seconds ago             PandoraNext

用session token 就是这样 然后一直restarting

**Comment by sunzehui** [comment]
https://github.com/pandora-next/deploy#%E5%85%B3%E4%BA%8E-licensejwt%E6%96%87%E4%BB%B6

**Comment by smerckzak** [comment]
> https://github.com/pandora-next/deploy#%E5%85%B3%E4%BA%8E-licensejwt%E6%96%87%E4%BB%B6

找到这个了。token就是中间那段么。。我按照docker命令部署以后，自动在、root生成一个lisence。jwt 打开换成获取的token还是一直restarting

**Comment by smerckzak** [comment]
root@armbian:~# docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                          PORTS     NAMES
6c38d82e4d39   pengzhile/pandora-next           "/opt/app/entrypoint…"   18 minutes ago   Restarting (1) 48 seconds ago

**Comment by taozihk** [comment]
老哥 非得用docker？

**Comment by smerckzak** [comment]
> 老哥 非得用docker？

不用docker那用啥

**Comment by ljnchn** [comment]
![docker](https://github.com/pandora-next/deploy/assets/6970776/478c7312-7e6c-41bb-ad3c-776a3595549b)

**Comment by smerckzak** [comment]
> ![docker](https://user-images.githubusercontent.com/6970776/283659389-478c7312-7e6c-41bb-ad3c-776a3595549b.png)

docker用户已经被大佬厌弃了吗

**Comment by wozulong** [comment]
> > ![docker](https://user-images.githubusercontent.com/6970776/283659389-478c7312-7e6c-41bb-ad3c-776a3595549b.png)
> 
> docker用户已经被大佬厌弃了吗

厌弃我为什么还发4个架构的镜像呢？只是很多人根本不会docker就要强上。

现在Releases发的bin直接运行，不用安装配置任何运行环境，何必强上docker？

**Comment by smerckzak** [comment]
> > > ![docker](https://user-images.githubusercontent.com/6970776/283659389-478c7312-7e6c-41bb-ad3c-776a3595549b.png)
> > 
> > 
> > docker用户已经被大佬厌弃了吗
> 
> 厌弃我为什么还发4个架构的镜像呢？只是很多人根本不会docker就要强上。
> 
> 现在Releases发的bin直接运行，不用安装配置任何运行环境，何必强上docker？

没办法啊，大佬。我也不想强上，谁叫docker输命令更简单呢，其他办法更复杂

**Comment by smerckzak** [comment]
昨天安装旧版的fakegpt，也是大佬你的作品吧？搭建了以后session token可以登入，就是输入问题没反应。。。想知道原因，也不知道去哪问....是不是fake停了？

**Comment by wozulong** [comment]
> > > > ![docker](https://user-images.githubusercontent.com/6970776/283659389-478c7312-7e6c-41bb-ad3c-776a3595549b.png)
> > > 
> > > 
> > > docker用户已经被大佬厌弃了吗
> > 
> > 
> > 厌弃我为什么还发4个架构的镜像呢？只是很多人根本不会docker就要强上。
> > 现在Releases发的bin直接运行，不用安装配置任何运行环境，何必强上docker？
> 
> 没办法啊，大佬。我也不想强上，谁叫docker输命令更简单呢，其他办法更复杂

其他软件不敢说，你手动部署一下PandoraNext就知道到底哪个简单了。
