### ISSUE TITLE
请教socks5如何配置username和password

### ISSUE THREAD

**Issue by LECYWZA** [pandora-next/deploy#442]
比如你使用Clash，你希望PandoraNext的流量走Clash的代理，那么你可以设置为：http://127.0.0.1:7980 或 socks5://127.0.0.1:7980

看config 没找到可以配置socks5 的 username和password？ 请问是不支持吗？
![image](https://github.com/pandora-next/deploy/assets/22796879/f089f11b-ef46-4cc8-b653-a8c8e212ec19)

**Comment by brucelau1987cn** [comment]
http://test:123456@192.168.1.10:8080
用户名test
密码123456

**Comment by wozulong** [comment]
楼上正解
