### ISSUE TITLE
【求助】阅读文档后，关于licence id获取仍然有一些问题

### ISSUE THREAD

**Issue by Clemet-Lxw** [pandora-next/deploy#443]
我已经认真阅读了项目的文档并且了解了获取license id的限制条件及注意事项。但我使用我的GitHub账号尝试获取它时（账号在2022年4月注册，超过180天）得到的返回是“注册未满180天”，我尝试了本地网络和全局代理的方式进行访问均得到此结果。请问这是否可能是我在操作过程中有未注意到的问题或是我错误理解了此处注册时间所指的内容？
![屏幕截图 2024-01-02 204145](https://github.com/pandora-next/deploy/assets/103412395/0264cd6f-6f6a-4d0d-95fd-bd27ef511ac7)

**Comment by kevinalpha** [comment]
我这儿也遇到一些问题，在使用Docker composedeploy，在启用docker-compose up的时候license id反馈一直显示toomany request 429，unable to fetch license，该怎么解决呢？有没有大神知道怎么帮忙处理？
