### ISSUE TITLE
通过ai.fakeopen.com网站获取到的Session Token只能使用10天

### ISSUE THREAD

**Issue by AndersonGhost** [pandora-next/deploy#446]
大佬您好，我使用10个账号，在同一天使用ai.fakeopen.com获取到的Session Token（不是Access Token）大概都只能使用10天，不是说Session Token可以使用3个月的吗？是哪里操作有误呀，感谢！！

**Comment by wozulong** [comment]
Session token获取access token时会给个新的，注意更换。
