### ISSUE TITLE
家里ip变化太快了，Access denied

### ISSUE THREAD

**Issue by gavinup** [pandora-next/deploy#45]
没几分钟就被限制了，有什么其他好思路解决吗

**Comment by gavinup** [comment]
![image](https://github.com/pandora-next/deploy/assets/30076575/3ff9d852-6d57-40c4-93b0-95da4529e344)

**Comment by taozihk** [comment]
老哥，花点钱买个小🐔吧～

**Comment by gavinup** [comment]
> 老哥，花点钱买个小🐔吧～

刚从vps服务全移到nas，又要移回去，😓
