### ISSUE TITLE
Failed to copy to clipboard.【求助】

### ISSUE THREAD

**Issue by txbxxx** [pandora-next/deploy#453]
在复制GPT输出的内容时报错 【Failed to copy to clipboard.】这是为什么呢？

**Comment by QAbot-zh** [comment]
去看文档，本地用127.0.0.1，服务器要开ssl：https://docs.pandoranext.com/

**Comment by txbxxx** [comment]
> 去看文档，本地用127.0.0.1，服务器要开ssl：https://docs.pandoranext.com/

谢谢哥，我大意了
