### ISSUE TITLE
【功能】使用PandoraNext全自动注册ChatGPT账号✓

### ISSUE THREAD

**Issue by QvQQ** [pandora-next/deploy#456]
## 项目地址
[ChatGPT-Register](https://github.com/QvQQ/ChatGPT-Register)

## 简单介绍
🚀 自动化注册：自动完成整个ChatGPT账号注册流程，使用Capsolver来绕过注册中的验证码。
📧 邮箱监控：自动监控和处理OpenAI的Verification认证邮件。
🐍 Python脚本：使用Python和selenium自动操作，并使用undetected_chromedriver防止检测。
🐳 Docker支持：通过Docker Compose轻松部署。
📦 灵活数据存储：结果保存在SQLite数据库，支持自定义存储。

### 数据库截图
![image](https://github.com/pandora-next/deploy/assets/35735975/c7b582c9-2d6a-427b-bb79-9066951b7a53)

### 注册过程日志截图
![image](https://github.com/pandora-next/deploy/assets/35735975/29ba8a73-096b-4b1d-8ec2-eedf273e83c5)

**Comment by nianhua99** [comment]
好东西

**Comment by ICLiuLi** [comment]
牛
