### ISSUE TITLE
【求助】突然每次对话都需要输入验证码

### ISSUE THREAD

**Issue by leichaoL** [pandora-next/deploy#458]
**描述请求**
不知道如何解决验证码问题

**问题陈述**
项目部署在本地windows电脑上，一开始使用是正常的。从某一天起突然每次对话都要输入验证码，进行拼图。

**已采取的步骤**
登录了其他账号没有问题，只有我这一个共享给局域网内其他人用的plus账号在我的本地使用会出问题。即便是在我本地尝试在share界面使用该账号都需要验证码。
我在本地尝试了其他账号，在其他电脑上尝试了本账号均没有验证码。

添加或者删除proxy设置，修改了bind，重启项目，重启电脑，清除cookie重新登录均试过了，没能解决。
用的v0.5.3版本，一开始正常，后来突然出现的问题。更新到最新的v0.6.1也无济于事。

**截图/日志**

![PixPin_2024-01-07_17-18-15](https://github.com/pandora-next/deploy/assets/66906588/fc0bb5e3-b41c-4065-8e9e-f85967e769b5)

**环境信息（请完整填写以下信息）：**
- 操作系统：Windows 10 专业版 22H2

**Comment by txbxxx** [comment]
可能是openai账号的问题你，你去openai官网登录试一下

**Comment by leichaoL** [comment]
> 可能是openai账号的问题你，你去openai官网登录试一下

openai官网使用没有问题，我在其他电脑上登录我本地部署的潘多拉，使用这个账号也没有问题。就很奇怪，不知道问题能出在哪。

**Comment by leichaoL** [comment]
今天突然又不用验证码了，也不知道具体什么原因，可能就是账号的问题吧。
