### ISSUE TITLE
【求助】开启https或者使用127.0.0.1 

### ISSUE THREAD

**Issue by acprk** [pandora-next/deploy#462]
如何开启https或者使用127.0.0.1？有无类似的教程推荐

**Comment by wj2008** [comment]
我是在nginx里反代pandora的，以下是gpt帮我修改了一下的 能正常跑
```
server {
    listen 80;
    listen 443 ssl;
    server_name *.123456.xyz;

    ssl_certificate /etc/letsencrypt/live/123456.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/123456.xyz/privkey.pem;

    location / {
        proxy_set_header Connection "";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_redirect off;
        proxy_buffering off;
	proxy_cache off;
        client_max_body_size 100M;

        set $backend_url "";

        if ($host = 'als.123456.xyz') {
            set $backend_url "http://10.0.0.1:5244";
        }
        if ($host = 'pandora.123456.xyz') {
            set $backend_url "http://10.0.0.1:8181";
        }
        if ($host = 'aosp.123456.xyz') {
            set $backend_url "http://10.0.0.1:8080";
        }
        if ($host = 'ya.123456.xyz') {
            set $backend_url "http://10.0.0.1:5288";
        }

        if ($backend_url = "") {
            set $backend_url "http://10.0.0.1:6666";
        }

        proxy_pass $backend_url;
    }
}
```

**Comment by acprk** [comment]
> 我是在nginx里反代pandora的，以下是gpt帮我修改了一下的 能正常跑
> 
> ```
> server {
>     listen 80;
>     listen 443 ssl;
>     server_name *.123456.xyz;
> 
>     ssl_certificate /etc/letsencrypt/live/123456.xyz/fullchain.pem;
>     ssl_certificate_key /etc/letsencrypt/live/123456.xyz/privkey.pem;
> 
>     location / {
>         proxy_set_header Connection "";
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header Host $http_host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Range $http_range;
>         proxy_set_header If-Range $http_if_range;
>         proxy_redirect off;
>         proxy_buffering off;
> 	proxy_cache off;
>         client_max_body_size 100M;
> 
>         set $backend_url "";
> 
>         if ($host = 'als.123456.xyz') {
>             set $backend_url "http://10.0.0.1:5244";
>         }
>         if ($host = 'pandora.123456.xyz') {
>             set $backend_url "http://10.0.0.1:8181";
>         }
>         if ($host = 'aosp.123456.xyz') {
>             set $backend_url "http://10.0.0.1:8080";
>         }
>         if ($host = 'ya.123456.xyz') {
>             set $backend_url "http://10.0.0.1:5288";
>         }
> 
>         if ($backend_url = "") {
>             set $backend_url "http://10.0.0.1:6666";
>         }
> 
>         proxy_pass $backend_url;
>     }
> }
> ```

喔，感谢
