### ISSUE TITLE
【求助】有人出现过这个警告吗，昨天还能用，今天就被警告阻止登录了

### ISSUE THREAD

**Issue by zoutao98** [pandora-next/deploy#468]
![Dingtalk_20240111093014](https://github.com/pandora-next/deploy/assets/46660687/84e420a6-6b4f-46fa-b720-2dba08b795e9)

**Comment by tangjianbing** [comment]
+1，一样的提示。而且用fakeopen获取token的时候，显示：获取失败: error request login url

**Comment by 0x222fe** [comment]
并且我用接口获取token也失败了
![image](https://github.com/pandora-next/deploy/assets/42604000/d179cbdf-dfd8-4068-85d4-9ca42fa800e0)
但是目前可以手动去openai获取token再通过token登录

**Comment by AcSully** [comment]
+1，在网页上点击log out，在重新登陆遇到这个问题

**Comment by oldweipro** [comment]
看来不止我一个遇到

**Comment by cq134cq** [comment]
我也有同样的问题，退出后在登陆就这样了，有什么办法解决吗？

**Comment by yaf0** [comment]
+1，zhile，大佬，pandoraNext好像是坏了，演示站https://chat.oaifree.com/也不行，我自己部署的也不行，登录提示miss arkose token  注册提示url不对什么的

**Comment by cq134cq** [comment]
代理被。。。。

**Comment by yaf0** [comment]
> 代理被。。。。

大家肯定主要是给非技术同事朋友用的，大家都跟zhile大佬混了，自己用肯定不成问题的

**Comment by leo0769** [comment]
同样遇到相同的问题，引用楼上大佬手动获取token确实可以用了

**Comment by wozulong** [comment]
oai又搞事情了，已修复。

**Comment by li88iioo** [comment]
+1昨日可用今日不行

**Comment by Chnja** [comment]
+1 又不可以了

**Comment by zwc4228986** [comment]
+1

**Comment by zrqohbug** [comment]
+1

**Comment by ayueryi** [comment]
+1

**Comment by Zhiyilang** [comment]
> +1，zhile大佬，PandoraNext好像是坏了，演示站 https://chat.oaifree.com/ 也不行 我自己部署的也一样 登录提示Miss Arkose Token 注册提示Error Request Signup URL ![image](https://private-user-images.githubusercontent.com/48549454/295763918-d83e0944-de04-4f26-83ae-dd4846a3780e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzM3NzUsIm5iZiI6MTcwNTAzMzQ3NSwicGF0aCI6Ii80ODU0OTQ1NC8yOTU3NjM5MTgtZDgzZTA5NDQtZGUwNC00ZjI2LTgzYWUtZGQ0ODQ2YTM3ODBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA0MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjY2E2YjEyOGY2ZjExODg4Y2Y0OTNkY2JlZTVlMGE4OTEyODEzMTY5ZWI0NDhhNzIzNTI5Y2NhMDdhMGRiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GrRKU2Pw-qHGCITlOFZed0TinEtGEbQJ0pqKSG1etSw) ![image](https://private-user-images.githubusercontent.com/48549454/295764199-8092aaad-913b-4db5-a13d-5423c2c9067e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzM3NzUsIm5iZiI6MTcwNTAzMzQ3NSwicGF0aCI6Ii80ODU0OTQ1NC8yOTU3NjQxOTktODA5MmFhYWQtOTEzYi00ZGI1LWExM2QtNTQyM2MyYzkwNjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA0MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzNkNTUxYTM4NjY2YjAwYWU4ODE5ZDE4ZDVkZTRlM2FmNGNlNDE1ZjJhYWZjZmI0ZDUxOTdmMTkxZjIzMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O1Juou3H4IBr_B3yoDAvfqz2xw2qxrYrDManc4ghMl8) ![image](https://private-user-images.githubusercontent.com/48549454/295764251-8d5d63b1-be88-4ef2-9c6e-adcaff582d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzM3NzUsIm5iZiI6MTcwNTAzMzQ3NSwicGF0aCI6Ii80ODU0OTQ1NC8yOTU3NjQyNTEtOGQ1ZDYzYjEtYmU4OC00ZWYyLTljNmUtYWRjYWZmNTgyZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA0MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MDBlOWYxODZmYjgzNTQ0Zjc1OWNhYzBmNmZhMTA0Y2U3NWNhNzlmYzM3ZDdkMmViZWQ1ZmE3NTU5MGFhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.591IQGsrgaKZwG0ZtiD2N58eK11cDvVIjEeF-9p7yKI)

友友那你最后是怎么做的呢？

**Comment by MotWnb** [comment]
> oai又搞事情了，已修复。

演示站没修复

**Comment by troilus** [comment]
目前还是有这个问题

**Comment by WPF0414** [comment]
+1 今天刚部署的。

**Comment by workyhx** [comment]
2024-1-19 依然存在这个问题
