### ISSUE TITLE
【求助】更新0.6.1后闪退，安全卫士报有风险。再退回0.5.3也同样闪退，没更新前一直能正常使用。什么原因？

### ISSUE THREAD

**Issue by lawlala** [pandora-next/deploy#469]
【求助】更新0.6.1后闪退，安全卫士报有风险。再退回0.5.3也同样闪退，没更新前一直能正常使用。什么原因？

**Comment by yaf0** [comment]
不是更新的事儿，应该是openai某些漏洞被堵上了，看另一个issue吧 #468

**Comment by wozulong** [comment]
拖到cmd里看看具体报什么错。
