### ISSUE TITLE
【BUG】无法登录与注册error request login url

### ISSUE THREAD

**Issue by xy3xy3** [pandora-next/deploy#476]
**提示error request login url**
登录或者注册时提示url错误

**复现步骤**
/auth/password
正常登陆输入账号密码

**预期行为**
登陆注册成功

**截图**
![image](https://github.com/pandora-next/deploy/assets/25221048/b8cee3f2-69d1-4612-9719-74fac6a055bb)

**Comment by ffllc** [comment]
我以为是我的问题,重新部署设置, 搞了半天.

**Comment by idoknown** [comment]
我也遇到了

**Comment by jieny** [comment]
我也遇到了

**Comment by areslp** [comment]
+1

**Comment by Jamerszhe** [comment]
+1

**Comment by LAkimoto** [comment]
+1

**Comment by MarcusYYDS** [comment]
+1

**Comment by JohnnieWind** [comment]
同样的问题

**Comment by wozulong** [comment]
已修复。

**Comment by zwc4228986** [comment]
又挂了

**Comment by czyt** [comment]
request forward login rate limit hit

**Comment by dycwuxing** [comment]
看来都遇到了

**Comment by SchrodingerFish** [comment]
同样的问题
