### ISSUE TITLE
手动部署exe打开，access_denied: OpenAI's services are not available in your country.无法登录

### ISSUE THREAD

**Issue by specialvan** [pandora-next/deploy#478]
![image](https://github.com/pandora-next/deploy/assets/59273632/979fdbb3-c49f-4216-9152-4c0d80fb79f6)
access_denied：OpenAI 的服务在您所在的国家/地区不可用。 （错误=不支持的国家/地区）
挂了代理也没用，官网demo也无法登录

**Comment by beyondczb** [comment]
之前使用正常 今天突然发现无法正常使用 
access_denied: OpenAI's services are not available in your country. (error=unsupported_country) 也是这个问题 是不是openai那边改了规则 坐等大佬更新一波

**Comment by EndlessJY** [comment]
+1

**Comment by beyondczb** [comment]
又出来这个错误 error request login url

**Comment by neomx7** [comment]
我也遇到了。应该是openai那边调整什么了。

**Comment by poxiao33** [comment]
一样一样

**Comment by beyondczb** [comment]
我这边问题已经得到修复
