### ISSUE TITLE
【BUG】PandoraNext不能获取access token了

### ISSUE THREAD

**Issue by Kwaiyu** [pandora-next/deploy#479]
**1. Obtaining refresh token API报错：**
curl 'http://127.0.0.1:8181/abcd1234/api/auth/login2' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'username=user%40mail.com' \
    -d 'password=abc123' \
    -d 'mfa_code=1234'

```
{
    "detail": "error request login url"
}
```

BaseURL/auth 网页发起也报同样的错

**2. fk、pk 全部失效了**

**3. 登录也报error request login url**

**Comment by poxiao33** [comment]
是的一样

**Comment by laorentou666** [comment]
使用email+password登录也同样报错

**Comment by yexingok** [comment]
我重新登陆也遇到了这个问题

**Comment by heipig** [comment]
我也遇到了
