### ISSUE TITLE
【求助】用户名+密码方式下，这个用户名必须在openai 的官网上注册过的吗？

### ISSUE THREAD

**Issue by wjuncn** [pandora-next/deploy#489]
**问题陈述**
在openai的官网上，成功申请了一个plus用户，然后想在内网分享这个账户。为了区分每个内网用户，想用 用户email+密码 的方式来区分，而不是常用的 “shared” 页面的方式。

**已采取的步骤**
1. 研究了文档，包括 tokens.json 的配置方式，使用用户email+密码的方式配置
2. 使用配置的用户email和密码方式，一直不能成功登录
3. 我感觉，这个用户email必须在openai官网上注册过，对吗？

**我采用的 tokens.json 配置文件：**
```
{
  "test-1": {
    "token": "eyxxxxx", 
    "shared": true,
    "show_user_info": true
  },
  "name1@abc.com": {
    "token": "name1@abc.com,pass1234!",
    "password":"pass1234!"
  }
}
```
其中 “test-1”用户的token是官方的access token，将“shared”设为“true”时是可用的。
然后下面的“name1@abc.com”，这个用户在openai 官网上是没有注册过的。在本例中无法使用。

**Comment by QAbot-zh** [comment]
举个例子，tokens.json里这么设置，然后就可以用abc的账号名+123456的密码登录，使用"bbbbbbbbbbbbbb@outlook.com,password"的账号权限
![image](https://github.com/pandora-next/deploy/assets/40236765/b013d74c-03b2-4906-9a59-54b5e4fe3a13)

**Comment by wjuncn** [comment]
@QAbot-zh 谢谢大佬回答。

在你给的例子里，就从字面上理解，是不是这样：

登录 Pandoranext 界面的用户名是“abc”，密码是“123456” （就是定义在password字段里的那串字符串）
这个用户对应到在 OpanAI 官网上注册的用户，是“bbbbbbbbbbbbbbb@outlook.com”，密码是“password”（就是token逗号后面的那串字符串）

对吗？

**Comment by QAbot-zh** [comment]
> @QAbot-zh 谢谢大佬回答。
> 
> 在你给的例子里，就从字面上理解，是不是这样：
> 
> 登录 Pandoranext 界面的用户名是“abc”，密码是“123456” （就是定义在password字段里的那串字符串） 这个用户对应到在 OpanAI 官网上注册的用户，是“[bbbbbbbbbbbbbbb@outlook.com](mailto:bbbbbbbbbbbbbbb@outlook.com)”，密码是“password”（就是token逗号后面的那串字符串）
> 
> 对吗？

对，能隐藏真实账号密码，但是不隔离对话

**Comment by wjuncn** [comment]
明白了，谢谢大佬
