### ISSUE TITLE
【求助】我多处部署，导致无法使用

### ISSUE THREAD

**Issue by yn197** [pandora-next/deploy#490]
**描述请求**
我在环境A，B本地分别使用部署了服务，但是我使用插件生成了多次，导致sessions里面出现多个，无法使用，然后删除重新启动，我该如何让A，B环境都可以使用？

**问题陈述**
我在环境A，B本地分别使用部署了服务，但是我使用插件生成了多次，导致sessions里面出现多个，无法使用，然后删除重新启动，我该如何让A，B环境都可以使用？

**已采取的步骤**
目前是删除sessions，重新生成使用

**预期结果**
我希望只要正常的插件生成的token都能使用

**截图/日志**
![image](https://github.com/pandora-next/deploy/assets/53424623/5a39fad8-c1f9-4c3c-8272-f5b9c5915c8e)

**环境信息（请完整填写以下信息）：**
- 操作系统：[例如 Windows、Linux]
- 版本：[例如 10]
- 架构：[例如 64]

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by wozulong** [comment]
license id是独占的，不能多处部署。可以多搞个github账号

**Comment by yn197** [comment]
好的我试试，thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pandora-next/deploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pandora-next/deploy] 【求助】我多处部署，导致无法使用 (Issue #490)





 
license id是独占的，不能多处部署。可以多搞个github账号
