### ISSUE TITLE
【求助】2024/01/17 01:02:42 Failed to fetch license: Too Many Requests(429)

### ISSUE THREAD

**Issue by hnuzhoulin** [pandora-next/deploy#498]
**描述请求**
2024/01/17 01:02:42 Failed to fetch license: Too Many Requests(429)  是因为ip发生变化吗？

**问题陈述**
出现如题的错误后无法使用

**已采取的步骤**
目前是等待，，，，

**预期结果**
确认问题点，再想办法解决

**截图/日志**
`2024/01/17 01:02:11 Trying to fetch new license...
2024/01/17 01:02:11 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:16 Trying to fetch new license...
2024/01/17 01:02:16 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:21 Trying to fetch new license...
2024/01/17 01:02:21 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:26 Trying to fetch new license...
2024/01/17 01:02:26 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:31 Trying to fetch new license...
2024/01/17 01:02:31 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:36 Trying to fetch new license...
2024/01/17 01:02:36 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:41 Trying to fetch new license...
2024/01/17 01:02:42 Failed to fetch license: Too Many Requests(429)
2024/01/17 01:02:46 Trying to fetch new license...
2024/01/17 01:02:46 New license fetched successfully
[GIN] 2024/01/17 - 01:04:34 | 200 |  994.229933ms | 192.168.119.155 | GET      "/api/accounts/check/v4-2023-04-27"
[GIN] 2024/01/17 - 01:04:35 | 200 |  339.581743ms | 192.168.119.155 | GET      "/backend-api/prompt_library/?limit=4&offset=0"
`

**环境信息（请完整填写以下信息）：**
- 操作系统：[Linux]
- 版本：[CentOS7]
- 架构：[例如 x86_64]

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by hnuzhoulin** [comment]
是因为IP发生变化才会重新获取licenseid吗？

**Comment by Rennix09** [comment]
same here https://github.com/pandora-next/deploy/issues/497
