### ISSUE TITLE
【求助】不好意思，没有start，抱歉，请问下今天遇到了登录提示不是官方站点的问题 该如何解决呢

### ISSUE THREAD

**Issue by lyzcodebool** [pandora-next/deploy#504]
<img width="463" alt="image" src="https://github.com/pandora-next/deploy/assets/28481065/64c69ba6-2f23-4f6c-8df5-df15f1d153e3">
🙏🏻

**Comment by rollexe** [comment]
我也是，我还以为更新 docker 镜像导致的。等修复吧

**Comment by wozulong** [comment]
被针对了，已修复。

**Comment by lyzcodebool** [comment]
已解决 非常感谢
