### ISSUE TITLE
【求助】佬，pandora现在是不是无法正常回复了，就在刚刚

### ISSUE THREAD

**Issue by dao-zero** [pandora-next/deploy#505]
**描述请求**
pandora无法正常响应，官网可以，说明账号没问题

**问题陈述**
阐述您面临的问题或您寻求帮助的原因。

**已采取的步骤**
描述您为解决问题已采取的步骤或您所做的研究。

**预期结果**
描述您期望得到的帮助或解决方案。

**截图/日志**

**环境信息（请完整填写以下信息）：**
- 操作系统：[例如 Windows、macOS、Linux]
- 版本：[例如 10、Catalina、Ubuntu 20.04]
- 架构：[例如 x86_64、arm64]

**正在使用的工具/框架**
[提供与此问题相关的特定工具或框架的信息。](https://chat1.zhile.io/)

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by wozulong** [comment]
我根本看不懂你要说什么
