### ISSUE TITLE
【求助】使用web模式的gpts时提示Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by iamyx123** [pandora-next/deploy#510]
**描述请求**
解决使用web模式的gpts时提示Our systems have detected unusual activity from your system. Please try again later.

**问题陈述**
使用web模式的gpts时提示Our systems have detected unusual activity from your system. Please try again later.

**已采取的步骤**
多次尝试输入验证码，但依然一直报错
**预期结果**
正常使用gpts

**截图/日志**
![c35da5a640a848b1ba462efee9ba5e8b](https://github.com/pandora-next/deploy/assets/88130457/290a3beb-ac5b-47a7-8965-715da9a0d7de)
![5259cc5e11d0aba90f55e294de006e40](https://github.com/pandora-next/deploy/assets/88130457/04739b3c-3a2f-4dbc-8a8c-a83c8416c18b)
![4309fb64b1c0f4f5242da3510c85ea4a](https://github.com/pandora-next/deploy/assets/88130457/c1666f15-deaa-40fd-a491-82ec7b622ab2)

**环境信息（请完整填写以下信息）：**
- 操作系统：windows
- 版本：11
- 架构：amd64

**Comment by feodorren** [comment]
同样的问题，待解决。

**Comment by xjy1592922966** [comment]
相同的问题，待解决。

**Comment by gao-jian-bin** [comment]
应该是被检测出来了

**Comment by wwbgit** [comment]
有大佬有解决方式吗？

**Comment by sw586** [comment]
相同的问题，待解决。

**Comment by xiaofutongxue1** [comment]
Our systems have detected unusual activity from your system. Please try again later.

也是这个问题

**Comment by wjuncn** [comment]
我也碰到了，在用 gpt-4 的时候会出现，用 gpt 3.5 就不会

**Comment by xyt417** [comment]
解决了？

**Comment by gao-jian-bin** [comment]
好了

**Comment by wozulong** [comment]
已更新至0.6.2解决了此问题。

**Comment by zrxxzz** [comment]
真的解决了嘛，我的重新上线服务或者重新登陆都不太行（4.0）

**Comment by zrxxzz** [comment]
是因为docker-hub还没最新的镜像吗0.0

**Comment by iamyx123** [comment]
我下载了0.6.2的release，但问题好像没有得到解决
![2b8355d63f6bd6c2bdd6cc2a8750279b](https://github.com/pandora-next/deploy/assets/88130457/9df76b15-44c7-4713-b132-2eb9eade66b0)

**Comment by zrxxzz** [comment]
我尝试了zhile.io的服务，好像时好时坏
