### ISSUE TITLE
【求助】我现在无法访问PandoraNext共享页显示404 This page could not be found.

### ISSUE THREAD

**Issue by DR-lin-eng** [pandora-next/deploy#516]
**描述请求**
我现在无法访问PandoraNext共享页显示404 This page could not be found.

**问题陈述**
我现在无法访问PandoraNext共享页显示404 This page could not be found.

**已采取的步骤**
升级镜像,重启镜像均无效

**预期结果**
需要解决

**截图/日志**
<img width="1918" alt="屏幕截图 2024-01-21 161237" src="https://github.com/pandora-next/deploy/assets/52230594/01eb8131-3f00-4c40-9cda-7c9d205f4d28">

**环境信息（请完整填写以下信息）：**
- 操作系统：CentOS 7
- 版本： 7.9.2009 
- 架构：x86_64

**正在使用的工具/框架**
提供与此问题相关的特定工具或框架的信息。

**相关代码片段**
如果适用，包括任何可能有助于解决问题的相关代码片段。

**附加背景**
添加任何其他您认为与您的请求相关的背景或信息。

---

请将占位符替换为您的具体详情，以创建一个全面的求助请求问题。

**Comment by DR-lin-eng** [comment]
![image](https://github.com/pandora-next/deploy/assets/52230594/185f2bd1-17bd-473a-89f5-824129164de9)
分享的选项也消失了

**Comment by rslywhj** [comment]
检查token.json
看share字段是否为true

**Comment by DR-lin-eng** [comment]
感谢解决
