### ISSUE TITLE
identify是什么呢？

### ISSUE THREAD

**Issue by sfvsfv** [pandora-next/deploy#55]
你好大神，我阅读了readme文档，并没有看到关于identify 的说明。

目前能够正常使用Access Token登录，但是进入界面的identify 不知道是什么。

目录：
![image](https://github.com/pandora-next/deploy/assets/62045791/8cc66e9d-4ed9-4b9f-ac5d-5951a5e9bef6)

配置：
![image](https://github.com/pandora-next/deploy/assets/62045791/1caae759-2813-4bc4-9751-d41ba328713a)

**Comment by wozulong** [comment]
官方用户名，或者你配置在tokens里的key，比如你这个test2
