### ISSUE TITLE
Gpt 4 gizmo disappeared

### ISSUE THREAD

**Issue by OmiiiDev** [pandora-next/deploy#56]
GPT-4 Gizmo "Alpha" disappeared from the site...

**Comment by yyxldr** [comment]
从https://dash.pandoranext.com/获取的token，貌似是无效的，一直提示无效的参数
2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments
2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments
2023/11/17 06:40:13 Unable to verify the server's license: token contains an invalid number of segments
2023/11/17 06:40:14 Unable to verify the server's license: token contains an invalid number of segments
2023/11/17 06:40:15 Unable to verify the server's license: token contains an invalid number of segments
2023/11/17 06:40:17 Unable to verify the server's license: token contains an invalid number of segments

**Comment by kelvinlee** [comment]
> 从https://dash.pandoranext.com/ 获取的token，貌似是无效的，一直提示无效的参数 2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:13 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:14 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:15 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:17 Unable to verify the server's license: token contains an invalid number of segments

用 listen 文件里面的 token . 不是网站上的值.

**Comment by smerckzak** [comment]
> > 从https://dash.pandoranext.com/ 获取的token，貌似是无效的，一直提示无效的参数 2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:12 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:13 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:14 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:15 Unable to verify the server's license: token contains an invalid number of segments 2023/11/17 06:40:17 Unable to verify the server's license: token contains an invalid number of segments
> 
> 用 listen 文件里面的 token . 不是网站上的值.

我直接用那串命令下载，然后就能启动了

**Comment by wozulong** [comment]
This bug has already been fixed by openai
