### ISSUE TITLE
大神，虚心请教

### ISSUE THREAD

**Issue by KrystalandBarry** [pandora-next/deploy#60]
大神，万分感谢，会考虑开源吗，一直在用，想继续沿用，并魔改一些前台界面

**Comment by wozulong** [comment]
> 大神，万分感谢，会考虑开源吗，一直在用，想继续沿用，并魔改一些前台界面

主要是把标抹了是吧？

**Comment by wozulong** [comment]
> 坐等锁定垃圾信息

并不会，那是脚本在扫白嫖。

**Comment by KrystalandBarry** [comment]
我想您误会了，首先非常感谢您的无私，分享这么好的项目给咱们，我也是一名开发，之前沿用pandora-cloud是和集团内部的ad域以及企微做了登录界面的改造集成，结合您的sharetoken和pooltoken，改标对咱的意义不大，但还是非常感谢您的好项目，谢谢
