### ISSUE TITLE
[Bug] v0.1.3 可能与 Supervisor 不兼容？

### ISSUE THREAD

**Issue by gltjk** [pandora-next/deploy#66]
我用 1Panel 的进程守护（背后是 Supervisor）运行 PandoraNext，之前一切正常，在升级 v0.1.3 后无法启动。配置文件内容如下：

```ini
[program:pandora_next]
command                 = /root/dev/pandora-next/PandoraNext
directory               = /root/dev/pandora-next
autorestart             = true
startsecs               = 3
stdout_logfile          = /opt/1panel/tools/supervisord/log/pandora_next.out.log
stderr_logfile          = /opt/1panel/tools/supervisord/log/pandora_next.err.log
stdout_logfile_maxbytes = 2MB
stderr_logfile_maxbytes = 2MB
user                    = root
priority                = 999
numprocs                = 1
process_name            = %(program_name)s_%(process_num)02d
```

我尝试在终端里运行 `supervisorctl start pandora_next:pandora_next_me_00` 仍启动失败，提示为 `ERROR (spawn error)` ，但如果降至之前的三个版本均能成功启动（显示 `started`）。

日志文件 `pandora_next.err.log` 里显示 `neither $XDG_CACHE_HOME nor $HOME are defined`，不知与此是否有关。

P.S. 在终端里直接运行 `./PandoraNext` 反而能成功启动，也不知道为啥……

**Comment by sunnywangzi** [comment]
在Supervisor中对应Pandora的配置文件里设置上environment就行

**Comment by gltjk** [comment]
> 在Supervisor中对应Pandora的配置文件里设置上environment就行

@sunnywangzi 感谢，在设置里加入 `environment = HOME="/root"` 后问题解决，但我不明白的是为什么 v0.1.3 才出现这个问题，以及未来是否有可能不需要这样。这个得问始皇帝了😂

**Comment by wozulong** [comment]
不是不兼容，是supervisor默认没有这个HOME环境变量，但这其实是每个linux/unix系统都存在的环境变量。
之所以0.1.3会出现这个问题，是因为把session存储放进了$HOME/.cache目录，也就是~/.cache目录。
原来的版本放在/tmp目录，但是由于系统的策略，/tmp目录下的文件可能会被莫名其妙清除导致掉登录状态。
0.1.3改掉了默认的存放目录，后面应该不会再改。
