### ISSUE TITLE
deploy on non-root path

### ISSUE THREAD

**Issue by WanQiyang** [pandora-next/deploy#67]
I am exploring using nginx to reverse proxy pandora-next and have encountered a slight inconvenience. The current version can only be deployed on the root path (`https://chat.example.com`), and there are issues when deploying it on a non-root path (`https://example.com/chat`).

It incorrectly requests
`https://example.com/auth/login?next=%2F`
, whereas the expected URL is 
`https://example.com/chat/auth/login?next=%2F`.

Could you please add an option for "baseURL" in `config.json` to facilitate deployment on a non-root path?

Thank you for developing such a nice project!

**Comment by wintopic** [comment]
请问为什么要说英文 :)

**Comment by wozulong** [comment]
I'm sorry, but the UI design of ChatGPT was never intended to be compatible with subdirectories from the beginning.
