### ISSUE TITLE
docker方式部署报错,Ping remote server failed, detail: Access denied

### ISSUE THREAD

**Issue by redquilt** [pandora-next/deploy#70]
错误信息：
============================================================
2023/11/18 08:48:59 Ping remote server failed, detail: Access denied., Ip: xxxx

这是我的ip被对方墙了吗？
这个机子的其它容器是可以访问外网的，应该不是docker转发的问题

**Comment by redquilt** [comment]
我先尝试了network_mode:bridge，又尝试了network_mode:host，两种都有这个错误

**Comment by redquilt** [comment]
解决了，是jwt没有在正确的ip地址获取

**Comment by 774649283** [comment]
我也是这个问题，
![image](https://github.com/pandora-next/deploy/assets/17950491/46f9f47d-e6f2-4de4-92c0-7320b8701baf)
![image](https://github.com/pandora-next/deploy/assets/17950491/af7e8db3-16b0-4d59-b177-32ac0d1e2523)
