### ISSUE TITLE
docker搭建仍然出错502 Bad Gateway

### ISSUE THREAD

**Issue by Evenjine** [pandora-next/deploy#71]
搭建好后使用网址出现：502 Bad Gateway
如果使用IP+断口号访问出现：
This page isn’t working right now xxx.xxx.xxx.xxx can't currently handle this request.
HTTP ERROR 502

**Comment by wozulong** [comment]
我建议你不要使用Docker。直接 ./PandoraNext

**Comment by Evenjine** [comment]
感谢🙏🏻多次回复，如果不用docker就更加不会搭建了，我想知道如果你那边使用docker能搭建成功的话我再仔细研究下。

**Comment by linxp001** [comment]
![image](https://github.com/pandora-next/deploy/assets/75927451/e09c7f26-eab2-4ef0-a29c-be998d22ee35)

![image](https://github.com/pandora-next/deploy/assets/75927451/b7a1ad16-8882-4d8e-9e16-18aa369783de)


我用docker配，配置文件这样写可以成功，希望可以帮到你。

**Comment by Evenjine** [comment]
> ![image](https://user-images.githubusercontent.com/75927451/284053469-e09c7f26-eab2-4ef0-a29c-be998d22ee35.png)
> 
> ![image](https://user-images.githubusercontent.com/75927451/284053534-b7a1ad16-8882-4d8e-9e16-18aa369783de.png)
> 
> 我用docker配，配置文件这样写可以成功，希望可以帮到你。

非常感谢🙏🏻，是配置问题，那个config和tokens.json都要设定对才行。还要在vps上面获取jwt，https://dash.pandoranext.com/

**Comment by cikichen** [comment]
nas上搭建这个，IP不知道填哪个，填127或者0或者nasIP都不行

**Comment by FiveHair** [comment]
> nas上搭建这个，IP不知道填哪个，填127或者0或者nasIP都不行

nas的config.json 填0.0.0.0:端口 ，
然后nas的docker那里映射填一样的端口
例子：
config.json 0.0.0.0:1234
docker        1234:1234

**Comment by cikichen** [comment]
> > nas上搭建这个，IP不知道填哪个，填127或者0或者nasIP都不行
> 
> nas的config.json 填0.0.0.0:端口 ， 然后nas的docker那里映射填一样的端口 例子： config.json 0.0.0.0:1234 docker 1234:1234

试过了，不行

**Comment by cikichen** [comment]
> > nas上搭建这个，IP不知道填哪个，填127或者0或者nasIP都不行
> 
> nas的config.json 填0.0.0.0:端口 ， 然后nas的docker那里映射填一样的端口 例子： config.json 0.0.0.0:1234 docker 1234:1234

可以了，要绑定容器的端口，比如1234:1233，需要绑定1233，不能绑1234
