### ISSUE TITLE
Shared Chat has GPT4 with plugins but not docker or vercel version

### ISSUE THREAD

**Issue by OmiiiDev** [pandora-next/deploy#75]
SharedChat:
![image](https://github.com/pandora-next/deploy/assets/103533638/990d61c7-db74-4e65-bcf1-6e0bae5ac838)

And Vercel/Docker version:
![image](https://github.com/pandora-next/deploy/assets/103533638/3b081a14-d46a-4772-93ca-07457b2a3ded)
![image](https://github.com/pandora-next/deploy/assets/103533638/72349f9a-36d2-41a4-b592-d3d8883a9d94)

Please explain  why it works on shared chat and not on any other version....

**Comment by wozulong** [comment]
What you are viewing on the chat-shared2 is a plus account, while your own account is a regular account.
