### ISSUE TITLE
运行时ping服务器报错

### ISSUE THREAD

**Issue by BBrother-GFC** [pandora-next/deploy#77]
在huggingface spaces上面运行的时候出现了错误，license.jwt也是正常放好了
![image](https://github.com/pandora-next/deploy/assets/51117375/5e74d084-37ff-4e53-be2a-52f6226d4553)

**Comment by BBrother-GFC** [comment]
> 在huggingface spaces上面运行的时候出现了错误，license.jwt也是正常放好了 ![image](https://user-images.githubusercontent.com/51117375/284061089-5e74d084-37ff-4e53-be2a-52f6226d4553.png)

没事了，我license.jwt没改好权限
但是huggingface spaces识别不到他已经开好了，一直在building状态（我不是docker pull运行的），请问如何才能让他成功识别到运行成功显示running呢？

**Comment by BBrother-GFC** [comment]
> > 在huggingface spaces上面运行的时候出现了错误，license.jwt也是正常放好了 [![image](https://user-images.githubusercontent.com/51117375/284061089-5e74d084-37ff-4e53-be2a-52f6226d4553.png)](javascript:void(0))
> 
> 没事了，我license.jwt没改好权限 但是huggingface spaces识别不到他已经开好了，一直在building状态（我不是docker pull运行的），请问如何才能让他成功识别到运行成功显示running呢？

![image](https://github.com/pandora-next/deploy/assets/51117375/c3cd6b29-011b-483c-8fd5-f4d21f9ac045)

**Comment by SmerckZak** [comment]
不是dockerpull怎么改成8080端口的？
