### ISSUE TITLE
虽然很讨厌docker,还是做出了docker部署PandoraNext的工具网站，支持在线管理PandoraNext,累死了！

### ISSUE THREAD

**Issue by Yanyutin753** [pandora-next/deploy#85]
项目地址：https://github.com/Yanyutin753/PandoraNext-TokensTool

php才是最好的语言，java真难，docker打包用国内服务器上传等的想死😂😂😂

**Comment by layui0320** [comment]
或许可以试试GitHub action打包上传docker

**Comment by gltjk** [comment]
建议始皇帝打开Discussions功能，让LZ把工具的更新记录放在那边。一方面可以避免开关太多issue，另一方面也可以把更新历史放在一起让读者看着有延续性。 @wozulong
