### ISSUE TITLE
共享账号网站可能存在恶意提问导致账号被封，建议对plus共享账号设置提问次数或者设置人工验证。

### ISSUE THREAD

**Issue by YeYeXuXu** [pandora-next/deploy#86]
共享账号网站可能存在恶意提问导致账号被封，建议对plus共享账号设置提问次数或者设置人工验证。

**Comment by jurieo** [comment]
你都共享出去了，自然要承担这个风险。怕承担就share:false

**Comment by YeYeXuXu** [comment]
共享账号毕竟有限，若对恶意破坏共享账号的行为不加制止，长期如此，共享网站恐怕会难以为继，而且也影响用户体验。望作者考虑采取一些简单的验证措施增加恶意提问的成本。

**Comment by wozulong** [comment]
怎么验证？之前搞验证码，大家又抱怨
