### ISSUE TITLE
关于frp穿透代理和图片无法显示显示的问题

### ISSUE THREAD

**Issue by goodve** [pandora-next/deploy#88]
1. bind 里面设置的是 lanip:10086,我现在用 frps  tcp代理映射(不是类似nginx 和caddy  代理的http)  公网ip:1086 转发过去直接503
   目测是  http 容器直接过滤了  非bind 里面来的请求。
2. chat中的图片好像是显示不了
![image](https://github.com/pandora-next/deploy/assets/17634299/ea03b2ca-7e2f-4224-82a2-3a25283b57e4)

**Comment by wozulong** [comment]
更新到最新版本

**Comment by goodve** [comment]
> 更新到最新版本

就是v0.2

**Comment by goodve** [comment]
代理本地绑定 0.0.0.0  就可以出去了

**Comment by goodve** [comment]
frp  代理那个，本地bind 0.0.0.0:port    就可以通过frp  反代出去了。
