### ISSUE TITLE
无法获得jwt

### ISSUE THREAD

**Issue by luwu4455** [pandora-next/deploy#94]
github账号created at2021-08-05T11:55:12Z
为何点击[https://dash.pandoranext.com/)依然提示注册时间不足180天，暂不提供服务。

**Comment by jurieo** [comment]
用大号

**Comment by luwu4455** [comment]
> 用大号

您好，我就是用的这个账号，没其他小号，不太明白为何不行

**Comment by lijuehua** [comment]
我也是，问题解决了嘛？
