### ISSUE TITLE
请问非共享账号如何实现会话隔离功能

### ISSUE THREAD

**Issue by jinglekang** [pandora-next/deploy#98]
我设置了密码，使用accessToken聊天文件会全部显示，感谢作者提供的工具。

刚刚忘记加星了，重发抱歉

**Comment by timing2022** [comment]
> 我设置了密码，使用accessToken聊天文件会全部显示，感谢作者提供的工具。
> 
> 刚刚忘记加星了，重发抱歉

可以看看这个
https://fakeopen.org/Pandora/Share%20Token%20%E7%9B%B8%E5%85%B3/%E6%8E%A5%E5%8F%A3%E5%88%97%E8%A1%A8.html

**Comment by wozulong** [comment]
使用share token。
